### ISSUE TITLE
Stepped fan to use slider setting

### ISSUE THREAD

**Issue by stijndevries** [merdok/homebridge-miot#1]
Hi Merdok, 

I created this issue before on the Mi fan plugin, which I currently use on the 1.3.1 version, but I would like to ask you to consider this again.

For fans with multiple steps, the are now toggles created for each fan speed. I think it would make more sense to use the old behaviour to have a slider that automatically adjusts to the closest value possible.
I understand that the current implementation is better from a technical standpoint but when using the Home app the old implementation just works way better. Could you add a toggle in the settings to use the slider behaviour?

Again, thank you for this excellent plugin!
Stijn

**Comment by merdok** [comment]
With this new plugin implementing such behavior should be actually easier to do so I will consider adding that. 

Please correct me if I am wrong, as far as I know the only fan which has levels but not steeples fan setting is the dmaker.fan.1c? At least from all the fans which the plugin supports that is the only one...

**Comment by merdok** [comment]
I added the stepless fan speed emulation in version 0.4.7. You can try it and let me know if it works.

**Comment by stijndevries** [comment]
Works fantastic! Thanks so much.
