### ISSUE TITLE
Standing Fan (zhimi.fan.za4) with controls is added, but does nothing

### ISSUE THREAD

**Issue by kikiwora** [merdok/homebridge-miot#100]
The device does not work, despite all configurations being correct.
[This plugin ](https://github.com/merdok/homebridge-xiaomi-fan#readme )works just fine.

Would you kindly include support of this device for us?

**Comment by kikiwora** [comment]
> Please specify your micloud credentials in the config to make it work!

Yeah, I did try that. No luck :(
The same credential, token, and IP works on other plugins, but not with this one :(

**Comment by merdok** [comment]
Then you need to post the debug log so we can have a look what the issue is.

**Comment by ahmadnazirafiq** [comment]
You can also try to use Discover All MiCloud devices up on top by keying in your credentials. It will find the fan and you should edit the configuration for it as well. I have the same model as yours and it works for me.
