### ISSUE TITLE
please add support for yeelink.light.strip4 

### ISSUE THREAD

**Issue by atuuling** [merdok/homebridge-miot#105]
yeelink.light.strip4
Yeelight Willow LED Lightstrip
2700K-6500K

https://www.joom.com/en/products/5efd44c7e67d17010612e1e4
- adjusting the different brightness according to the various scenes.
- 2700K-6500K free color temperature adjustment, warm or white light for option.

**Comment by merdok** [comment]
Then it seems that it is an older miio device which requires a micloud connection. Can you enter your micloud credentials in the config.json and see if it will then work?

**Comment by atuuling** [comment]
Yeelighter plugin find it without cloud, but there are no warm and cold functions 

it works through yeelight app and lan control is active

**Comment by merdok** [comment]
Yes, but i am asking if it works with this plugin already?

**Comment by merdok** [comment]
Like I already mentioned, this looks like an old miio device hence please try to specify your micloud credentials in the config.json and set the forceMiCloud flag to true, this way at least the on/off should work!

**Comment by merdok** [comment]
Support is now added as of version 0.9.17
