### ISSUE TITLE
Please add right functions and support for zhimi.heater.na1

### ISSUE THREAD

**Issue by atuuling** [merdok/homebridge-miot#106]
I add images from the application
https://www.dropbox.com/sh/qmrjovmpjmf7son/AACJqcv_lcy1BJr1vGqKUDQ-a?dl=0

https://www.geekbuying.com/item/Smartmi-2000W-Smart-Electric-Air-Heater-PTC-Ceramic-Heating---White-426239.html)
https://china-gadgets.com/smartmi-electric-air-heater-heater/

https://github.com/al-one/hass-xiaomi-miot/issues/74

**Comment by merdok** [comment]
Sorry i do not understand what you mean. Can you please explain what do you exactly have on your mind? Most of the functions are already available...
