### ISSUE TITLE
Need support for lumi.acpartner.v3 & lumi.acpartner.v2

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#107]
Hi,

I’ve been using lumi.acpartner.v3 and lumi.acpartner.v3 for awhile now. Unfortunately, the plugin for this device called Mi HeaterCooler by @jayqi is no longer in development, and a forked version were no longer published.

It’s an earlier version of lumi.acpartner.mcn02 with the exception that it has Zigbee hub built-in and an IR controller. I’m not sure if its using Mi Cloud or not but I remember the hoops of getting a developer mode activated via a forked version of Mi Home app on Android to use it with Homebridge.

If you need additional information, I’d be happy to provide. Thank you!

**Comment by merdok** [comment]
What kind of devices are those? When was those devices released?

**Comment by jayqi** [comment]
@ahmadnazirafiq - I think you tagged the wrong person. Good luck with whatever you're doing!

**Comment by merdok** [comment]
Support is now added as of version 0.9.17
