### ISSUE TITLE
Get air quality level from air purifier?

### ISSUE THREAD

**Issue by kaiserkiwi** [merdok/homebridge-miot#11]
Hi, I finally got this working (thanks for your help) and wanted to ask if it's possible to get the air quality level in HomeKit from the Air Purifier 3C? I'd love to set automations in HomeKit but right now I'm pretty limited without this information.

**Comment by merdok** [comment]
Your device supports PM2.5 Density reporting, so the Air Quality information should be available. Please note that the air quality is  not on the device group but on the air purifier accessory. You have display all the accessories on the air purifier group and there should be the air purifier accessory which should have that information.

**Comment by kaiserkiwi** [comment]
Ah I see. Thank you.
Is it possible you could add an optional parameter to set the quality level based on PM2.5 level? Just because it's not possible to set automations based on PM2.5.

**Comment by merdok** [comment]
Air Quality level should also be there, it is calculated based on the pm2.5 value.

**Comment by kaiserkiwi** [comment]
Sadly not. It just says "unknown".

![0ECB6B5E-E635-4DDF-BF1B-8972F1DEDB2B](https://user-images.githubusercontent.com/8428551/113755058-29b60e00-9710-11eb-9fa8-647519e343b4.png)

**Comment by merdok** [comment]
Hmmm, seems like a bug...
I see in the code that the air quality will only be shown when the device power is turned on. Is your device turned on or off? Does the device also measure the pm2.5 level when it is off?

**Comment by kaiserkiwi** [comment]
You're right. If I turn it on it instantly shows the quality level. But the moment it turns off its unknown again.

**Comment by merdok** [comment]
Ok then this is a logic mistake which i made 😅 For some reason i made a check that it only shows up when the device power is on which does not make sense...
Will fix that in the release! Sorry for that! Will let you know here when the update is available.

**Comment by kaiserkiwi** [comment]
Awesome! Thanks for you absolutely great support!

**Comment by merdok** [comment]
Should now be fixed in version 0.6.0. Please let me know if it works now.

**Comment by kaiserkiwi** [comment]
It's currently not shown as an update but I'll keep an eye on that and will comment on this issue after the update :)

**Comment by merdok** [comment]
Ok, seems HOOBS ha some delay with package updates...

**Comment by merdok** [comment]
@kaiserkiwi i think the update is already available on hoobs, could you test it?

**Comment by kaiserkiwi** [comment]
I just restarted my Pi and it finally showed up. It seems to work fine, but I'll keep an eye on it, when the air quality is worse.

Thanks for your awesome work!
