### ISSUE TITLE
Air conditioner partner as an outlet

### ISSUE THREAD

**Issue by obs945** [merdok/homebridge-miot#113]
I have lumi.aircondition.acn05 and buttons were successful created by homebridge-miot.
AC control button and fan level buttons all showed on Homekit app via homebridge. 
However, the purpose that I use air conditioner partner is used as an outlet (220V 16A outlet for my boiler).
My issue/problem is how to only create a button for control power on/off without showing/create ac control and fan level buttons.

**Comment by merdok** [comment]
Currently that is not possible. The device is being reported as an air conditioner hence you have air conditioner specific controls. I would need to think about it and see if i can come up with a solution for that...

**Comment by obs945** [comment]
Thanks for prompt reply. I think my purpose is a very special use case for AC partner. 
But still looking forward for a solution that AC partner can be local controlled in the future.

**Comment by merdok** [comment]
I mean your device has a lot of configuration properties exposed in spec and i guess some of them are also related to the outlet control. But since it is reported as an air conditioner, unrelated ones are currently ignored since they would just make the ui messy. But yeah i will think about it and see what i can do.

**Comment by obs945** [comment]
Below is the log from VEVS modified Mihome APP

2021-10-30 16:58:57 -> {"params":[{"siid":14,"piid":1,"did":"409038427","value":true}]} /miotspec/prop/set
2021-10-30 16:58:57 <- {"code":0,"message":"","result":[{"did":"409038427","siid":14,"piid":1,"code":0}]}
2021-10-30 16:59:04 -> {"params":[{"siid":14,"piid":1,"did":"409038427","value":false}]} /miotspec/prop/set
2021-10-30 16:59:04 <- {"code":0,"message":"","result":[{"did":"409038427","siid":14,"piid":1,"code":0}]}

These four lines are related to power on and off.
Hope above information is helpful for your implement.

**Comment by merdok** [comment]
You can now expose the outlet switch from you air conditioner as a `propertyControl` in version 1.0.0, i hope that this will solve your issue.

**Comment by obs945** [comment]
Thanks for your effort and this is really solve my issue.
Now situation is successfully power-on and power-off with two toggles and try to figure out how to set outlet switch status (true - false) in one toggle.

**Comment by merdok** [comment]
You can just skip the `value` property for the `propertyControl` and have one entry, when you do that then you should have 1 toggle switch which does what you want.
