### ISSUE TITLE
Cannot toggle temperature accessory on chuangmi.plug

### ISSUE THREAD

**Issue by duckalini** [merdok/homebridge-miot#114]
These accessories add a temperature sensor to Home. The temperature is from inside the outlet and is not the general room temperature.

Could you please add an Outlet Specific Setting to disable temperature so it's not visible in Home?
<img width="795" alt="Screen Shot 2021-10-31 at 2 11 29 PM" src="https://user-images.githubusercontent.com/23623393/139562704-716626e8-f83c-4f75-90f0-5be87e59bc6b.png">

**Comment by merdok** [comment]
Yes, that makes sense! Will add in the next release!

**Comment by oleg77s** [comment]
👍

**Comment by merdok** [comment]
You should not be able to remove the temperature as of version 0.9.17

**Comment by oleg77s** [comment]
It's ok now: "showTemperature": false 👍
