### ISSUE TITLE
Please add a new outlet device cuco.plug.cp1m

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#115]
I now add the cuco.plug.cp1m device model as cuco.plug.cp1 and it works fine, but the new device cuco.plug.cp1m has the LED control function

**Comment by merdok** [comment]
Will add full support for that outlet in the next update👍

**Comment by merdok** [comment]
Support is now added as of version 0.9.17

**Comment by louliangsheng** [comment]
In the latest version, cuco.plug.cp1m can be controlled, but the switch status is not obtained in time. Mihome displays on, but homekit displays off

**Comment by merdok** [comment]
You would need to post a homebridge debug log so I can see if there is any kind of an issue.

**Comment by louliangsheng** [comment]
[log.txt](https://github.com/merdok/homebridge-miot/files/7466542/log.txt)

**Comment by merdok** [comment]
You got timeouts, try to use micloud if it gets better or maybe  reduce the polling interval
