### ISSUE TITLE
Open question | Support for Roidmi Eve Plus 

### ISSUE THREAD

**Issue by avielc** [merdok/homebridge-miot#116]
Hi
Wanted to know if this will support Roidmi Eve Plus 
I know hass-xiaomi-miot by (al-one) supports it, but I really want it to be through Homebridge. 
Any chance it works? (I'd like to know before purchasing.)

Thanks!

**Comment by merdok** [comment]
If hass-xiaomi-miot supports it, then i am pretty certain that i can also add support for that device :) You would just need to provide me the correct model code for that device so i can lookup the correct spec.

**Comment by avielc** [comment]
oh wow thanks man! such a quick reply!
I'll have to purchase it though first, and that may take a little while 
but good to know, I'll keep you posted if I'll add it. 
I did a quick search and found this info
let me know if it helps
roidmi.vacuum.v60
https://home.miot-spec.com/spec/roidmi.vacuum.v60

**Comment by merdok** [comment]
Yeah, that looks good. Should be no problem to add the device!

**Comment by avielc** [comment]
Awesome thank you so much! 
by the way, that site has a huge list of all kinds of items, if you could "sync it" with the codes that this plugin can support - this should really make it epic mega-plugin for homebridge

**Comment by avielc** [comment]
While on topic
Any chance to add https://home.miot-spec.com/spec/roborock.vacuum.a10
Roborock S6MaxV (Has some interesting AI technology) 
(I have a dilemma which to purchase)

**Comment by merdok** [comment]
Also should be no problem 😉

**Comment by avielc** [comment]
Epic! Thank you!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18
