### ISSUE TITLE
Unable to connect with Viomi S9

### ISSUE THREAD

**Issue by flareman** [merdok/homebridge-miot#118]
As always, thanks for your great work.

I tried taking advantage of the latest Viomi S9 capabilities added in the last plugin version, but I'm having difficulties with it.

My Viomi is set up with a static IP (MAC address-based assignment from my router), it's online, it's taking commands from the Mi Home App, and I can ping the IP normally from command line and getting a response. The device is using firmware 1.6.5_2254 and is set up in the DE server, and the plugin version of the app is 43. I restarted Homebridge with the -D switch and the deep debug option enabled and this is what I got:

```
[3/11/2021, 6:33:18 μ.μ.] [miot] [Viomi S9] Got device configuration, initializing device with name: Viomi S9
[3/11/2021, 6:33:18 μ.μ.] [miot] [Viomi S9] Device info file does not exist yet!
[3/11/2021, 6:33:18 μ.μ.] [miot] [Viomi S9] Device model unknown! Starting discovery!

[...]

[3/11/2021, 6:33:20 μ.μ.] [miot] [Viomi S9] Error: Could not connect to device, handshake timeout
[3/11/2021, 6:33:20 μ.μ.] [miot] [Viomi S9] Could not connect to the device! Retrying in 42 seconds!

```
And the handshake timeout error occurs again every 42 seconds after that.

Am I doing something wrong? Should I define the device model manually and try again?

Again, thanks for all your efforts.

**Comment by merdok** [comment]
The handshake timeout might indicate the token is wrong, also you could try to reset your device.

**Comment by flareman** [comment]
A reset allowed the device to connect, thanks. Mopping, consumables life expectancy, per-room cleaning are not available, however. Is that normal?

**Comment by merdok** [comment]
Mopping and per room cleaning is available, you just need to configure that yourself using the `actionButtons` property. You can have a look here https://github.com/merdok/homebridge-miot/blob/main/lib/modules/robotcleaner/devices/viomi.vacuum.v18.js#L261 or check the homebridge log to see all available actions which you can enable and use. 
consumables life expectancy is right now only displayed in the log since there is no homekit ui control to do reasonable...

**Comment by flareman** [comment]
I managed to map the mopping function to a switch, thank you so much. I can't find how to perform per-room cleaning, as the log does not mention something, but I'm covered for now. Thank you :)
