### ISSUE TITLE
Make air quality level configurable?

### ISSUE THREAD

**Issue by kaiserkiwi** [merdok/homebridge-miot#12]
Hi. I know I'm a bit annoying but I've another question. Or better: This time a feature request.

In the `AirPurifierAccessory.js` is the following part
```
if (pm25Density <= 7) {
return Characteristic.AirQuality.EXCELLENT;
} else if (pm25Density > 7 && pm25Density <= 15) {
return Characteristic.AirQuality.GOOD;
} else if (pm25Density > 15 && pm25Density <= 30) {
return Characteristic.AirQuality.FAIR;
} else if (pm25Density > 30 && pm25Density <= 55) {
return Characteristic.AirQuality.INFERIOR;
} else if (pm25Density > 55) {
return Characteristic.AirQuality.POOR;
}
```

I understand these values are based on some research, but I'd love to configure this, so I could finetune my automations a bit more. Other plugins that don't work with my air purifier had a simple array for this, where one could simply add five values for this.

Would it be possible to add this to your plugin?

**Comment by merdok** [comment]
Yes, that would be possible. I will add that in the next update 👍

**Comment by merdok** [comment]
As of version 0.6.3 you can now configure custom pm25 breakpoints. Just use the new `pm25Breakpoints`. Please let me know if it works as expected :)

**Comment by kaiserkiwi** [comment]
Maybe I've configured it wrong, but currently it doesn't seem to work.
In the first Screenshot are the test value I put in to try it out. In the second one you can see the quality level in my Home app. In German the highest level is "Sehr gut". But despite the fact I configured 10 for the first change, it says "Gut" at 8. 
![IMG_0528](https://user-images.githubusercontent.com/8428551/115225156-07f45800-a10e-11eb-8039-26a1129d860e.PNG)
![IMG_0529](https://user-images.githubusercontent.com/8428551/115225165-0aef4880-a10e-11eb-91a1-40861e5f1cc5.PNG)

**Comment by merdok** [comment]
There are 4 breakpoints for pm2.5
I see you have 5 which is wrong.
I added a strict check to make sure that the provided values are correct, if they are not then it will revert to the default values. Probably it would make sense to also show a warning in that case in the console.
Anyway please adjust your breakpoint to 4 values and try again.

**Comment by space-squad** [comment]
Makes sense. 😅 
As always: Thanks for your great support.
I will keep an eye on the numbers an will let you know soon if it works. :)

**Comment by kaiserkiwi** [comment]
Makes sense. 😅
As always: Thanks for your great support.
I will keep an eye on the numbers an will let you know soon if it works. :)

**Comment by kaiserkiwi** [comment]
Okay. I finally had the chance to see the levels changing. It works like a charm. Thank you so much for your support!
