### ISSUE TITLE
Add support for yeelink.light.mono4

### ISSUE THREAD

**Issue by shahrilamrias** [merdok/homebridge-miot#121]
Added through plugin auto discovery.
Forced micloud and still wasn't able to turn on/off the light.

I got a ```no response``` in Homekit and the following in HB -D
```
[07/11/2021, 10:41:39] [miot] [Porch Left] Error: Could not connect to device, token might be wrong
[07/11/2021, 10:41:39] [miot] [Porch Left] Could not connect to the device! Retrying in 42 seconds!
```
I assume this is normal since it wasn't implemented in the plugin.

I believe this should be the [spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:light:0000A001:yeelink-mono4:1) for it

**Comment by merdok** [comment]
Yes, it is not implemented, but nevertheless turning the light on/off should already work. Your error indicates that no connection cannot be made to the device, it is either offline, you specified the wrong ip or the wrong token.

**Comment by shahrilamrias** [comment]
I checked the the availability, ip and token and they all seem correct.

I have a few ```yeelink.light.mono4``` and ```yeelink.light.color4``` bulbs around the house and have been using the Yeelight app to control my bulbs.  

So I installed MiHome and surprisingly only the ```color4``` bulbs show up in MiHome app. I can't figure out why all my ```mono4``` won't appear in MiHome but appears in Yeelight app. Even after reset. 

My wild guess is that Mi support for this specific bulb is broken. That or my bulb is just stupid. 

I ended up directly adding them through the Homekit pairing code. I forgot that option exist with this bulb 😅

**Comment by merdok** [comment]
Did you enable "lab control" for the bulb in the yeelight app?

**Comment by shahrilamrias** [comment]
Yes, they’re all already toggled on in lan control.

**Comment by merdok** [comment]
Then there is another issue with your device. As long as it is unreachable in the network then you won't be able to control it.
