### ISSUE TITLE
Roborock S5 MAX support

### ISSUE THREAD

**Issue by Reddyzinho** [merdok/homebridge-miot#122]
Hello There :) This plugin is amazing. Can you please support the ROBOROCK S5 MAX? It obtain the TOKEN, but doesn’t work and on the log, it says that I have to contact support to get this working :) Can you please consider this device on your plugin? ….please?? ;)

**Comment by merdok** [comment]
Sure, but can you tell me that model of your device? It should appear in the log...

**Comment by Reddyzinho** [comment]
Thanks for your reply. The model is this: roborock.vacuum.s5e

**Comment by merdok** [comment]
Thanks! will add update for it in the next update!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18
