### ISSUE TITLE
Add support for the  leshow.heater.bs3

### ISSUE THREAD

**Issue by zlldnv** [merdok/homebridge-miot#123]
Actually all of the staff is working except the auxiliary fan, Could you please add support of that, if possible, thanks!
![IMG_0366](https://user-images.githubusercontent.com/19211379/140888998-eb7322aa-9928-4813-a422-89f0cb916d0d.jpeg)

**Comment by merdok** [comment]
Will add support for it in the next release.

**Comment by zlldnv** [comment]
@merdok would need a help with that?

**Comment by merdok** [comment]
Thanks, but no help needed 👍  In the next version the heater including the fan option should be fully supported!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18
