### ISSUE TITLE
How to set default mode to auto for air purifier?

### ISSUE THREAD

**Issue by Neoplanetz** [merdok/homebridge-miot#127]
Hi, first of all, thanks for your plug-in.

I have Mi Air Purifier Pro H model.

and install miot plug-in and set name, ip, token, model, pollingInterval.

buzzer and led control is set false, fan level and mode control is set also false.

after restart my homebridge, everything worked only except one thing.

the one thins is when I turn on air purifier by apple homekit, the air purifier is always set manual mode(favorite mode).

and manual mode(favorite mode)is always full fan speed.

 so what I want to do when turning on the air purifier is set auto mode as a default fan mode.

how can I set default air purifier fan mode to auto mo when I turn on it ?

**Comment by merdok** [comment]
There should be a possibility to set the air purifier mode to auto in the home app, i think this is what you are looking for.
