### ISSUE TITLE
Viomi SE vacuum support

### ISSUE THREAD

**Issue by GaborSchM** [merdok/homebridge-miot#133]
Hi, would it be possible to add support for Viomi SE robot vacuum? 

Many thanks

**Comment by merdok** [comment]
Should generally be possible, but i would need the exact model name of your device so that i can find the corresponding specification.

**Comment by GaborSchM** [comment]
Thanks for your quick feedback 

[](https://www.viomi.com/robot-vacuums/viomi-se)

This guy here I cannot find a more exact name for the device, even in the xiaomi app I see only the FW information which could be helpful 4.0.9_0017

**Comment by merdok** [comment]
This is unfortunately not helpful. Just add your device to the plugin including the token and enable homebridge debug log. The information that the device is not supported should popup and it will also display the device model.

**Comment by GaborSchM** [comment]
Sorry for this. 

Seems to be viomi.vacuum.v19

**Comment by merdok** [comment]
Yeah, that looks looks like the correct one! Thanks! Will add it in the next update!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18

**Comment by GaborSchM** [comment]
Seems to be perfect, thanks a lot!!
