### ISSUE TITLE
Please add support  Viomi water heater

### ISSUE THREAD

**Issue by danielkit83** [merdok/homebridge-miot#136]
Hi,

Would it be possible to support viomi water heater? Many Thanks

Device Model
viomi.waterheater.e8

22/11/2021, 23:43:33Miot Bridgemiot[Water Heater] Got device configuration, initializing device with name: Water Heater
22/11/2021, 23:43:33Miot Bridgemiot[Water Heater] Device model known: viomi.waterheater.e8! Creating device!
22/11/2021, 23:43:33Miot Bridgemiot[Water Heater] Initializing device properties
22/11/2021, 23:43:33Miot Bridgemiot[Water Heater] Initializing device actions
22/11/2021, 23:43:33Miot BridgemiotWARNING[Water Heater] Device not supported! Using a generic device with limited properties! Consider requesting device support!

Best Regards,
Daniel

**Comment by merdok** [comment]
Should be possible. Will add support in the next update!

**Comment by danielkit83** [comment]
> Should be possible. Will add support in the next update!

Many thanks for your support

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18

**Comment by danielkit83** [comment]
![WeChat Image_20211203160243](https://user-images.githubusercontent.com/88359393/144567045-a1dc691e-56e7-4e27-bbe9-2a00304b3854.jpg
![WeChat Image_20211203160237](https://user-images.githubusercontent.com/88359393/144567070-095036fd-df9e-48d5-9f1e-62848af7d670.jpg)
)

**Comment by danielkit83** [comment]
![IMG_5551](https://user-images.githubusercontent.com/88359393/145018087-ac703283-33d4-4aaf-9135-e844e4633ea2.PNG)

![IMG_5552](https://user-images.githubusercontent.com/88359393/145018137-d58ae1e4-80f0-408e-8839-ef190709a714.PNG)

Viomi water heater is not a Kettle. It is a bath water heater. Besides, I can't turn on the bath water heater in homekit. In homekit, it is only able to show the water temp and always showing turn off even though it is in heating mode.

Please kindly help to see whether we can control the heater in homekit. Many many thanks

**Comment by merdok** [comment]
Oh, is it not a kettle? You should have mentioned that in the beginning since most of the device s I usually never even heard of before...

I can have a look at it again but it will take quite some time till I have time to do that...

**Comment by danielkit83** [comment]
Sorry for my misleading information. Thanks for your help

**Comment by merdok** [comment]
Should now be fixed in version 1.0.0
