### ISSUE TITLE
Please add support for Mi Bedside Lamp (yeelink.light.bslamp1)

### ISSUE THREAD

**Issue by mrmaximas** [merdok/homebridge-miot#137]
Subj
Thks

**Comment by merdok** [comment]
Will add in the next update!

**Comment by mrmaximas** [comment]
Thanks!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18

**Comment by mrmaximas** [comment]
> The device should now be supported as of version 0.9.18

thanks! it's works. but login to mi cloud required.

**Comment by merdok** [comment]
Based on my research this is an older device using the miio protocol, hence mi cloud is required to control it using the miot protocol.

**Comment by mrmaximas** [comment]
It's works fast, but first plugin discover ask me for cloud log/pass

**Comment by merdok** [comment]
Yes, like i said above, mi cloud login is required for your device, without mi cloud it will not work!
