### ISSUE TITLE
Please add support for Mi Smart Air Conditioner Controller Pro (lumi.acpartner.mcn04)

### ISSUE THREAD

**Issue by chrhee21** [merdok/homebridge-miot#140]
Mi Smart Air Conditioner Controller Pro (lumi.acpartner.mcn04) was released several month ago.
If support for this device is added, it will be very helpful.

**Comment by merdok** [comment]
Will be added in the next update!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.18
