### ISSUE TITLE
Please add support for Mi Mosquito lamp (dayang.mosq.dyt16s), MI Pet water dispenser (skyrc.pet_waterer.fre1), Remote control (chuangmi.remote.v2), Massage Pillow (17216.pillow.pl008).

### ISSUE THREAD

**Issue by Nooshie** [merdok/homebridge-miot#141]
Hello and thanks for reading the following request's

Please add support for the following 
Mi Mosquito lamp (dayang.mosq.dyt16s)
MI Pet water dispenser (skyrc.pet_waterer.fre1)
MI Remote control (chuangmi.remote.v2)
MI Massage Pillow (17216.pillow.pl008)

Thank you!!!

**Comment by merdok** [comment]
Hi,

all of the devices are quite strange and do not fit any standard services. A couple of info:

- Mi Mosquito lamp (dayang.mosq.dyt16s) - **should work already now as a generic device**
- MI Pet water dispenser (skyrc.pet_waterer.fre1) - **should also work already now as a generic device**
- MI Remote control (chuangmi.remote.v2) - **the spec for this device is empty...? not sure why**
- MI Massage Pillow (17216.pillow.pl008) - **requires a new module which i cannot add right now**

**Comment by merdok** [comment]
As of version 1.0.0 you can now add all of your devices to the plugin and use the `propertyControl` to expose any functionally which you would like. It would look something like this:

```
        {
          "name": "miot device",
          "ip": "ip",
          "token": "token",
          "model":"17216.pillow.pl008",
          "propertyControl": [
            {
              "property": "2.2",
              "name": "Pillow"
            },
            {
              "property": "3.1",
              "name": "Massager"
            }
          ]
        }
```
