### ISSUE TITLE
Can not get my air purifier 2S to work

### ISSUE THREAD

**Issue by roberkane212** [merdok/homebridge-miot#143]
It says it’s set up however I don’t see it in my logs and it is unresponsive in HomeKit.

**Comment by merdok** [comment]
You need to provide more context, like debug log and config.json entry. Without that it will be impossible to say what your issue is...

**Comment by roberkane212** [comment]
@merdok this issue is fixed, the plug-in gave me a us region token for some reason. I found out how to get the mainland china token and it works not thanks
