### ISSUE TITLE
Xiaomi Mijia 1C.

### ISSUE THREAD

**Issue by Carlos-fraile** [merdok/homebridge-miot#144]
Hello SIR!

First thank you for this plugin !! it's great! 

My problem is that i have a xiaomi 1c, but i can't get it to work. I have read and followed all the steps and the device appears in my Home app but is not responding. 

Could you help me?, the same thing happens with my xiaomi security hub. 

THANK YOU VERY MUCH!!

**Comment by merdok** [comment]
You did not provide any information which might allow me to help you. You would need to post some debug log and your config.json entry.

Without that info a wild guess would be that your token or device is wrong.

**Comment by Carlos-fraile** [comment]
Thanks! I tried to obtain the token in other ways, I tried the automatic mode of the plugin and it seems to be correct, checking the logs this is what it indicates:

[12/01/2021, 10:46:13] [homebridge-miot] [Chulii] Error: Could not connect to device, handshake timeout
[12/01/2021, 10:46:13] [homebridge-miot] [Chulii] Could not connect to the device! Retrying in 42 seconds!

 and my config.json:

{
            "devices": [
                {
                    "name": "Chulii",
                    "ip": "192.168.6.129",
                    "token": "5162694f46327044637a4f757a676d72",
                    "deviceId": "382766893",
                    "model": "dreame.vacuum.mc1808",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                    "micloud": {
                        "username": "25067 ***",
                        "password": "***",
                        "country": "de",
                        "timeout": 5000
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "showTemperature": true
                }
            ],
            "_bridge": {
                "username": "0E: E3: E5: 9D: 03: 37",
                "port": 45767
            },
            "platform": "miot"
        },

**Comment by merdok** [comment]
If you are certain that your token is correct then you would need to try to reset the device. A handshake timeout is usually solved after resetting the device. Please note that when you reset the device, the token will change.

**Comment by Carlos-fraile** [comment]
OKAY! Thank you! I'll try

**Comment by Carlos-fraile** [comment]
Wow! Fixed up!!! Thank you very much MASTER !!!
