### ISSUE TITLE
Setting fan speed to auto for air purifiers

### ISSUE THREAD

**Issue by JonoHaysom** [merdok/homebridge-miot#145]
Hello, I can't find a way to set the Xiaomi 3H to "auto" it always forces it into "manual" speeds. is there a fan level or switch that can be put in the settings to allow "auto"?

**Comment by merdok** [comment]
You should be able to do that directly on the accessory, if not then simply enable "modeControl" which should show you switches to control the device mode.

**Comment by JonoHaysom** [comment]
yup! that did the trick! thanks so much for your amazing work
