### ISSUE TITLE
New Device support request isa.camera.hlc6

### ISSUE THREAD

**Issue by wojciej** [merdok/homebridge-miot#146]
Hello,
Can I kindly request a support for Xiaomi Mijia 1080P 170 ° Smart IP CAM (MJSXJ02HL) isa.camera.hlc6.

Please let me know if you would need more details.
Thanks

**Comment by merdok** [comment]
Hi,
for camera it will only be possible to control so basic settings of the camera but it will not be possible to see the video stream. For that i would need to physically have such camera, which i do not...
