### ISSUE TITLE
New device support request cgllc.airmonitor.b1

### ISSUE THREAD

**Issue by wojciej** [merdok/homebridge-miot#148]
Hello,
Can I kindly request a support for Xiaomi Air Quality Monitor (cgllc.airmonitor.b1).

Please let me know if you would need more details.
Thanks

**Comment by merdok** [comment]
Hi,
this is a completley new device type which requires me to first prepare the module for such devices. Since i am currently preparing a bigger update, it will take me some time to implementet that (probably no sooner then january)

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
