### ISSUE TITLE
Add light yeelight GU10 smart bulb w1 (dimmable)

### ISSUE THREAD

**Issue by koctya1212koc** [merdok/homebridge-miot#149]
Good day! To begin with, I would like to thank you for developing this functionality. Works very well.
 I wanted to ask you to add a new product. It works but in a limited way (you can only turn it on and off) I would like to ask you to modify the functionality with the ability to control the intensity (dimmable) product yeelight GU10 smart bulb w1 (dimmable) yldp004.
This is how the product is defined in the plugin (Model yeelink.light.monob).

**Comment by merdok** [comment]
Hi,
that should be no problem but since i am currently working a big update it will take a while till i can add full support for your device (probably not sooner then in january) so you need to be patient...

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
