### ISSUE TITLE
Xiaomi Purifier 3C new revision support

### ISSUE THREAD

**Issue by itarikadev** [merdok/homebridge-miot#150]
Xiaomi Purifier 3C now has a few revisions:

zhimi.airpurifier.mb4 (old one, fully supported)
**zhimi.airp.mb4a** (new one, partically supported - only on/off)

BUT, if you fill "model" in config manually as old one - all works!

MANY THANKS to @merdok! Hope this issue will fix soon)

**Comment by merdok** [comment]
Thanks!
Due to me currently working on a bigger update, the soonest i can add full support for the device will be january, but since it works with the old model then it should be fine for now!

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
