### ISSUE TITLE
New device support request yeelink.bhf_light.v1 (Yeelight Smart Bathroom Heater Pro)

### ISSUE THREAD

**Issue by samuelchchan** [merdok/homebridge-miot#155]
link: https://item.jd.com/100007107268.html
Name：Yeelight Smart Bathroom Heater Pro
Model Name: yeelink.bhf_light.v1
model number：YLYB005

**Comment by merdok** [comment]
Hi,

should be possible, although it will take some time since I am currently working on rebuilding the plugin.

**Comment by merdok** [comment]
Support is now added in version 1.0.0!

**Comment by merdok** [comment]
Should be fixed in version 1.0.1
