### ISSUE TITLE
yeelink.light.color5 control doesn't work

### ISSUE THREAD

**Issue by MonStar1** [merdok/homebridge-miot#158]
Give me know could I get additional info to help you fix it

**Comment by merdok** [comment]
You would need to provide the homebridge debug log and your config, without there is no way for me to know that your issue is.

**Comment by MonStar1** [comment]
[homebridge.log (1).txt](https://github.com/merdok/homebridge-miot/files/7761727/homebridge.log.1.txt)

I have at least two devices. They doesnt work. 
Lamp didn't work every time.
Dreame L10 Pro stopped work some days ago

**Comment by merdok** [comment]
For the lamp, it is probably a micloud only device. For that you would need to try to specify your micloud credentials in the config with the forceMiCloud parameter set to true and then try it.

As for the vacuum, it seems that either the token or device ip changed since a connection cannot be established to that device.

**Comment by MonStar1** [comment]
https://github.com/CorsairCat/homebridge-mi-philips-light
The plugin homebridge-mi-philips-light lets me turn on, turn off and dimming the lamp. Here is my config for the plugin
Think some API is similar, because coloring doesn't work
`                {
                    "type": "MiPhilipsSmartBulb",
                    "ip": "192.168.31.175",
                    "token": "023ad7d67207e446f****",
                    "lightName": "ColorLamp",
                    "lightDisable": false
                }`

**Comment by merdok** [comment]
Sorry, I do not understand what you mean an what the other plugin has to do with this. 
You should try the suggestions which I gave you and let me know if that fixes your problem.

**Comment by MonStar1** [comment]
I mean it is not Micloud only device and it is possible control device localy, because it works for other plugin

Force micloud option works for the lamp, but still doesn't work for the vacuum cleaner
[12/22/2021, 2:11:41 PM] [miot] [cleaner] Error: Could not connect to device, handshake timeout
[12/22/2021, 2:11:41 PM] [miot] [cleaner] Could not connect to the device! Retrying in 42 seconds!

**Comment by merdok** [comment]
When forceMiCloud works for the lamp then it is a miot device which only works with micloud. The other plugin uses the older miio protocol which this plugin does not support, hence micloud is required!

For the vacuum your issue is different, your specified token or ip is incorrect!
