### ISSUE TITLE
New device: support for a new mijia airer model

### ISSUE THREAD

**Issue by DotIN13** [merdok/homebridge-miot#160]
The new model I bought is detected `hyd.airer.znlyj4` by the plugin. I suspect it will work with the old model implementation `znlyj1` but I have not tested the compatibility yet.

As I know the almighty author is working on something gargantuan, I think we can probably just add it to the WIP list and get back to it later.

**Comment by DotIN13** [comment]
Here's the device spec:

https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj4:1

**Comment by merdok** [comment]
Will add for a later implementation, in the meantime you can try to use the old device as model and see if that works!

**Comment by merdok** [comment]
Can you tell me what the official name of the device is?

**Comment by DotIN13** [comment]
Should be Xiaomi Mijia Smart Clothes Dryer, model ZNLYJ01HYD.

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
