### ISSUE TITLE
Possibility to assign rooms to the devices

### ISSUE THREAD

**Issue by Seger85** [merdok/homebridge-miot#169]
As mentioned in the title. can you add the option of entering the room per device?

thank you very much for your great work!

**Comment by Seger85** [comment]
My Device: Xiaomi Purifier 3C

**Comment by merdok** [comment]
Sorry, I do not quite understand what you mean with entering the room per device, can you please try explain more?

**Comment by Seger85** [comment]
So that I can already assign the corresponding final room to the respective device.

If I add a device today (via plugin) all devices end up in the hallway/standard room.

Now I would like to assign e.g. device 1 to the living room, device 2 to the kitchen and so on. - so that the devices do not all show up in the standard room. This would also clean up the designations:

Today the device 1 is called e.g.
Air purifier kitchen
But should only be called air purifier and stand in the room kitchen

**Comment by merdok** [comment]
This is something i cannot change! This is how HomeKit behaves. All new devices which you add will be added to the "Standard room". After that you can easily move them in the Home app to whatever room you want and they will stay there.

**Comment by Seger85** [comment]
Okay Thanks a lot!!!
