### ISSUE TITLE
A comfy and secure way to store Mi Cloud settings

### ISSUE THREAD

**Issue by kikiwora** [merdok/homebridge-miot#171]
Regarding the authentication, I have a few questions - something is bothering me. 
I've noticed it after adding a few devices to this plugin.

Is the way login-password pairs have been stored up to this moment a necessity?
We, users, have to duplicate the same data for each of our devices (login, password, server, isForced flag), while the passwords are not protected at all, they're completely open.

I have a feeling that it would be better to store credentials (password) at Keychain (macOS), for example (so only the key is listed in the config file). With a choice for the user, to store it securely or openly, ofc.

And it would be nice to have one place to define "default" login-password and server for all devices, with an option to override these params for each device.

For example, I have all my devices at the DE server, and only one of my devices at the CN server, but all of them are bonded to the same account.

**Comment by merdok** [comment]
Unfortunately as far as i know the login credentials cannot be stored in the Keychain (macOS) or any other secure storage, but storing the login credentials in the config.json is generally secure, given that you properly secured your device running homerbidge and your network.

MiCloud should normally only be used as a gateway to control older devices, of course you also can control newer devices over MiCloud using the `forceMiCloud`, but that usually does not give you any benefit over local control and sometimes can increase the latency.
In general i was thinking to have a global setting for MiCloud credentials but given that most devices can be controlled using the local commands and that sometimes users not only have devices on different servers but also different accounts, i decided to leave it as a per device setting. 
Yeah it can be annoying when someone has multiple devices that require MiCloud, but in the end it reduces complexity adn gives the user a better overview on which devices uses MiCloud and which not.

**Comment by merdok** [comment]
Regarding the "default" micloud credentials for all devices, in the next update there will be a possibility to set global micloud settings which will be used by all devices! When a device requires a micloud connection then it will use the global ones, devices which does not need a micloud connection will ignore that.
You will also be still able to set per device micloud settings, so you can force single devices to use micloud or specify the country per device. That way you will not need to specify the login details multiply times! 
That should improve the config file and there will be no need to specify that multiply times!

**Comment by merdok** [comment]
Global MiCloud credentials is now added in version 1.0.0
