### ISSUE TITLE
Log filtering

### ISSUE THREAD

**Issue by MariusAnje** [merdok/homebridge-miot#172]
Device frequently outputting warning logs.

Device: zhimi.humidifier.cb1
Log: [$time$] [miot] [Smartmi Evaporative Humidifier] The property target_humidity was not found on this deivce!

This is a valid log because this humidifier has no target_humidity function. However, this warning appears at every polling period.

Is it possible that this log be filtered/removed?

**Comment by merdok** [comment]
Yeah, humidifier devices without target_humidity should actually only show an on/off switch. I will try to adjust that in the next update.
The logs, especially warning logs, are there for a reason so it is not possible to remove them. Warning logs indicate an issue which needs to be adjusted.

**Comment by MariusAnje** [comment]
Thanks a lot for your quick response & effort

**Comment by merdok** [comment]
Should now be fixed in 1.0.0
