### ISSUE TITLE
Roidmi Vacuum v60 (EVE PLUS)

### ISSUE THREAD

**Issue by Stubmake** [merdok/homebridge-miot#173]
Good afternoon, I connected my Roidmi EVE Plus vacuum cleaner, and without MiCloud connected, it refused to work at all, after connecting MiCloud, the vacuum cleaner can only turn on, it cannot turn off. The status of the vacuum cleaner at the charging station does not work - it always shows "no".

**Comment by merdok** [comment]
Hi, what is the model of your device?

**Comment by Stubmake** [comment]
model roidmi.vacuum.v60

**Comment by merdok** [comment]
I see that this model is not yet fully supported so proper support needs to be added. You could temporarily try to use model roidmi.vacuum.v6 as the model and see if that helps.

**Comment by Stubmake** [comment]
Ah, sorry, I thought it was the same model

**Comment by Stubmake** [comment]
if you use the roidmi.vacuum model.v6, controls are not displayed.

**Comment by merdok** [comment]
In that case you need to wait for proper support for your device.

**Comment by merdok** [comment]
Oh, somehow i mistook here. I see that the v60 is already supported so it should actually work (not sure how i missed that, sorry...)

**Comment by Stubmake** [comment]
[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/7923084/homebridge.log.txt)
Good afternoon, the token is correct, I choose the automatic search for a vacuum cleaner, attach the log.

**Comment by Stubmake** [comment]
[homebridge.log (1).txt](https://github.com/merdok/homebridge-miot/files/7923198/homebridge.log.1.txt)

**Comment by merdok** [comment]
Hi, from the second log it seems that everything is fine. The properties are syncing and the one error which appears should not cause any issues.
