### ISSUE TITLE
Please add AirPurifier2S ( zhimi-airpurifier-mc1 ) and  MiFan2S ( zhimi-fan-za4 )

### ISSUE THREAD

**Issue by Terminator0007** [merdok/homebridge-miot#18]

**Comment by merdok** [comment]
Unfortunately both do not use the miot protocol but the old miio protocol. The fan is supported in my other plugin homebridge-xiaomi-fan so you might want to check that out.

**Comment by Terminator0007** [comment]
Ok, thanks !
Jacek


dnia 26 kwietnia 2021 o 12:09:43, Marcin ***@***.***) napisał:

Closed #18 <https://github.com/merdok/homebridge-miot/issues/18>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/merdok/homebridge-miot/issues/18#event-4643848672>, or
unsubscribe
