### ISSUE TITLE
Xiaomi Air purifier Pro H not support

### ISSUE THREAD

**Issue by BaskaraR** [merdok/homebridge-miot#182]
Hi ,
I'm using version vb2a region MY to be able to connect to Mi app
"name": "Mi Air Purifier Pro H",
                    "ip": "192.168.68.59",
                    "token": "xxxxxxxxxx",
                    "deviceId": "407914088",
                    "model": "zhimi.airp.vb2a",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                   

and I'm getting this msg in debug

27/01/2022, 16:22:07] [homebridge-miot] [Mi Air Purifier Pro H] Device not supported! Using a generic device with limited properties! Consider requesting device support!
[27/01/2022, 16:22:07] [homebridge-miot] [Mi Air Purifier Pro H] Initializing accessory!
[27/01/2022, 16:22:07] [homebridge-miot] [Mi Air Purifier Pro H] Accessory Factory - Creating Unknown accessory for device Mi Air Purifier Pro H!

pls assist. thanks

**Comment by merdok** [comment]
Will add support for that device in the next update!
