### ISSUE TITLE
Hello, please add support for this device

### ISSUE THREAD

**Issue by KuznecKA** [merdok/homebridge-miot#183]
yunmi.kettle.v12
_The unique model of your device, e.g zhimi.fan.za5._

Mi Smart Kettle Pro
_The friendly name of the device used by the manufacturer, e.g. Smartmi Standing Fan 3._

Do not know
_Yes/No/Do not know_
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
Will add support for that device in the next update!

**Comment by merdok** [comment]
@KuznecKA i do not see a device with the model: `yunmi.kettle.v12` Are you sure this is the correct one?

**Comment by KuznecKA** [comment]
Mi Smart Kettle Pro
IP: 80.76.110.187
MAC: A4:C1:38:82:3C:58
Token: 36f5205beab14c3919acce56
Model: yunmi.kettle.v12
Region: ru

Отправлено с iPhone

**Comment by KuznecKA** [comment]
When I received tokens for Xiaomi devices, I received such data

Mi Smart Kettle Pro
IP: 80.76.110.187
MAC: A4:C1:38:82:3C:58
Token: 36f5205beab14c3919acce56
Model: yunmi.kettle.v12
Region: ru

Отправлено с iPhone

**Comment by merdok** [comment]
Is this a Wifi or Bluetooth device?

**Comment by KuznecKA** [comment]
Bluetooth 

Отправлено с iPhone

**Comment by merdok** [comment]
Oh, sorry! Bluetooth devices are not supported by this plugin at this time...

**Comment by KuznecKA** [comment]
Thank you, sorry to bother you

Отправлено с iPhone
