### ISSUE TITLE
Mi Robot Vacuum-Mop 2 Pro (Need Support)

### ISSUE THREAD

**Issue by fung199609** [merdok/homebridge-miot#184]
**Device model**
ijai.vacuum.v3

**Device name**
Mi Robot Vacuum-Mop 2 Pro

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
How to create a feature button? How can I know the information of action params?

**Comment by merdok** [comment]
Will add support for the device in the next update! Action buttons parameters depend on the device you are using.

**Comment by fung199609** [comment]
how can I know the buttons parameters?

**Comment by merdok** [comment]
That is something I cannot tell you since I do not own the vacuum which you got. There will be a small guide for dreame based vacuums after the update and you can try to follow that.

**Comment by merdok** [comment]
Support is now added in version 1.0.0! A guide for room cleaning for dreame based vacuums can be found here: https://github.com/merdok/homebridge-miot/blob/main/docs/robotcleaner.md
