### ISSUE TITLE
Mode settings in English

### ISSUE THREAD

**Issue by benchristian88** [merdok/homebridge-miot#186]
Thank you for adding my new devices. Any chance that the clean:mode  18.6 values for the mode toggles could be in English on the following device

- dreame.vacuum.mb1808

**Comment by merdok** [comment]
The classes are now generated automatically based on the spec. You are right that some texts are in Chinese but that is how they are described in the spec (I myself also do not speak Chinese😅)

Anyway, you should be able to rename the switches by yourself in  the home app. Simply go on the mode switch settings and you can rename it there.
