### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by Stetocasa** [merdok/homebridge-miot#19]
Hi! Thanks for your job, your plugin is the unique one that works with Air Purifier 3C
I’d like to disable the “Screen” brightness from HomeKit, my interest is just to have the Air Purifier without screen control
Do you know how can I remove from HomeKit?

Second question,  any changes to let appear the temperature and humidity sensors?

This is my configuration:

    "accessories": [],
    "platforms": [
        {
            "platform": "miot",
            "devices": [
                {
                    "name": "Purificatore",
                    "ip": "192.168.178.xxx",
                    "token": "adxxxxxxxxxxb",
                    "deviceId": "3xxxxxxx",
                    "model": "zhimi.airpurifier.mb4",
                    "pollingInterval": 5,
                    "buzzerControl": false,
                    "childLockControl": false,
                    "ledControl": false,
                    "swingControl": false,
                    "moveControl": false,
                    "fanLevelControl": false,
                    "ioniserControl": false,
                    "dryControl": false,
                    "modeControl": false,
                    "lightModeControl": false,
                    "motorControl": false,
                    "pm25Breakpoints": [
                        5,
                        12,
                        35,
                        55
                    ]
                }
            ]
        }
    ]
}

**Comment by merdok** [comment]
As for screen, try to set the `screenControl` property to true, that should enable screen controls in HomeKit.

As for temperature and humidity, it looks like the air purifier does not support that so it will not show up. At least it seems not to be reported by purifier over the specs.

**Comment by Stetocasa** [comment]
> As for screen, try to set the `screenControl` property to true, that should enable screen controls in HomeKit.
> 
> As for temperature and humidity, it looks like the air purifier does not support that so it will not show up. At least it seems not to be reported by purifier over the specs.


    "accessories": [],
    "platforms": [
        {
            "platform": "miot",
            "devices": [
                {
                    "name": "Purificatore",
                    "ip": "192.168.178.148",
                    "token": "adfb4337ce7861580eaa8573847f77fb",
                    "deviceId": "359581494",
                    "model": "zhimi.airpurifier.mb4",
                    "pollingInterval": 5,
                    "buzzerControl": false,
                    "childLockControl": false,
                    "ledControl": false,
                    "swingControl":  #false,'
                    "ScreenControl": true,
                    "moveControl": false,
                    "fanLevelControl": false,
                    "ioniserControl": false,
                    "dryControl": false,
                    "modeControl": false,
                    "lightModeControl": false,
                    "motorControl": false,
                    "pm25Breakpoints": [
                        5,
                        12,
                        35,
                        55
                    ]
                }
            ]
        }
    ]
}

Done. But the tile persist in HomeKit (my goal is to remove it)

**Comment by merdok** [comment]
If you want to remove it then you have to set `screenControl` to false, please note that it needs to be written with a small s at the beginning.

**Comment by flareman** [comment]
If I can butt in, I had some such issues while developing a homebridge plugin of my own; when an accessory is cached, it retains services it registered between restarts of the server, even if the service itself is removed. The plugin should remove these services when they are not needed anymore. Likewise, when I started using this plugin, I initially used the screen switches but they were cluttering HomeKit and so I disabled the switch in config.json, and the switches persisted (while doing nothing, ofc).

As a stopgap solution, you can remove the entire accessory from homebridge cache (menu->homebridge settings->remove a single accessory from cache and remove just your device). The plugin will rediscover it from scratch and then the extra switches will be gone. Only caveat is the device will be set up as new in HomeKit and you'll have to set your automations again.
