### ISSUE TITLE
deerma.humidifier.jsq4 mode control service

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#190]
**Describe the bug**
deerma.humidifier.jsq4  mode control service：When I disable the mode control service, the mode switch still exists

**Expected behavior**
When I disable the mode control service, the mode switch should disappear, the fan level can adjust the humidifier mode, and the mode control service of the air purifier is normal

**Your config.json**
{
                    "name": "纯净式加湿器",
                    "ip": "192.168.31.254",
                    "token": "d9dacd3f8e9c7d3a5216fb79aec2d3cf",
                    "deviceId": "338228296",
                    "model": "deerma.humidifier.jsq4",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "fanLevelControl": true
                }

**Debug log**
no log

**Screenshots**
![image](https://user-images.githubusercontent.com/37586254/152105134-5fd22fe2-1cf5-4e4f-a531-0179b38fc5aa.png)

**Comment by merdok** [comment]
Based on the spec, your device does not support modes, so the switch will not do anything in your case. I also do not see modes on the screenshoot. What switches do you want hide?

**Comment by louliangsheng** [comment]
Fan level mode.

Marcin ***@***.***>于2022年2月2日 周三16:21写道：

**Comment by merdok** [comment]
Just set the fanLevelControl property to false and they should disappear.
