### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#192]
**Describe the idea or improvement**
Would like to provide options for renaming and disabling some properties such as temperature and humidity.

**Comment by merdok** [comment]
I think this should be possible within the accessory to rename those. Simply go on the accessory group in the home app where you will find a list of services and there open the settings of either humidity or temperature which can be renamed there. Or do I understand it wrong?

**Comment by louliangsheng** [comment]
If you rename in homebridge, you can synchronize to homekit; if you rename
only in homekit, if you edit homebridge, you may lose rename information.

Marcin ***@***.***>于2022年2月2日 周三15:50写道：

**Comment by merdok** [comment]
Yeah, but how often do you want to rename your accessories? You just do it one single time and afterwards never again, right?
Simply renaming it in the home app  should do the job.
It might be that I somehow do not understand the issue here...

**Comment by louliangsheng** [comment]
When I restart homebridge, HomeKit's renaming doesn't work, like re-adding

Marcin ***@***.***>于2022年2月2日 周三16:17写道：

**Comment by merdok** [comment]
The renaming should also work after restart, might be that something is clearing your cache between restarts?
