### ISSUE TITLE
Some UI text is duplicated in v1.0.0

### ISSUE THREAD

**Issue by Olepir** [merdok/homebridge-miot#194]
Some UI text is duplicated in v1.0.0

<img width="452" alt="Screenshot 2022-02-02 at 11 58 09" src="https://user-images.githubusercontent.com/48185958/152149541-2feeda61-fca6-4ebb-bdc6-c61d2d3af3d5.png">

**Comment by merdok** [comment]
This is somehow a visual bug in the homebridge ui. Standard json Schemas do not show it like that, not sure what is causing is but I will keep my eye on it and try to fix it!
