### ISSUE TITLE
Problem with other plugins

### ISSUE THREAD

**Issue by abaozang** [merdok/homebridge-miot#199]
After installed the miot plugin, I was not able to use Yeelighter or hue devices within HomeKit anymore. After deactivating miot they worked fine.. please verify. Thanks.

**Comment by merdok** [comment]
Did not notice any issues with other plugins. You can post some homebridge debug log so i can have look to check if there is anything unusual in your logs.

**Comment by Aekung** [comment]
Just want to confirm that I am using both Yeelighter and Hue plugin along with this plugin without any problem.
