### ISSUE TITLE
Add humidity mode

### ISSUE THREAD

**Issue by yoonpooh** [merdok/homebridge-miot#201]
![IMG_0D7FDEF0D123-1](https://user-images.githubusercontent.com/13917662/152528386-3001150f-0660-4dd9-adb4-fecb946a38a1.jpeg)

Currently my humidifier has a humidity mode.
It seems that this function does not exist in the corresponding plug-in, and it seems that there is only an On/Off function.

Could you please add that feature?

thank you.

![IMG_87405703274B-1](https://user-images.githubusercontent.com/13917662/152528538-ae94c776-5bf5-46c1-82e0-c2773a8b787c.jpeg)
(Other plugins look like this.)

**Comment by yoonpooh** [comment]
I want to integrate it into one miot plugin.

**Comment by merdok** [comment]
Hi, 
which humidifier do you have?

**Comment by yoonpooh** [comment]
@merdok `deerma.humidifier.jsq`

**Comment by merdok** [comment]
The humidifier has no mode in the miot spec so unfortunately it cannot be controlled:

https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Ahumidifier%3A0000A00E%3Adeerma-jsq%3A1

**Comment by yoonpooh** [comment]
If you register as `deerma.humidifier.jsq1` in other plugins, the corresponding function is created. Is it possible to apply it to work even if the model name is different?

**Comment by yoonpooh** [comment]
Other plugins work fine.

**Comment by yoonpooh** [comment]
<img width="658" alt="스크린샷 2022-02-04 21 51 54" src="https://user-images.githubusercontent.com/13917662/152532196-de384d89-4452-4546-a7ca-a3c2ff35fc20.png">

**Comment by yoonpooh** [comment]
```if (true) {
      this.humidifierService
        .getCharacteristic(Characteristic.RelativeHumidityHumidifierThreshold)
        .onGet(this.getRelativeHumidityHumidifierThreshold.bind(this))
        .onSet(this.setRelativeHumidityHumidifierThreshold.bind(this));
    }```

`homebridge-miot/lib/humidifier/HumidifierAccessory.js`
When I changed the 77th conditional statement to true, it worked normally.

**Comment by merdok** [comment]
The other plugin does not use the new miot protocol. It used the old miio protocol. Since your device is an older miio device it needs to emulate the miot protocol, for that case some features might not be exposed. This is something which is not under my control. I can only offer features which are available in the miot protocol in this plugin.

**Comment by yoonpooh** [comment]
@merdok ok, thanks! I will use it as above.

**Comment by yoonpooh** [comment]
It's not working. I'm sorry. I'll wait.

**Comment by merdok** [comment]
You have to remove the model which you entered before and I will adjust the device in the next update to mark it as micloud required!

**Comment by merdok** [comment]
The device is now marked as micloud required in version 1.0.3
