### ISSUE TITLE
Country Code :

### ISSUE THREAD

**Issue by Stewart06** [merdok/homebridge-miot#203]
Bonjour,

Pour des serveurs Europe ou France il faut choisir lequel en option ?

Hello,

 For Europe or France servers, which one must be chosen as an option?

**Comment by merdok** [comment]
That depends on what server you have your devices on. If you do not know, then you can check that in the homebridge ui, use the "Discover" button on the plugin preferences and it will show you on what server your devices are located.

**Comment by Stewart06** [comment]
J’ai configuré mes ventilateur et autre sur les serveur européen.

**Comment by Stewart06** [comment]
I configured my fans and others on the European servers.

**Comment by merdok** [comment]
I suppose the European servers are "de"

**Comment by Stewart06** [comment]
Je vous remercie.

J’ai remarqué un comportement anormal du plugin pour mes ventilateur.

Je m’explique, si mon ventilateur est éteins et que j’active la veille celle-ci s’active et se désactive de suite. Sauf que, quand j’active ensuite le ventilateur la veille se réactive de nouveau. Cela est désagréable car j’ai une règle qui active la veille du ventilateur de mon fils pour l’été et sauf que quand la journée il activé le ventilateur et bien il s’éteint tout seul car la minuterie est resté en mémoire. Il faudrait quelle soit restable.

Thank you.

 I noticed an abnormal behavior of the plugin for my fans.

 Let me explain, if my fan is off and I activate the day before, it activates and deactivates immediately.  Except that when I then turn on the fan the standby comes back on again.  This is unpleasant because I have a rule that activates the standby of my son's fan for the summer and except that when the day he activates the fan and well it turns off on its own because the timer has remained in memory.  It should be stable.

**Comment by merdok** [comment]
Can you share what fan model are you using? I guess since you asked about micloud then you are using a micloud based fan. Unfortunately this might happen, depending on what moment you turn on the switch, this is due to the fact that the MiCloud has a slight delay which causes this. There is nothin really what can be done about it...

**Comment by merdok** [comment]
Since you already opened a new issue, I will be slowing this.
