### ISSUE TITLE
zhimi.fan.za4 not working

### ISSUE THREAD

**Issue by andiweli** [merdok/homebridge-miot#205]
**Describe the bug**
zhimi.fan.za4 not working

**Expected behavior**
I got two dmaker.fan.p18 and one zhimi.fan.za4. The two p18 are working, the za4 (S2) not.
All 3 are configured the same way.

**Your config.json**
<details><summary>CLICK ME</summary>
<p>
{</br>
    "micloud": {</br>
        "username": "my mail address",</br>
        "password": "my password",</br>
        "country": "de",</br>
        "timeout": 5000</br>
    },</br>
    "devices": [</br>
        {</br>
            "name": "Lüfter Büro Xiaomi Fan 2",</br>
            "pollingInterval": 10,</br>
            "deepDebugLog": false,</br>
            "micloud": {},</br>
            "buzzerControl": true,</br>
            "ledControl": true,</br>
            "childLockControl": true,</br>
            "modeControl": true,</br>
            "showTemperature": false,</br>
            "ip": "10.1.0.195",</br>
            "token": "my token",</br>
            "deviceId": "dmaker.fan.p18",</br>
            "model": "dmaker.fan.p18",</br>
            "ventilationControl": true,</br>
            "fanLevelControl": true,</br>
            "actionButtons": true,</br>
            "moveControl": true,</br>
            "swingControl": true</br>
        },</br>
        {</br>
            "name": "Lüfter Schlafzimmer Xiaomi Fan 2S",</br>
            "pollingInterval": 10,</br>
            "deepDebugLog": false,</br>
            "micloud": {},</br>
            "buzzerControl": true,</br>
            "ledControl": true,</br>
            "childLockControl": true,</br>
            "modeControl": true,</br>
            "showTemperature": false,</br>
            "ip": "10.1.0.196",</br>
            "token": "my token",</br>
            "deviceId": "zhimi.fan.za4",</br>
            "model": "zhimi.fan.za4",</br>
            "ventilationControl": true,</br>
            "fanLevelControl": true,</br>
            "actionButtons": true,</br>
            "moveControl": true,</br>
            "swingControl": true</br>
        },</br>
        {</br>
            "name": "Lüfter Lukas Xiaomi Fan 2",</br>
            "pollingInterval": 10,</br>
            "deepDebugLog": false,</br>
            "micloud": {},</br>
            "buzzerControl": true,</br>
            "ledControl": true,</br>
            "childLockControl": true,</br>
            "modeControl": true,</br>
            "showTemperature": false,</br>
            "ip": "10.1.0.197",</br>
            "token": "my token",</br>
            "deviceId": "dmaker.fan.p18",</br>
            "model": "dmaker.fan.p18",</br>
            "ventilationControl": true,</br>
            "fanLevelControl": true,</br>
            "actionButtons": true,</br>
            "moveControl": true,</br>
            "swingControl": true</br>
        }</br>
    ],</br>
    "platform": "miot"</br>
}
</p>
</details>

**Debug log**
<details><summary>CLICK ME</summary>

ham.0 | 2022-02-07 13:26:22.223 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Brightness" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
ham.0 | 2022-02-07 13:26:22.221 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.215 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Supported-Characteristic-Value-Transition-Configuration" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.214 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Saturation" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.213 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.212 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Hue" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.210 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Color-Temperature" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.209 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Characteristic-Value-Transition-Control" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.208 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Characteristic-Value-Active-Transition-Count" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.206 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Brightness" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:22.205 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.555 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Product-Data" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.554 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Software-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.553 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Hardware-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.552 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Configured-Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.550 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.App-Matching-Identifier" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.549 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Accessory-Flags" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.548 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Firmware-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.546 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Serial-Number" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.545 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.544 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Model" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.542 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Accessory-Information.Manufacturer" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.541 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Loop-Gear.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.540 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Loop-Gear.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.538 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Loop-Gear.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.537 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Toggle-Mode.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.536 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Toggle-Mode.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.534 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Toggle-Mode.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.533 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Toggle.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.531 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Toggle.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.530 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Toggle.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.529 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Mode---Natural-Wind.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.527 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Mode---Natural-Wind.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.526 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Mode---Natural-Wind.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.525 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Mode---Straight-Wind.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.523 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Mode---Straight-Wind.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.522 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Mode---Straight-Wind.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.521 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Led.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.519 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Led.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.518 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Led.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.517 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Buzzer.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.515 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Buzzer.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.514 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Buzzer.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.513 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Horizontal-Swing.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.511 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Horizontal-Swing.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.510 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Horizontal-Swing.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.509 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Move-right.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.507 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Move-right.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.506 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Move-right.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.505 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Move-left.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.503 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Move-left.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.502 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Move-left.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.501 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level4.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.499 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level4.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.498 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level4.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.496 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level3.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.495 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level3.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.494 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level3.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.492 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level2.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.491 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level2.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.490 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level2.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.488 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level1.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.487 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level1.On" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.485 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Fan-Level---Level1.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.484 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Swing-Mode" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.482 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Rotation-Speed" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.481 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Rotation-Direction" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.479 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.478 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lock-Physical-Controls" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.476 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Target-Fan-State" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.475 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Current-Fan-State" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.473 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Rotation-Direction" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.472 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Swing-Mode" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.470 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Rotation-Speed" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.469 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lock-Physical-Controls" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.467 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Current-Fan-State" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.465 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Active" has no existing object, this might lead to an error in future versions
ham.0 | 2022-02-07 13:26:16.460 | warn | State "ham.0.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Lüfter-Schlafzimmer-Xiaomi-Fan-2S.Name" has no existing object, this might lead to an error in future versions
host.RasPi-ioBroker | 2022-02-07 13:26:03.554 | info | instance system.adapter.ham.0 started with pid 29480

</details>

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Comment by merdok** [comment]
The za4 fan is certainly working fine(I have one myself), but I see that you are not using homebridge directly but some kind of adapter for iobroker. I suspect that this might be the issue. Also the log which you posted comes from iobroker which unfortunately does not help me...
I also noticed that the deviceId you entered is incorrect, you should not specify that property if you do now know it, the plugin will fetch the deviceId automatically from the device when connected for the first time.

**Comment by andiweli** [comment]
I deleted the deviceIDs now, but no success.
The za4 is identical configured as the p18's... I have no idea what's wrong.
Even the objects generated by ioBroker stay empty when switching On/Off in the Xiaomi app.
The p18-objects change between 1/0 and true/false.

**Comment by merdok** [comment]
Sorry I cannot help you with iobroker related stuff, since I am not using it and I am not familiar with it. 
I am sure that the homebridge adapter must have its own repository where you should open an issue there.

I can assure you that the fan is working fine with this plugin in homebridge.
