### ISSUE TITLE
Xiaomi Air Purifier 3C - Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by yielfa** [merdok/homebridge-miot#206]
The Mi Air Purifier 3C devices are accesible via the Mi Home app, but fails with Homebridge after reinstallation with new IP-addresses and tokens. Other plugins and devices, [Webos Tv](https://github.com/merdok/homebridge-webos-tv) and [Dyson Pure Cool](https://github.com/lukasroegner/homebridge-dyson-pure-cool), still work.

```
{
    "name": "Mi Air Purifier 3C1",
    "ip": "10.0.20.10",
    "token": "-",
    "deviceId": "-",
    "model": "zhimi.airpurifier.mb4",
    ...
}
```

```
[2/7/2022, 3:07:40 PM] [miot] [Mi Air Purifier 3C1] Error: Could not connect to device, handshake timeout
[2/7/2022, 3:07:40 PM] [miot] [Mi Air Purifier 3C1] Could not connect to the device! Retrying in 40 seconds!
```

**Comment by merdok** [comment]
Handshake timeout means either the token is wrong or the device cannot be reached at the specified IP address. Make sure those are correct and also make sure that the device is reachable under the specified ip in your network.

**Comment by yielfa** [comment]
The devices respond to ping, nmap reveals nothing. The devices and tokens were discovered via the plugin itself.

**Comment by merdok** [comment]
If you are certain about ip and token then I would recommend that you investigate if everything is correct with your local network.

**Comment by yielfa** [comment]
Yes, there are VLANs involved and a separate IoT network with an LG TV and Dyson air purifier amongst other things; they are reachable though.

How can connectivity be tested outside of Homebridge? The port 54321 should be open, right?

**Comment by merdok** [comment]
Yes, that port should be open and reachable on the device network from. Keep in mind that everything applies here to the homebridge machine <-> device communication.

**Comment by yielfa** [comment]
Here are some tests from the homebridge machine:

```
$ telnet 10.0.20.10 54321
Trying 10.0.20.10...
telnet: Unable to connect to remote host: Connection refused
```
```
$ nmap -p- 10.0.20.10
Starting Nmap 7.80 ( https://nmap.org ) at 2022-02-07 21:22 CET
Nmap scan report for zhimi-airpurifier-mb4_mibtDBA9.lan (10.0.20.10)
Host is up (0.025s latency).
All 65535 scanned ports on zhimi-airpurifier-mb4_mibtDBA9.lan (10.0.20.10) are closed

Nmap done: 1 IP address (1 host up) scanned in 992.53 seconds
```

```
$ nmap 10.0.20.20
Starting Nmap 7.80 ( https://nmap.org ) at 2022-02-07 21:15 CET
Nmap scan report for LGwebOSTV.lan (10.0.20.20)
Host is up (0.0085s latency).
Not shown: 993 closed ports
PORT      STATE SERVICE
1074/tcp  open  warmspotMgmt
1088/tcp  open  cplscrambler-al
1247/tcp  open  visionpyramid
3000/tcp  open  ppp
3001/tcp  open  nessus
7000/tcp  open  afs3-fileserver
11111/tcp open  vce

Nmap done: 1 IP address (1 host up) scanned in 0.21 seconds
```

```
$ nmap 10.0.20.30
Starting Nmap 7.80 ( https://nmap.org ) at 2022-02-07 22:28 CET
Nmap scan report for OD11-********.lan (10.0.20.30)
Host is up (0.029s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
80/tcp   open  http
8081/tcp open  blackice-icecap

Nmap done: 1 IP address (1 host up) scanned in 0.51 seconds
```

**Comment by merdok** [comment]
You can try to reset your device and see if that helps, but this still looks for me more like a network issue.

**Comment by yielfa** [comment]
Already tried with multiple resets. It could be a network issue which could be sorted out with a dedicated access point for the Mi devices, although, one of them briefly responded to the scan now, revealing open ports:

```
$nmap 10.0.20.11
Starting Nmap 7.80 ( https://nmap.org ) at 2022-02-07 23:06 CET
Nmap scan report for zhimi-airpurifier-mb4_********.lan (10.0.20.11)
Host is up (0.028s latency).
Not shown: 996 closed ports
PORT     STATE    SERVICE
3006/tcp filtered deslogind
3031/tcp filtered eppc
5269/tcp filtered xmpp-server
8652/tcp filtered unknown
```

Is there a known profile / behavior of these devices?

**Comment by merdok** [comment]
Not sure if there is any know profile or behavior of the devices in the network.
You could also try to connect to the device using the MiCloud if you do not want to change your network. For that you need to specify the micloud credentials in the config.json and set the MiCloud flag forceMiCloud to true in the device config. The device needs to have access to the internet within its network.
Please note that this might introduce a small delay when controlling the device since the route will obviously be longer now...

**Comment by yielfa** [comment]
Yes, it turned out to be a network problem; Homebridge can communicate with the Mi devices when on the same subnet. Why the other devices worked while the Mi devices did not, is still not clear to me.
