### ISSUE TITLE
Split Purifier from Air sensor in HK

### ISSUE THREAD

**Issue by Stetocasa** [merdok/homebridge-miot#21]
HI, are there any possibility to expose the Purifier and the Air sensor as two different accessories and not grouped?
My request made because if I want to switch from Automatic to Manual mode without use the switch plugin, I can do trough the Purifier accessory but to do that I need to enter inside the tile group
![21BD69CC-A234-4FF0-8626-98A9F306A46C](https://user-images.githubusercontent.com/70729310/116704969-51755a80-a9cc-11eb-8e75-5d13b0f1b034.jpeg)
![A5F5782C-2A2C-4007-A723-64E52BA922A7](https://user-images.githubusercontent.com/70729310/116704977-533f1e00-a9cc-11eb-84f6-ed5d2de314c3.jpeg)
![91088830-DD64-4823-9D41-9D523C050F4B](https://user-images.githubusercontent.com/70729310/116705129-82558f80-a9cc-11eb-8d69-6595dcf13741.jpeg)

**Comment by Stetocasa** [comment]
Attaching a video to better explain all steps to go the integrated switch mode (without using the additional switch that the plugin can create)

https://user-images.githubusercontent.com/70729310/116706377-ddd44d00-a9cd-11eb-8ace-424f40c8ebd8.mov

**Comment by Stetocasa** [comment]
@merdok

**Comment by merdok** [comment]
Yes, you can. Just scroll down on the group to the bottom and there should be a button "Split into separate tiles", just use that!

![image](https://user-images.githubusercontent.com/730197/116710385-fd6d7480-a9d1-11eb-82e3-6f420e83ba22.jpeg)

**Comment by Stetocasa** [comment]
This is possible just if you include more accessories from config.
I tested, if the Screen monitor is exposed, you can ungroup as you said, but I the screen monitor was not included, the ungroup function is not visible.

**Comment by merdok** [comment]
This is unfortunately like the Home app behaves. I would recommend then to add the screen control and then ungroup it. You can always hide the screen control in a room which you do not use that often.

**Comment by jipvankuijk** [comment]
This is possible @merdok because I also have a HomeBridge plugin for Dyson air purifiers and there they are split.

https://github.com/lukasroegner/homebridge-dyson-pure-cool#readme

Maybe you can take a look just to take up some inspiration?

**Comment by Stetocasa** [comment]
Thanks @jipvankuijk !!!!
@merdok now I solved adding the Screen switch, but definitely if you can do as Dyson plug-in will be fantastic

**Comment by merdok** [comment]
@jipvankuijk the plugin does not group related services together under one accessory, instead a new accessory is created for each service (this is the way plugins did work before apple introduced the grouping).  This is not wrong and this will work but will create a mess in your home app since related services are not grouped together.

Apple provides a fantastic way of grouping related services together and this should be used, especially because it also allows to split them up in separate accessories if needed.
