### ISSUE TITLE
yeelink.light.colorc

### ISSUE THREAD

**Issue by naumserg74** [merdok/homebridge-miot#211]
**Device model**
The unique model of your device : yeelink.light.colorc

**Device name**
The friendly name of the device used by the manufacturer: RGB LED Bulb

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
It works, but only in switch mode

**Comment by merdok** [comment]
Will add support in the next update!

**Comment by merdok** [comment]
The device is now added in version 1.0.4!

**Comment by naumserg74** [comment]
Thank you very march. It really works now
