### ISSUE TITLE
Yeelight Lightstreep 1S

### ISSUE THREAD

**Issue by AndyLoginov** [merdok/homebridge-miot#212]
**Device model**
Yeelight Lightstrip 1S

**Device name**
yeellink.light.strip6

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
Every time disconneted from Homekit

**Comment by merdok** [comment]
Will add it in the next update!

**Comment by merdok** [comment]
Ufff i just see that `yeellink.light.strip6` is already supported https://github.com/merdok/homebridge-miot/blob/main/supported_devices.md#light

**Comment by AndyLoginov** [comment]
But its the same stripe?
Yeelight Lightstrip Plus VS Yeelight Lightstrip 1S?

**Comment by merdok** [comment]
I mean there is just one device with the `yeelink.light.strip6` model so it is certainly the same. Might be that the name is incorrect or that it requires micloud. If so then i can correct that.

**Comment by Olepir** [comment]
I think right model for this strip is `yeelink.light.strip2` – I found this info on Yeelight forum

Is there a way to confirm this somehow?

**Comment by merdok** [comment]
I mean if you have the device already then you can either add it to the plugin already without specific the model and the plugin will detect it automatically and show you the model in the log during initialization. Or you can use homebridge ui and go to the plugin settings and use the "Discover" button there which will get you all your devices in your MiCloud with the models.

**Comment by AndyLoginov** [comment]
> I think the right model for this strip is `yeelink.light.strip2` – I found this info on Yeelight forum
> 
> 
> 
> Is there a way to confirm this somehow? 

I checked.  This didn't work either 🤔

**Comment by AndyLoginov** [comment]
![image](https://user-images.githubusercontent.com/98414170/153334887-d04d0807-c842-42c9-89da-2e1764eb11db.jpeg)

Why is he pulling incomprehensible data from the Mi Cloud?
 My ip is different.  10…..
 And region Cn

**Comment by merdok** [comment]
This is what is stored in the MiCloud...

But I see that you indeed have the strip6 device which is supported. Does the device work for you?

**Comment by AndyLoginov** [comment]
> This is what is stored in the MiCloud...
> 
> But I see that you indeed have the strip6 device which is supported. Does the device work for you?

Don't work 😢

**Comment by merdok** [comment]
Then what does the homebridge log say?

**Comment by AndyLoginov** [comment]
> Then what does the homebridge log say?

I can check it in evening...
But you know- that working with Yeelighter plugin 
🤔

**Comment by merdok** [comment]
Sure you can check and let me know later.

**Comment by merdok** [comment]
As of version 1.0.4 the device is now marked as micloud required

**Comment by AndyLoginov** [comment]
👍🏻

**Comment by AndyLoginov** [comment]
> As of version 1.0.4 the device is now marked as micloud required

Tnx. I'll check
