### ISSUE TITLE
Fan speed level set between 1-100

### ISSUE THREAD

**Issue by BuSHari** [merdok/homebridge-miot#213]
I have 2 fans models that has the option to choose fan speed between 1-100 and also jump between fan levels 1-4.
In your previous [plugin](https://github.com/merdok/homebridge-xiaomi-fan#readme) its working great.
I have these fans:
`zhimi.fan.za4`
`dmaker.fan.p15`

When i try to set the speed level with the slider it jumps 25 steps (probably it jumps between fan levels 1-4)
When i set it from the Mi up to a speed of 18 for example the plugin sees it as 25, it think its working by levels and not the real speed.
0-25 = 25 (1)
26-50 = 50 (2)
51-75 = 75 (3)
76-100 = 100 (4)

I think most of the smart fans are working with the 1-100 speed levels
I saw that you resolved that [issue](https://github.com/merdok/homebridge-miot/issues/1) but i don't know if its related.

Thanks in advanced

**Comment by merdok** [comment]
Both of those fans do not support stepless fan speed over the miot protocol. This is something which is not under my control and I cannot change it.

The xiaomi-fan plugin is not using the miot protocol but the old miio protocol which can do that!
