### ISSUE TITLE
Device model: philips.light.ceiling. 

### ISSUE THREAD

**Issue by naumserg74** [merdok/homebridge-miot#216]
Why is only MiCloud connection used instead of local connection? It is very slow and does not work without internet connection. Here is plugin with a local connection and very fast response from the device:
https://github.com/CorsairCat/homebridge-mi-philips-light

**Comment by merdok** [comment]
Not sure how many times I should explain this😅 
This plugin is for devices which support the miot protocol! Your device is an older device which does not support the miot protocol but instead uses the miio protocol. For convenience xiaomi offers miot protocol emulation for older device but that only works over the MiCloud! This is something I cannot change, so if you are using older devices with this plugin you will have a slight delay, depending on what server you have your devices.

**Comment by naumserg74** [comment]
Thank you for your comment. Now I know a lot more about my celling light
