### ISSUE TITLE
Please add “isleep.blanket.hs2205”

### ISSUE THREAD

**Issue by Ukenn2112** [merdok/homebridge-miot#217]
**Device model**
[isleep.blanket.hs2205](https://home.miot-spec.com/spec/isleep.blanket.hs2205)

**Device name**
Painted sleep water heating pad HS2205

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
It works, but there is only one switch

**Comment by merdok** [comment]
Should be possible. Will add it as a heater device in the next update!

**Comment by merdok** [comment]
The device is now added in version 1.0.4!
