### ISSUE TITLE
Excellent plugin!

### ISSUE THREAD

**Issue by avielc** [merdok/homebridge-miot#220]
This "Issue" is just to say kudos on all your work buddy!
I spent last night about 5 hours in total on which the last 10 minutes were finding and using this plugin for the Xiaomi Mi Smart LED Essential (You added it to the support back in November) 
This made it work almost flawlessly (there's some delay when turning off\on the light compared to Aqara light,) but it's fantastic and setting it up was a breeze compared to all the troubles I had with tokens. 

so thank you! Feel free to close this one once you've read it :)

**Comment by merdok** [comment]
Thanks for the nice words! Glad that you like the plugin 👍 
Such issues i gladly close 😄
