### ISSUE TITLE
thermostat cubee.airrtc.th123e

### ISSUE THREAD

**Issue by dmitrylive** [merdok/homebridge-miot#221]
**Device model**
cubee.airrtc.th123e

**Device name**
smart thermostat mihome wifi

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
you have cubee.airrtc.th123w support. can add cubee.airrtc.th123e? the thermostat worked on/off, but stopped responding 2-3 weeks ago

**Comment by merdok** [comment]
Will add it in the next update!

**Comment by merdok** [comment]
Added in version 1.0.5
