### ISSUE TITLE
Xiaomi Mijia Bluetooth Temperature Humidity Sensor 2 

### ISSUE THREAD

**Issue by wmar** [merdok/homebridge-miot#223]
**Device model**
miaomiaoce.sensor_ht.t2

**Device name**
Xiaomi Mijia Bluetooth Temperature Humidity Sensor 2 

**Does the device require a MiCloud connection?**
Do not know
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_It should work with Humidifier or Air purifier

**Comment by merdok** [comment]
Bluetooth devices are not supported by this plugin!
