### ISSUE TITLE
Mi bluetooth Temperature and Humidity sensor

### ISSUE THREAD

**Issue by wmar** [merdok/homebridge-miot#224]
**Device model**
_cleargrass.sensor_ht.dk1

**Device name**
_Mi bluetooth Temperature and Humidity sensor

**Does the device require a MiCloud connection?**
Do not know_

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
Bluetooth devices are not supported by this plugin!
