### ISSUE TITLE
Xiaomi CRMCR Fingerprint Safe Deposit Box 

### ISSUE THREAD

**Issue by wmar** [merdok/homebridge-miot#225]
**Device model**
_lcrmcr.safe.ms30b

**Device name**
_Xiaomi CRMCR Fingerprint Safe Deposit Box 3D 

**Does the device require a MiCloud connection?**
Do not know_
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
Seems like a bluetooth device. Bluetooth devices are not supported by this plugin!
