### ISSUE TITLE
Door Loock CatY

### ISSUE THREAD

**Issue by wmar** [merdok/homebridge-miot#226]
**Device model**
_loock.cateye.v01

**Device name**
_Door Loock CatY

**Does the device require a MiCloud connection?**
_Yes
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
The devices only exposes motion detection and battery level, so there is nothing really to control here...
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:video-doorbell:0000A03A:loock-v01:1
