### ISSUE TITLE
Please add support device for Xiaomi Air Purifier 2S (Global Version) | zhimi.airpurifier.mc1

### ISSUE THREAD

**Issue by tapecom** [merdok/homebridge-miot#227]
**Device model**
zhimi.airpurifier.mc1

**Device name**
Xiaomi Air Purifier 2S (Global Version)

**Does the device require a MiCloud connection?**
Yes (I think it same as zhimi.airpurifier.ma2 and I need to config "forceMiCloud": true to make it work.)

**Anything special about the device?**
I have 2 model of Xiaomi Air Purifier 2S.
Xiaomi Air Purifier 2S (Global Version) | zhimi.airpurifier.mc1 and Xiaomi Air Purifier 2S (Chinese Version) | zhimi.airpurifier.ma2

The device look same and all function in Mi home app look same.
zhimi.airpurifier.mc1 already work with the plugin with a limited function (only on-off is working).

Please support for it.
Thank you.

**Comment by merdok** [comment]
Should be no problem! Will add support for it in the next update!

**Comment by merdok** [comment]
Added in version 1.0.5
