### ISSUE TITLE
Xiaomi Mi Computer Monitor Light Bar 1S

### ISSUE THREAD

**Issue by patriceckhart** [merdok/homebridge-miot#228]
I have the Xiaomi Mi Computer Monitor Light Bar 1S. This can be found in the supported device list. However, I can't register this monitor lightbar anywhere? how can i add this to the plugin? How do I find out IP and token?

**Comment by merdok** [comment]
If you have homebridge ui then you can simply use this feature to auto discover your devices:
![discover](https://user-images.githubusercontent.com/730197/154844132-3a7da17e-c99e-45dd-be08-ca8316acd517.png)

If not then you can use the built in command line utilities to get the info straight from the console. See here for command: https://github.com/merdok/homebridge-miot#token

**Comment by patriceckhart** [comment]
@merdok Thanks but there are no devices registered in my micloud account (https://i.mi.com/). How can I register the monitor light there?

**Comment by merdok** [comment]
You have to simply add it in the mi home app while you are logged into your account.

**Comment by patriceckhart** [comment]
@merdok Thank you. I tried it with a Xiaomi Monitor Lamp, shouldn't that be this one? Unfortunately the off on off ... 5 times in 7 seconds and 2 secondes 5 times doesn't work.

**Comment by merdok** [comment]
I mean you should not ask me what kind of device you have 😅 You would need to provide the unique device model, but from what i can understand is that your device requires a micloud connection, hence depending on the country you are and the server which you use there will be a slight delay.
