### ISSUE TITLE
Fan model missing - Mi Smart Fan 1X

### ISSUE THREAD

**Issue by vijayramadass** [merdok/homebridge-miot#23]
Hi will it be possible to add support for  Fan Mi Smart Fan 1X (dmaker.fan.p5).
Currently its is not supported and the configuration is not saved.

**Comment by merdok** [comment]
The dmaker.fan.p5 is not a miot device. It still uses the old miio protocol for local connectivity. 
You can actually use my other plugin homebridge-xiaomi-fan for that since i added support for that fan there.
