### ISSUE TITLE
Dreame Bot D9 Max

### ISSUE THREAD

**Issue by izumovn** [merdok/homebridge-miot#231]
**Device model**
dreame.vacuum.p2259
_The unique model of your device, e.g zhimi.fan.za5._

**Device name**
Dreame Bot D9 Max
_The friendly name of the device used by the manufacturer, e.g. Smartmi Standing Fan 3._

**Does the device require a MiCloud connection?**
Yes
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
Will add support in the next update!

**Comment by phipsey** [comment]
Please also add the Dreame D9 Pro. At the moment it can be added, but in HomeKit it is marked as „unsupported Device“ and has no function at all. Thank you!

**Comment by merdok** [comment]
@phipsey please create a separate issue for that!

**Comment by merdok** [comment]
The device is now added in version 1.0.6
