### ISSUE TITLE
Please add viomi.hood.a10

### ISSUE THREAD

**Issue by chung0002000** [merdok/homebridge-miot#232]
**Device model**
 viomi.hood.a10 

**Device name**
Viomi Hood Free 3

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
Please also add the light if possible.

**Comment by merdok** [comment]
Hello,

this device does not fit any category but you can actually get it easily to work with `propertyControl`, here is how it should look like:

```
          "customAccessory": true,
          "propertyControl": [
            {
              "action": "2.1",
              "name": "Power"
            },
            {
              "property": "2.2",
              "name": "Fan level"
            },
            {
              "property": "3.1",
              "name": "Light"
            }
          ]
```

**Comment by chung0002000** [comment]
Thanks for your reply.
It's work, but can make the Fan level in one switch?

**Comment by merdok** [comment]
The fan has 3 options, so you need at least 3 switches to control all fan modes. Do you need only two?

**Comment by chung0002000** [comment]
Sorry for your confusion. 
I mean is it possible to make a slider switch?

**Comment by merdok** [comment]
Unfortunately not possible currently for custom accessories.

**Comment by chung0002000** [comment]
Got it.
Thanks for you support.
