### ISSUE TITLE
ip and country of device in discover

### ISSUE THREAD

**Issue by bisquit2003** [merdok/homebridge-miot#233]
hello
some devices are displayed with an ip and a country that differ from the real ones. 
for example: 
rockrobo.vacuum.v1 ip 192.168.1.65 country tw, but real static ip 192.168.1.131 country cn
chuangmi.plug.hmi206  192.168.1.61 country tw, real static ip 192.168.1.115 country cn

the token is correct everywhere
do I need to reconnect my devices to mi home?

**Comment by merdok** [comment]
Yes, when the ip and country do not match that means that you have not up to date info. You should reset your device and reconnect it with the cloud.
