### ISSUE TITLE
Compatibility for Node v14.x.x

### ISSUE THREAD

**Issue by deflao** [merdok/homebridge-miot#235]
**Describe the idea or improvement**
Hi, I'm using other plugins that are required Node v14.x.x
Therefore, if I updated my node to v16.x.x those plugins won't work.
Specifically, the plugin that requires v14.x.x is 'Homebridge Switchmate Ble' (https://github.com/AMoo-Miki/homebridge-switchmate-ble#readme)

**Describe the solution you'd like**
A solution would be adding support for node v14.x.x
For example, the Govee plugin and switchbot plugin support both v14.x.x and v16.x.x
https://github.com/OpenWonderLabs/homebridge-switchbot#readme
https://github.com/bwp91/homebridge-govee#readme

**Comment by merdok** [comment]
You should be able to use Node v14.x.x without any issues, the only thing is that a warning will popup in the homebridge debug log. 
Homebridge will drop Node.js v14.x.x support next year in April so plugins will have to be update anyway by that time.

**Comment by deflao** [comment]
Okay. Thank you for the information
