### ISSUE TITLE
Support for "qmi.powerstrip.v1"

### ISSUE THREAD

**Issue by uswong** [merdok/homebridge-miot#239]
Hello,

Thanks for this homebridge-miot.  My house is full of Xiami devices and this homebridge has brought so many of them into my homekit.

I have one more device "**qmi.powerstrip.v1**" which does not seem to be supported.  I did try to add it in the config and it created the tile in homekit but the polling timed out.

It would be much appreciated if this community can add support for this Xiaomi device "**qmi.powerstrip.v1**"

Best regards,
Ung Sing

**Comment by merdok** [comment]
That should not be a problem, but i need a little bit more info.
What is the official (marketing) name of the device?
Did you try to enter your MiCloud credentials and set the `forceMiCloud` flag to `true` and did it work then?

**Comment by uswong** [comment]
The model name of the power strip is "qmi powerstrip v1".

and yes, I have enter my MiCloud credentials, etc.  My config as follow for your reference:

The first one is for the device "qmi powerstrip v1" which does not work.  The second is for "zimi powerstrip v2" which works flawlessly.

        {
            "platform": "miot",
            "devices": [
                {
                    "name": "Master qmi Power Strip",
                    "ip": "192.168.0.24",
                    "token": "977bb4cae0b3a449e61a5d58142788ae",
                    "micloud": {
                        "username": "uswong@gmail.com",
                        "password": "xxxxxxxx",
                        "country": "cn"
                    },
                    "forceMiCloud": true
                },
                {
                    "name": "Games Zimi Power Strip",
                    "ip": "192.168.0.30",
                    "token": "746495d3cfbbd70094003168d5a04f3e",
                    "micloud": {
                        "username": "uswong@gmail.com",
                        "password": "xxxxxxxx",
                        "country": "cn"
                    },
                    "forceMiCloud": true
                }
            ]
        }

**Comment by merdok** [comment]
I think "qmi powerstrip v1" is just a model name. How is the official device called like on the box you bough it in?

The config is wrong. forceMiCloud needs to be included in the micloud object as follows:

```
    {
        "platform": "miot",
        "devices": [
            {
                "name": "Master qmi Power Strip",
                "ip": "192.168.0.24",
                "token": "977bb4cae0b3a449e61a5d58142788ae",
                "micloud": {
                    "username": "uswong@gmail.com",
                    "password": "xxxxxxxx",
                    "country": "cn",
                    "forceMiCloud": true
                }
            },
            {
                "name": "Games Zimi Power Strip",
                "ip": "192.168.0.30",
                "token": "746495d3cfbbd70094003168d5a04f3e",
                "micloud": {
                    "username": "uswong@gmail.com",
                    "password": "xxxxxxxx",
                    "country": "cn",
                    "forceMiCloud": true
                }
            }
        ]
    }
```

Please try that way.

**Comment by uswong** [comment]
Thanks, its all working now.  I have 3 of them, two of them has 3 USB ports.

![image](https://user-images.githubusercontent.com/96530237/158002191-85011acc-b083-4fe7-b96b-cc1ff0ee0f7c.png)


It turns up that the token was also not correct.  Apparent, when I deleted the device and re-added the device again, the token changed and have to retrieve the token from the server again.  


I do not have the box of the power strips anymore, I think it is called `Xiaomi Chingmi WiFi smart powerstrip` and the model name is `qmi.powerstrip.v1`.

Now you can confidently put this `qmi.powerstrip.v1` as one of your your supported devices.
