### ISSUE TITLE
cgllc.gateway.s1 (Xiaomi cleargrass Bluetooth gateway)

### ISSUE THREAD

**Issue by ddomino007** [merdok/homebridge-miot#241]
**Device model**
cgllc.gateway.s1

**Device name**
Xiaomi cleargrass Bluetooth gateway

**Does the device require a MiCloud connection?**
Do not know
Although it might, [this GitHub issue for HASS](https://github.com/al-one/hass-xiaomi-miot/issues/368) mentions HASS is pulling the sensor data via MiCloud if I understand correctly.

**Anything special about the device?**
It's a gateway, so it determines the individual accessories paired to it.
It's used for BLE devices, mostly BLE Termohygrometers
There's BLE Termohygrometer support in Homebridge, but it's a plugin that aims to directly connect to the sensors rather than interacting with the gateway.

**Comment by merdok** [comment]
The miot spec of the device reports nothing so i guess that will not be possible:
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:gateway:0000A019:cgllc-s1:1
