### ISSUE TITLE
lumi.gateway.mieu01 (Mi Control Hub)

### ISSUE THREAD

**Issue by ddomino007** [merdok/homebridge-miot#242]
**Device model**
lumi.gateway.mieu01

**Device name**
Mi Control Hub

**Does the device require a MiCloud connection?**
Do not know
Device definitely introduced before 2020.

**Anything special about the device?**
It's a gateway, so it determines the individual accessories paired to it.
It's used for Zigbee devices, mostly motion sensors (and running automations).
There's a plugin dedicated for this gateway, that's been long abandoned and doesn't work anymore - also the pairing instructions for that particular plugin don't match the current state of the Mi Home app.

**Comment by merdok** [comment]
This device at least reports some properties, but you can basically only set the alarm on that device:
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:gateway:0000A019:lumi-mieu01:1
