### ISSUE TITLE
Support removing "Screen" controls on `zhimi.airp.mb5`

### ISSUE THREAD

**Issue by MPThLee** [merdok/homebridge-miot#243]
**Describe the idea or improvement**
I just set up `zhimi.airp.mb5` device on homebridge, but somehow I can't remove "screen" brightness toggles.
If there's feature about removing screen brightness toggles in home bridge, it will be nice

**Describe the solution you'd like**
Add some configurable option for screen brightness

**Additional context**
`"ledControl": false` doesn't do anything.

**Comment by merdok** [comment]
Did you check the docs? https://github.com/merdok/homebridge-miot/blob/main/docs/airpurifier.md
There is a `screenControl` and i guess this is what you are looking for, right?

**Comment by MPThLee** [comment]
I noticed that so i just write that on config. Thanks.

![image](https://user-images.githubusercontent.com/26970092/158067325-3c87342d-621c-4865-95d1-b6ce3f91649a.png)
I think i just missed that config as gui config doesn't represent default value. (it should be checked. I think?)
