### ISSUE TITLE
outlet icon

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#244]
**Describe the bug**
After upgrading to the latest version of the plug-in, the multi-port socket is no longer displayed as a socket. I guess the reason is that the accessories of the socket show "swtich" instead of "outlet".
I am using v0.9.19 now, and it shows normal in homekit.
![QQ图片20220314190111](https://user-images.githubusercontent.com/37586254/158159374-f40a6f74-a4ca-4126-b996-4ab57c11b6a8.png)
![QQ图片20220314190116](https://user-images.githubusercontent.com/37586254/158159378-d50cb7ad-5354-4173-98b1-5193341e0c4d.png)

**Comment by louliangsheng** [comment]
Display of latest firmware in homekit. I guess the reason is that the accessories of the socket show "swtich" instead of "outlet".
![QQ图片20220314190352](https://user-images.githubusercontent.com/37586254/158159776-dc8b1cd6-e591-4313-852b-a99b89c825c6.png)
![QQ图片20220314190356](https://user-images.githubusercontent.com/37586254/158159799-73d89a05-8af2-4ed1-b3e7-fad7b86c02e7.png)

**Comment by louliangsheng** [comment]
cuco.plug.cp2a

Marcin ***@***.***>于2022年3月15日 周二00:27写道：

**Comment by merdok** [comment]
This device is supported and is an outlet device. Did you try to tap on the icon and try to change it?

**Comment by louliangsheng** [comment]
I guess the reason is that the accessories of the socket show "swtich" instead of "outlet". Switch cannot be changed to outlet in homekit.

**Comment by merdok** [comment]
Oh, you are right! The main accessory is still an outlet as before, but the additional sockets are now auto generated as switches instead of outlets! This might cause the issue!
Will have a look at it and try to provide a fix!

**Comment by merdok** [comment]
Should be fixed in version 1.1.0
