### ISSUE TITLE
Unable to use Siri turn on robot cleaner after update plugin

### ISSUE THREAD

**Issue by pewpew-ai** [merdok/homebridge-miot#246]
Hi the plugin was working perfectly in the last version. However, after I update the plugin, there are new additional actions available and I was unable to use Siri to turn on robot cleaner. 

I only got response saying that Siri couldn't find device in home app. I only use plugin to turn on and off robot cleaner. I try moving other actions to different room as I don't need them but everything just end up moving altogether including turn on and off option.  Any thought on this?

Below are my setting 
                {
                    "name": "Robot Cleaner",
                    "ip": "192.168.x.x",
                    "token": "xxxxxxx",
                    "actionButtons": false,
                    "propertyControl": false
                } 
![IMG_1362](https://user-images.githubusercontent.com/15328352/159513760-7fae3980-dab6-49a0-a8da-215da7d09463.jpg)

**Comment by pewpew-ai** [comment]
Just found out that I could disable other actions by adding "modeControl": false. Now all the option has disappeared.

However, I still couldn't use Siri to toggle the robot cleaner. It might be the sensor that causing this issue. Is there anyway I could disable the sensor? 

![IMG_1364](https://user-images.githubusercontent.com/15328352/159534671-96ecdab6-eff4-4e10-82c8-f8f700d582d1.PNG)

**Comment by merdok** [comment]
Please make sure that you tell Siri the exact name of the switch which you are trying to turn on/off. The sensor or other switches has absolutely nothing to do with your issue. You can also rename the switch and then tell Siri the name of you find it difficult to speak speak out the name.

**Comment by pewpew-ai** [comment]
Hi Marcin,

I’ve been calling the exact name of the switch and I even try changing the name and type of switch to fan but still doesn’t work.

I know it sounds bizarre and the new sensor shouldn’t effect Siri functionality but it’s the only thing that’s different from previous version which worked perfectly fine.

Anyway, thanks for your hard work 🙏🏻!

On 24 Mar 2022, at 12:50, Marcin ***@***.***> wrote:

﻿

Please make sure that you tell Siri the exact name of the switch which you are trying to turn on/off. The sensor or other switches has absolutely nothing to do with your issue. You can also rename the switch and then tell Siri the name of you find it difficult to speak speak out the name.

**Comment by merdok** [comment]
I have also the sensor and it does not affect Siri in any way. I can control my vacuum cleaner with Siri without any problems. Again, naming is here very important especially when you have your language other then English, in that it is recommended to use a name using your native language.

**Comment by pewpew-ai** [comment]
Oh I just found out that the vacuum cleaner and its sensor have the same name. Hence why Siri couldn't figure out which device I was referring to. I changed the sensor name and things are now back to normal! 

Thanks a lot. It's naming issue.
