### ISSUE TITLE
Please add support for Scene Curtain WIFI X (leshi.curtain.v0001)

### ISSUE THREAD

**Issue by avbaga** [merdok/homebridge-miot#25]
Please add support for Scene Curtain WIFI X (leshi.curtain.v0001)

**Comment by merdok** [comment]
Will add the device and let you know when it is ready!

**Comment by merdok** [comment]
The device should now be support in version 0.8.0. Please let me know if it works!

**Comment by avbaga** [comment]
Thank you! Now it is working !
