### ISSUE TITLE
Removing the temp sensor on Air purifier

### ISSUE THREAD

**Issue by Trippersgarage** [merdok/homebridge-miot#250]
Hi Merdok. 

Perhaps a dumb question with an obvious solution but is it possible to remove the temperature readout from a zhimi.airpurifier.mb3? Basically, I do not want the purifier to report the temp to homekit. 

Can't seem to figure out how to remove just the temp reading.

Thank you!

**Comment by merdok** [comment]
Currently is not possible. But why would you like to do that? I mean if a air purifier has an temperature sensor then it will be shown. On air purifiers with native homekit support it is also not possible to remove that as far as i know...

**Comment by Trippersgarage** [comment]
Ah ok. The reason I asked is because I've always found the temp sensor slightly off and have a new, more accurate sensor in the room. But it seems like HomeKit will use both sensors and reports a "range" temperature. If not possible, its fine, but yeah, that's the issue I'm seeing.

Thank you!
