### ISSUE TITLE
Issue with my devices 

### ISSUE THREAD

**Issue by Mata-hari11** [merdok/homebridge-miot#253]
Hi community, thanks for your script for your plugin which looks really great.

I am a novice with home automisation, I tried to follow the instructions in the « read me » but all my devices are detected « without response ».
I think the problem is a server, but I don’t see FR server. 

My config and screenshots of my log. 
thanks in advance

{
    "bridge": {
        "name": "Homebridge D038",
        "username": "….",
        "port": 51656,
        "pin": "…."
    },
    "accessories": [
        {
            "name": "Temperature & Humidity",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "Air Purifier",
            "address": "192.",
            "token": "8fce3aed85e8b63d9d24ce8e29ac0ea1",
            "enableAirQuality": true,
            "enableTemperature": true,
            "enableHumidity": true,
            "filterChangeThreshold": 5,
            "enableFanSpeedControl": true,
            "enableChildLockControl": true,
            "accessory": "XiaomiMiAirPurifier"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "micloud": {
                "username": "….@gmail.com",
                "password": "……",
                "country": "cn",
                "forceMiCloud": true,
                "timeout": 5000
            },
            "devices": [
                {
                    "name": "Purificateur home",
                    "ip": "10.49.0.100",
                    "token": "e06d1270f0f999c76535ff4bd446d39e",
                    "deviceId": "293318700",
                    "model": "zhimi.airpurifier.mb3",
                    "pollingInterval": 10,
                    "deepDebugLog": true,
                    "micloud": {
                        "username": "……",
                        "password": "….",
                        "country": "cn",
                        "forceMiCloud": true,
                        "timeout": 5000
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true,
                    "fanLevelControl": true,
                    "ioniserControl": true
                },
                {
                    "name": "Ampoule gauche",
                    "ip": "10.00.00000",
                    "token": "d439a55e102925304c45e9a2c8416465",
                    "deviceId": "312749455",
                    "model": "yeelink.light.color3",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                },
                {
                    "name": "Principal",
                    "ip": "10.000000,
                    "token": "3a5e5445b54ef0a01fd953e4ae2c4a93",
                    "deviceId": "312948451",
                    "model": "yeelink.light.color3",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                },
                {
                    "name": "Ampoule droite",
                    "ip": "10.000
                    "token": "370cc42e1bc3124f59e0c4c936ba8af6",
                    "deviceId": "313088322",
                    "model": "yeelink.light.color3",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                }
            ],
            "platform": "miot"
        }
    ],
    "disabledPlugins": [
        "homebridge-xiaomi-mi-air-purifier",
        "homebridge-mi-hygrothermograph"
    ]
}

<img width="1194" alt="Image PNG 8" src="https://user-images.githubusercontent.com/102914089/161438565-75af334b-d612-4790-bd89-43d1dbc62998.png">
<img width="1194" alt="Image PNG 9" src="https://user-images.githubusercontent.com/102914089/161438567-c9d43983-09a9-4dc9-998c-5fadc2dac301.png">

**Comment by merdok** [comment]
The config.json which you posted here has some issues, is this just a copy/paste mistake or might that be the issue?

**Comment by Mata-hari11** [comment]
Hi :) 
I have indeed deleted the ip, password and email for a matter of confidentiality.

Are these the errors you have detected?

Thanks

**Comment by merdok** [comment]
Ah, you are right. Anyway i see in the small log you provided that you are getting a handshake timeout which means that the plugin cannot connect to your device. Either your token or ip of the device might be wrong.

**Comment by mtnmx** [comment]
Hello, all European (Spain, France, Germany, Switzerland, Italia…) servers are located in de, cn is Chinese server, check this:

micloud": {
"username": "…[.@gmail.com](mailto:.@gmail.com)",
"password": "……",
"country": "cn",   <—— change for “de”

if your devices cannot connect open Mi home App and check one by one if they have the same IP address in homebridge, sometimes if you have unplugged your router or some devices they will get another new IP address.
