### ISSUE TITLE
Can we use 2 servers simultaneously ? 

### ISSUE THREAD

**Issue by Myth0zz** [merdok/homebridge-miot#254]
Merdok hi again! Thank you again for adding my vacuum in Hoobs. I have one question. I recently purchased a Mi Air Fryer BUT it works in Germany servers. I changed server in my Android phone and I see it. I also got token, IP, everything.

But my Whole MI Home (including my Vacuum) is in CN servers.

CAN I add another server in HOOBS? So that both (CN and DE) can be used simultaneously?

Is there a way? The plugin now only has option to select 1 server (I have CN).

Waiting on your reply,

Nick

**Comment by merdok** [comment]
The air fryer does not require a micloud connection, so you do not need that for the device. If you still want to use micloud you can just specify a different country for every device in the MiCloud section.
