### ISSUE TITLE
Xiaomi Air Purifier 3H

### ISSUE THREAD

**Issue by Ir0nTh0r** [merdok/homebridge-miot#256]
Hi. I have little problem with my Xiaomi Air Purifier 3H. I know that device is supported, but when I extracted token, device name isn't zhimi.airpurifier.mb3, but it is zhimi.airp.mb3a and I can't connect device. I tried both names but no luck. Below log:

[4/5/2022, 10:50:31 PM] [miot] [Air] (Protocol) 192.168.xx.xxx <- Reached maximum number of retries, giving up miIO.info - {"timeout":5000,"retries":3}
[4/5/2022, 10:50:31 PM] [miot] [Air] Error: Call to device timed out
[4/5/2022, 10:50:31 PM] [miot] [Air] Could not connect to the device! Retrying in 40 seconds!

Merdok please help.

**Comment by merdok** [comment]
Full zhimi.airp.mb3a support will be added in the next update, but never the less it should already work. I suspect that either the ip or token might be wrong since it is failing to do the initial request to the device.

**Comment by Ir0nTh0r** [comment]
Hi Merdok.

I checked the IP and Token, but it looks ok. I'll try to reset Purifier one more time and try with clean setup. Hope that it will work, if not I'll wait for next update. 

And as I said once, thank you for all your help and I owe you a beer again. ;)

**Comment by merdok** [comment]
If it still does not work you can post a deep debug log from homebridge startup and post here so I check if I can find there anything else.

**Comment by merdok** [comment]
Added in version 1.1.0, please check now.

**Comment by Ir0nTh0r** [comment]
Merdok, you are King! It works like a charm. Thank you for all your help and time.

**Comment by merdok** [comment]
Glad it works now :)
