### ISSUE TITLE
Roborock E4 support

### ISSUE THREAD

**Issue by dilipfeb** [merdok/homebridge-miot#259]
**Device model**

roborock.vacuum.a01

**Device name**

Roborock E4

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

no, it is not added with the plugin.

**Comment by merdok** [comment]
Will add support in the next update!

**Comment by merdok** [comment]
Support is now added in version 1.1.1
