### ISSUE TITLE
Open settings in browser cause high 100% cpu

### ISSUE THREAD

**Issue by erkage** [merdok/homebridge-miot#26]
I'm using homebridge from today so haven't got much info, but just installed this plugin and when i open it's settings popup it kills my chrome with high 100% cpu.
When i have time before it freezes out and close the settings popup it just immediately fix it so the cpu usege drops back to normal.

Can't see any error logs in devtools.

Versions:
macOS 11.3.1 (20E241) (Big Sur)
Chrome: 90.0.4430.85
Node.js: v14.16.0
Npm: v7.11.2
Homebridge: v1.3.4
homebridge-config-ui-x: v4.41.1 
omebridge-miot: v0.7.4

update: just tried it in safari and there's no problem so something goes wrong with chrome

**Comment by merdok** [comment]
Thanks for reporting, will check it out!

**Comment by merdok** [comment]
Just tried to reproduce it and i did not notice any issues (using latest Chrome). 
Could you tell me the exact steps to reproduce that? Like what exact buttons you click?

**Comment by erkage** [comment]
Just click on the Settings button of the plugin on Plugins page.
I'm created a video:
[https://www.icloud.com/iclouddrive/0z81loYM6PP62HumkE3c9X_fA#Screen_Recording_2021-05-13_at_7.43](url)

**Comment by merdok** [comment]
I do not think that it is related to the plugin, at least i cannot observe the same on machine, so I guess that it is related to your specific setup? Your chrome does not seem to be up to date, also maybe you have some extension installed which cause that?

**Comment by erkage** [comment]
Just happens with this plugin's settings the others works fine.
I'm just on one or two (sub)versions behind the latest chrome, but will update later today and check with that.
I used incognito mode where only few of my extensions enabled and killed the ones which are potential problematic.

Forget the above: now i downloaded Chrome beta so
- latest version
- no extensions
- no special or custom settings
and it just happens same as on my normal Chrome.

I'm also will try to investigate somehow but the problem is it kills everything on the page also the devtools so after a while it stop responding to anything.

**Comment by merdok** [comment]
Is there any error in the chrome dev tools console?
It might also be due to outdated plugins like homebridge or homebridge-ui-x.

**Comment by Abhi347** [comment]
I have a related issue that whenever I try to add a new device clicking on the text fields kills the webpage. I had similar issue with other webpages, but I found that it's related to some chrome plugins and I disabled them to make it work. I will suggest trying the same settings page in incognito disabling all the plugins or in an entirely different browser like Firefox or Brave.

**Comment by merdok** [comment]
Oh, that is actually a very good tip with the incognitio mode. It might certainly be the case that some plugins are causing the issue...
Thanks for letting us know!
