### ISSUE TITLE
cuco model device problem

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#263]
After updating the plugin v1.1.0, my devices like cuco.plug.cp1 and cuco.plug.cp1m keep restarting, cuco.light.sl4a doesn't work either, cuco.plug.cp2a works fine, and the icons are fine.

**Comment by louliangsheng** [comment]
[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/8489449/homebridge.log.txt)

**Comment by louliangsheng** [comment]
The log just says that the device cannot be connected, but my IP and token are correct, and I use it normally in v0.9.19.


{
            "devices": [
                {
                    "name": "Gosund插排",
                    "ip": "192.168.31.27",
                    "token": "64a9f6eb38b50aa15672948c8aebbaf7",
                    "deviceId": "264384679",
                    "model": "cuco.plug.cp2a",
                    "pollingInterval": 7,
                    "deepDebugLog": false,
                    "micloud": {
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": true,
                    "modeControl": false,
                    "showTemperature": false
                },
                {
                    "name": "狗剩插座左",
                    "ip": "192.168.31.51",
                    "token": "5cb10a61df33f5b30b2840efd3fe81ad",
                    "deviceId": "482159487",
                    "model": "cuco.plug.cp1",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                    "micloud": {
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "showTemperature": false
                },
                {
                    "name": "狗剩插座右",
                    "ip": "192.168.31.77",
                    "token": "4551d4a3803163f0093b6aab5fa42916",
                    "deviceId": "482718049",
                    "model": "cuco.plug.cp1",
                    "pollingInterval": 7,
                    "deepDebugLog": false,
                    "micloud": {
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "showTemperature": false
                },
                {
                    "name": "热水壶",
                    "ip": "192.168.31.213",
                    "token": "9b89632bbb9616e8e88d97b9cd3fd1d4",
                    "deviceId": "482781303",
                    "model": "cuco.plug.cp1",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                    "micloud": {
                        "forceMiCloud": false,
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "showTemperature": false
                },
                {
                    "name": "智能灯带",
                    "ip": "192.168.31.223",
                    "token": "d5953efb39dcdf89a40e2f2440376372",
                    "deviceId": "482374713",
                    "model": "cuco.light.sl4a",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                    "micloud": {
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "showTemperature": false
                }
            ],
            "_bridge": {
                "name": "Miot",
                "username": "0E:67:1B:DE:B5:99",
                "port": 45567
            },
            "platform": "miot"

**Comment by louliangsheng** [comment]
Sorry, I forgot to turn on the debug option of homebridge just now, the new log has been uploaded.

**Comment by merdok** [comment]
Just checked all the device classes there are no errors. Not sure what you mean with "restarting"? Based on your log the requests to the devices time out, maybe something changed? ip or token?
Also i noticed that you have one of your devices set as the wrong model:
`[狗剩插座左] Found device model cuco.plug.cp1m does not match specified model cuco.plug.cp1! Some services might not work!`
Seems that device is `cuco.plug.cp1m` and not a `cuco.plug.cp1`.

**Comment by louliangsheng** [comment]
Yes, I wrote the wrong model on purpose, I mentioned this question, and later I found that it can be changed to cp1 to work better, if it is cp1m, it will not work well, so I always write it as cp1, my current ip And the token works very stable under v0.9.19. My friends also said that the latest plug-in is not very easy to use, especially it is very unfriendly to coco model devices. For example, it will also cause cp5 to restart. I don't know why there is no log in the log. Related errors, but as far as I know, the performance of coco models is relatively poor, and cannot make too many requests. Some control requests can be appropriately disabled, such as disabling LEDs and child locks, as well as modes and so on.
In addition, I bought a new cp3 socket, and I hope you can support it.
Finally I very much hope that you can fix the support for coco devices, thank you for your work

https://github.com/merdok/homebridge-miot/issues/115
https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Aoutlet%3A0000A002%3Acuco-cp3a%3A2

**Comment by merdok** [comment]
The cp3 socket can be added yes, i will add that in the next update. 
I will also reduce the properties which are synced for those since it might be that those devices are overloaded with the huge requests. By forcing your device to be a cp1 even if it is not, you did that already and as you say it improves the performance so i guess that makes sense to do.

**Comment by louliangsheng** [comment]
I just bought the cuco.plug.cp5pro again, plugged in with the v0.9.19 plug-in as model cuco.plug.cp5, it works and it's perfect!
https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Aoutlet%3A0000A002%3Acuco-cp5pro%3A1

**Comment by merdok** [comment]
Sure, i can add the cuco.plug.cp5pro

**Comment by merdok** [comment]
As of version 1.2.0 i have reduced the number of synced properties to the minimum required for a device which should improve the connection!
