### ISSUE TITLE
handshake timeout

### ISSUE THREAD

**Issue by sadanro100** [merdok/homebridge-miot#265]
Everything was fine until I decided to setup my ISP modem and Apple Time Capsule in bridge mode, now for some reason I've been getting the error below.

 I've updated the device's ip in the plugin (which obviously changed because I started using the Time Capsule to attribute ips) and checked the token is still the same using the plugin's tool to fetch devices info from the Mi Cloud.
 
Any other ideas?

[4/27/2022, 11:20:09 PM] [miot] [Aspirador] (Protocol) Start handshake 10.0.1.5
[4/27/2022, 11:20:13 PM] [miot] [Aspirador] Error: Could not connect to device, handshake timeout
[4/27/2022, 11:20:13 PM] [miot] [Aspirador] Could not connect to the device! Retrying in 40 seconds!

**Comment by merdok** [comment]
Handshake timeout means pretty much that the token or ip is wrong and the plugin cannot connect to the device. Make sure those are correct!

**Comment by sadanro100** [comment]
I've double checked them both several times. They're all correct. Still getting timeout I'm afraid. I doubt it has anything to do with IP/token

**Comment by merdok** [comment]
The `handshake timeout` error like i already mentioned means that the plugin cannot connect to the device. The most common causes are wrong ip or token. It might also be that your device is simply not reachable in your network for some reason.

**Comment by sadanro100** [comment]
I am able to ping it's IP from my raspberrypi, where Homebridge is running.

**Comment by merdok** [comment]
Then your token is most probably incorrect.

**Comment by sadanro100** [comment]
I'm using the same token as before I changed my network architecture which worked, I checked it towards the info fetched by the plugin from the MiCloud and it hasn't changed.

Is there a chance it's wrong in the MiCloud?

**Comment by merdok** [comment]
I certainly already had cases where the token in MiCloud was outdated for some reason...

**Comment by sadanro100** [comment]
If that's the case, any idea how to fix that?

**Comment by merdok** [comment]
Try to reset the device and re-add it to the xiaomi home app, other then that you would need to use some manual methods to retrieve the token.

**Comment by sadanro100** [comment]
I wanted to avoid that otherwise I'll have setup all my rooms and ids again, but I guess there'll be no other way around it. Thanks

**Comment by sadanro100** [comment]
Just removed the device, re-added it to the app, a new token was retrieved. I updated the token in the plugin and still no joy... same timeout error unfortunately.

**Comment by sadanro100** [comment]
It actually worked! Surprisingly it kept that map, rooms ids and everything else. Thank you very much.

**Comment by merdok** [comment]
Glad it works now!
