### ISSUE TITLE
Please add support for device "qmi.plug.psv3"

### ISSUE THREAD

**Issue by uswong** [merdok/homebridge-miot#267]
**Device model**
qmi.plug.psv3

**Device name**
Xiaomi Smart Power Strip 2 (5 outlets)

**Does the device require a MiCloud connection?**
_Do not know_

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_
Not working at all, however the tile appears on Homekit correctly but I can not control it.  When I click on the tile, the tile will show "No Response".  This device is a Bluetooth device connected to Xiaomi Smart Home Hub 3 using its Bluetooth mesh.  I can control the device from Xiaomi App nicely.

Best regards,
Ung Sing

**Comment by merdok** [comment]
Unfortunately it is not possible right now to control Bluetooth devices. The plugin only works with wifi devices.
