### ISSUE TITLE
Support for S7MaxV Ultra would be nice!

### ISSUE THREAD

**Issue by Bend3smo** [merdok/homebridge-miot#268]
**Device model**
Roborock

**Device name**
S7 MaxV Ultra

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
-

**Comment by merdok** [comment]
Sure, but you need to provide the correct device mode. `Roborock` is just a marketing name and not the model. You can already try to add the device into the plugin and it should show you the model in the homebridge console or homekit.
