### ISSUE TITLE
Add Support For Mi Smart Standing Fan 1X

### ISSUE THREAD

**Issue by tantai251295** [merdok/homebridge-miot#27]
Pls add support for dmaker.fan.p5 (Mi Smart Standing Fan 1X). Thank u so much !!

**Comment by merdok** [comment]
Please see issue #23
The Mi Smart Standing Fan 1X is not a miot device. But you can use my other plugin [homebridge-xiaomi-fan](https://github.com/merdok/homebridge-xiaomi-fan) which supports that fan.
