### ISSUE TITLE
zhimi.fan.sa1 

### ISSUE THREAD

**Issue by guyue0227** [merdok/homebridge-miot#273]
**Device model**
_The unique model of your device, e.g zhimi.fan.sa1 _

**Device name**
_The friendly name of the device used by the manufacturer, Mi Standing Fan_

**Does the device require a MiCloud connection?**
_Yes/No/Do not know_
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
I can add it in the next update!

**Comment by merdok** [comment]
Added in version 1.2.1
