### ISSUE TITLE
cuco.plug.sp5 has been showing timeout, homebridge-miot v0.9.19 version but the new version 1.21. has been polling timeout.

### ISSUE THREAD

**Issue by Bladwintweak** [merdok/homebridge-miot#276]
cuco.plug.sp5 has been showing timeout, homebridge-miot v0.9.19 version but the new version 1.21. has been polling timeout
![XE @ XN9I~0_O7`QXQM Q81](https://user-images.githubusercontent.com/43061757/169944537-9f1ef963-736e-444c-bceb-9e39d51b92bc.png)
.

**Comment by merdok** [comment]
Did you try to reset your device?

**Comment by Bladwintweak** [comment]
yes. Reset is still prompted

**Comment by merdok** [comment]
Then you need to post some homebridge deep debug log so I can check if there is anything unusual.
