### ISSUE TITLE
Imilab EC3 automatic moving on his own

### ISSUE THREAD

**Issue by Semir333** [merdok/homebridge-miot#279]
**Describe the bug**
When the plugin active, the camera randomly, and repeatly move a littlebit to max sideway position on his own. Than not go back.

**Your config.json**
chuangmi.camera.025b02

**Debug log**

**Screenshots**

**Additional context**

**Comment by merdok** [comment]
The plugin does not control any device in any way by its own. When you say that it is moving randomly, then most probably something is controlling your device.

**Comment by Semir333** [comment]
No, i checked. When I’m on Hoobs this problem not have. When i changed to Homebridge and instal miot plug in this problem appear. I tried first to password the camera, and apply a high sec firewall and again do. When i disable the plugin (change the ip only to not search it) the camera not moving on his own.

**Comment by merdok** [comment]
Again, the plugin does not send any control commands by its own. I cannot tell what is controlling your device since I do not know your setup but I guess it might be some other software.

**Comment by Semir333** [comment]
And again :) no other plugins work with the camera. I have only 4-5 plugins (MIOT the only Xiaomi) others are Gree, LG TV and kind of this. When i add camer to MIOT problem is active, when i remove, problem is not active. I belive the plugin not control anything, but maybe a code, or a login process do something with the camera, and that protocoll maybe moved a little bit. It can be in Xioami side when log to the account or kind of this. Just a sentence.

**Comment by merdok** [comment]
It might be xiaomi, it might be some kind of a setup of the camera or calibration. It might also be that as soon as you add the camera to homekit some other software is controlling it for some reason. 
I am not able to tell why your camera is doing that but i can certainly say that it is not the plugin itself which controls it. Every single command for controlling must be first triggered.
