### ISSUE TITLE
Improve Air purifier management interface

### ISSUE THREAD

**Issue by tantai251295** [merdok/homebridge-miot#28]
You can Change Fan Control, Led, Mode from switch to select in Air Purifier control ?

![image](https://user-images.githubusercontent.com/70562867/118265663-b7d99d00-b4e3-11eb-9707-645724ca87cf.png)

Fan Control, Led, Mode like Child Lock, Mode.
![image](https://user-images.githubusercontent.com/70562867/118265717-c7f17c80-b4e3-11eb-975d-e40c02be78e7.png)

**Comment by merdok** [comment]
Unfortunately this is not possible as far as i know, so it needs to be an additional switch. If i ever find a way to do it like that then i will adjust it because i also think that it would be more cleaner.
