### ISSUE TITLE
New device support

### ISSUE THREAD

**Issue by WaxenSs** [merdok/homebridge-miot#280]
**Device model**
_chuangmi.camera.029a02_

**Device name**
_Xiaomi Mi 360° Home Security Camera 2K_

**Does the device require a MiCloud connection?**
_No_

**Anything special about the device?**
_The switches already work with the plugin ( turn off the LED / enable or disable the camera):_
<img width="524" alt="CleanShot 2022-05-30 at 16 37 04@2x" src="https://user-images.githubusercontent.com/37812331/171014506-a32f8249-ae58-4b34-9809-f281baf09a0f.png">

Thanks 😄

**Comment by merdok** [comment]
The same as with the vacuum, i would need first access to the actual camera to try to get it to work. Right now i do not have access to any xiaomi camera so i cannot do that...
