### ISSUE TITLE
Add functionality to access the camera of a vacuum cleaner

### ISSUE THREAD

**Issue by WaxenSs** [merdok/homebridge-miot#281]
**Describe the idea or improvement**
_Add functionality to access the camera of a vacuum cleaner (roborock.vacuum.a10) when it is running_

**Describe the solution you'd like**
_As soon as the vacuum cleaner is running, the camera from Home could activate, showing the view of the vacuum cleaner.
If the vacuum cleaner is off, the camera would simply be disconnected._

**Comment by merdok** [comment]
Hi, I know that some newer vacuums have a camera which can be accessed. I think it would be possible to add that to homekit but unfortunately that is not an easy task for me to do without having the actual hardware. So probably i cannot do anything until i get my hands on a vacuum with such a camera...
