### ISSUE TITLE
Please add support for zhimi.airpurifier.ma2

### ISSUE THREAD

**Issue by vmx-kbabenko** [merdok/homebridge-miot#29]
I would like to request a support for Xiaomi  Air Purifier S2 aka zhimi.airpurifier.ma2.

Type info: miio:air-purifier, sensor, miio, air-purifier
Capabilities: miio:buzzer, miio:led-brightness, miio:switchable-led, pm2.5, relative-humidity, temperature, switchable-mode, mode, switchable-power, restorable-state, power, state

Please let me know what other information I could provide to integrate the device.
Thank you.

**Comment by merdok** [comment]
Hello,

thanks for the request. Unfortunately the zhimi.airpurifier.ma2 air purifier is not a miot device. It uses the older miio protocol.
