### ISSUE TITLE
Stuck on Everything looks good! Initiating property polling!

### ISSUE THREAD

**Issue by juster-cyber** [merdok/homebridge-miot#290]
**Describe the bug**
I can't control device. Stuck on `[Robot] Everything looks good! Initiating property polling!`. 

**Expected behavior**
_Device fully controllable_
**Your config.json**
{
  "devices": [
    {
      "name": "Robot",
      "ip": "192.168.0.188",
      "token": "xxxxxxxx",
      "deviceId": "xxxxxxxx",
      "model": "roborock.vacuum.m1s",
      "pollingInterval": 10,
      "deepDebugLog": true,
      "micloud": {
        "username": "xxxxx@xxxxx.com",
        "password": "xxxxxxxx",
        "country": "ru",
        "forceMiCloud": true,
        "timeout": 10000
      },
      "buzzerControl": false,
      "ledControl": false,
      "childLockControl": false,
      "modeControl": false,
      "fanLevelControl": false
    }
  ],
  "platform": "miot"
}

**Debug log**
[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/8986233/homebridge.log.txt)

**Additional context**
I tried to restart the homebridge
I tried to reset token and ip for robot
With and without Mi account
With or without device model and ID

> `OS: Windows 10 Home

> Homebridge: [v1.5.0] (https://github.com/homebridge/homebridge/releases/tag/v1.5.0)

> homebridge-miot v1.2.3

> node:  16.15.1 (x64)

> npm: [v6.1.0](https://github.com/npm/npm/releases/tag/v6.1.0)`

**Comment by merdok** [comment]
You need to post a homebridge debug log with the deepDebugLog flag set to true, please have a look here. https://github.com/merdok/homebridge-miot#troubleshooting without that i will not able to help you.

**Comment by juster-cyber** [comment]
> You need to post a homebridge debug log with the deepDebugLog flag set to true, please have a look here. https://github.com/merdok/homebridge-miot#troubleshooting without that i will not able to help you.

how to do this?

**Comment by merdok** [comment]
Just have a look at the link which i posted. It has the exact shell command to start homebridge in debug mode.

**Comment by juster-cyber** [comment]
okie. Anyways i will be afk for a couple of days
[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/9031514/homebridge.log.txt)

**Comment by merdok** [comment]
Your ip or token is incorrect since based on the logs the handshake with the device is failing.

**Comment by juster-cyber** [comment]
But the IP and token are correct! I also tried using a third -party utility ( token extractor ) so with the utility built into the plugin, anyway!

**Comment by merdok** [comment]
I also see a lot of `Error: The device with id xxxxxx could not be found on the ru server! Please make sure that the specified micloud country is correct!` I would recommend to recheck that.

**Comment by juster-cyber** [comment]
It's totally right! I think you need to see my logs again
[homebridge.log (3).txt](https://github.com/merdok/homebridge-miot/files/9262873/homebridge.log.3.txt)
.

**Comment by juster-cyber** [comment]
Ok, i deleted id from plugin but it still doesnt work
[homebridge.log (4).txt](https://github.com/merdok/homebridge-miot/files/9262888/homebridge.log.4.txt)
!

**Comment by merdok** [comment]
As i already mentioned `handshake timeout` which appears in your log means either token or ip is incorrect.
