### ISSUE TITLE
Roborock .jsn

### ISSUE THREAD

**Issue by yestrdave** [merdok/homebridge-miot#291]
Could use a little help.  I have been using another plug in on my roborock.vacuum.a10 for about a year. I have an new roborock.vacuum.a27 (Roborock S7 MaxV Ultra) coming in this week and was trying to set up my roborock.vacuum.a10 to see how the plug in works.  I have everything working and I wanted to set up room switches. Based on what I could find, I'm assuming this is the correct format.

 "actionButtons": [
                {
                    "action": "vacuum:start-sweep",
                    "name": "Clean Kitchen",
                    "params": [
                        0,
                        1,
                        "21"
                    ]
The previous room ID is 21.  The switch that is created just runs Quick Start.  I also tried action 2.1 

This was my old plug in
"rooms": [
                {
                    "name": "Master Bathroom",
                    "id": 16
                },
                {
                    "name": "Master Bedroom",
                    "id": 17
                },
                {
                    "name": "Living Room",
                    "id": 18
                },
                {
                    "name": "Game Room",
                    "id": 19
                },
                {
                    "name": "Office",
                    "id": 20
                },
                {
                    "name": "Kitchen",
                    "id": 21
                },
                {
                    "name": "Bedroom One",
                    "id": 22
                },
                {
                    "name": "Bedroom Katie",
                    "id": 23
                },
                {
                    "name": "Laundry Room",
                    "id": 24
                },
                {
                    "name": "Family Room",
                    "id": 25
                },
                {
                    "name": "Bedroom Guest",
                    "id": 26
                } 

Any help would be appreciated

**Comment by merdok** [comment]
The roborock.vacuum.a10 does not support room cleaning, at least not using the miot protocol. Your device does not use the miot protocol natively but uses a emulation layer over the MiCloud for that, with a limited functionality which unfortunately does not include room cleaning. 

The roborock.vacuum.a27 is a different topic as it natively uses the miot protocol. You have a look at the various properties and actions here: https://merdok.github.io/miotspec/?model=roborock.vacuum.a27

**Comment by yestrdave** [comment]
Would this be the correct format for .a27?

"actionButtons": [
{
"action": "vacuum:start-sweep",
"name": "Clean Kitchen",
"params": [
0,
1,
"21"
]

**Comment by merdok** [comment]
The action which you are looking for is vacuum:start-room-sweep
It accepts one string parameter which is described as room ids.
The tricky part is usually to find out what the format should be of that parameter. The best way to do that is to use the modified mi home android app and catch the request which is sent to the device, then you would know what format it should be.
Unfortunately nobody yet provided me with that info, hence roborocks are missing in the robot cleaner doc.

**Comment by yestrdave** [comment]
I would love to help but don't have any android devices. I guess I'm dead in the water for now

**Comment by yestrdave** [comment]
Where do I find the modified mi home app?
