### ISSUE TITLE
can add support for Mi smoke detector?

### ISSUE THREAD

**Issue by i7s7x** [merdok/homebridge-miot#292]
https://www.mi.com/shop/buy/detail?product_id=13635

**Device model**
I can't find the unique model ， cmiit id:2020dp15509 ? or   Product model： jtyj-gd-03mi/BB   ？？

**Device name**
Mi smoke detector

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
Gateway required，I use Mijia smart socket 2(Bluetooth gateway version)

**Comment by merdok** [comment]
If a gateway is required then i guess it is either a zigbee or  bluetooth device which will unfortunately not work.

**Comment by Avamander** [comment]
@merdok Would things be different now that direct cloud and hub connections are both supported?

I tried adding `lumi.sensor_smoke.mcn02` for example, but it seems that `smoke-sensor:status` is not mapped to a characteristic HomeKit supports.

**Comment by merdok** [comment]
Indeed it should be possible I think. Does it work if you try to use propertyMonitor on the some sensor status property? If you can confirm that it indeed works then I would go ahead and try to add a smoke detector accessory.

**Comment by Avamander** [comment]
@merdok I'll try that out.

From the logs I see that the Mi Cloud connection shows sensor state (busy if it's working) and battery state, I haven't triggered it yet (it's loud :S).

**Comment by merdok** [comment]
Yeah, if you say that the values update then I guess we could add a new accessory for that. Could you please open a new issue with a feature request for that, so that I do not forget?
