### ISSUE TITLE
MiCloud Two-Factor Issue

### ISSUE THREAD

**Issue by JacopoBassan** [merdok/homebridge-miot#296]
Hi,

I was trying to install and configure the homebridge-miot plugin to use with my Xiaomi Vacuum 1C Robot but it fails at the very first "Discover all devices via MiCloud" step since my account is set up with 2FA.
The plugin seems to support it using the open link in a browser from the same public IP, but in the error notice it doesn't give me the link it's talking about, neither there nor thru the console, or am I the one missing where it should be?

Can you help me? Thanks!
<img width="388" alt="Schermata 2022-07-05 alle 11 53 06" src="https://user-images.githubusercontent.com/1736964/177302753-28ed91a1-2430-496b-9dee-e960ffe11436.png">

**Comment by merdok** [comment]
Oh, you are right! Going to fix that in the next update! Thanks for letting me know!

**Comment by merdok** [comment]
Should be fixed in version 1.2.4

**Comment by JacopoBassan** [comment]
Thanks I've updated it and now the link is there, I got the ok response from the 2FA link but then it doesn't work anyway. Opened the link in a browser on a computer on the same network as Homebridge, any tips? Thanks!

**Comment by merdok** [comment]
I unfortunately do not have 2fa enabled so I cannot test myself, but you eventually could try to open the link in the same page, since maybe some cookies are set?
