### ISSUE TITLE
Replace switch by heater cooler for Air Fryer 

### ISSUE THREAD

**Issue by nicolasbigot** [merdok/homebridge-miot#298]
So I have just purchased a [Xiaomi Air Fryer](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:air-fryer:0000A0A4:careli-maf02:1) with identifier `careli.fryer.maf02`.

**Everything works great, but I was wondering if is it possible to use the heater cooler accessory switch to turn on/off heating, instead of an additional switch?**
As this model supports target temperature, the default heater cooler HomeKit accessory already has a tiny switch to enable heating/cooling.
On the current implementation, only the main additionnal button turns the fryer on/off.
The heater cooler switch does nothing.
![image](https://user-images.githubusercontent.com/3419988/178968100-54f2a885-4c79-4fa3-92b3-7ef82f5d90a6.png)

**Additionally, I was wondering if it could be possible to support current temperature in the heater cooler?**
It always seems to return 0.0 degrees when heating or off. 
Would it be possible to return the target temp as the current temp when heating?
I noticed the specs as reference to a `custom:work-temp` property.

**Finally, there is a "remaining time" Lux sensor that is always shown, whether the heater is on or off.**
Can it be temporary hidden if fryer is off? I don't really know if HomeKit supports this natively.

Many thanks!

**Comment by merdok** [comment]
Yeah, there was a reason why it is like it is right now, but I honestly forgot why😅

With the remaining time at least it is not possible or at least not good behavior to remove and add service on the fly depending on the device state, so that will always have to be there.

There stuff I guess is a comprise which has to be taken right now because it is included in the oven module... maybe I would need to make a special module for air fryers...

**Comment by nicolasbigot** [comment]
I guess it’s because some ovens do not support target temperature? Which I understand why a single button is necessary.
What about having the heater cooler for accessories that support temperature and button devices that don’t? 
Or maybe you wanted temperature to be set before starting the fryer?
that would be 100% more satisfying to use ❤️

**Comment by nicolasbigot** [comment]
Also, what about having the target temp instead of 0.0 degrees when fryer is on?

**Comment by merdok** [comment]
I also have the same air fryer and I did the development by testing it in my device. Some stuff is not so intuitive when using the miot spec api. You are right with the temp, the same goes for time, they both need to be set before even starting the cooking. When using the heater service as soon as you start choosing the temperature the air fryer will start and the temperature cannot be set anymore during that period. That more or less means I would need to constantly turn off the device set temperature and turn it in again when you drag to choose the target temperature. You have to keep in mind that HomeKit officially does not support ovens or cooking device, hence some devices will only work with some workarounds.

**Comment by nicolasbigot** [comment]
Just tested and it seems that the temp and time can be adjusted on the device and via HomeKit when the fryer is on.

**Comment by merdok** [comment]
What happens when you change the time or temp during an active cooking phase?

**Comment by nicolasbigot** [comment]
It changes on the oven, and vice-versa.

—
Nicolas Bigot
***@***.***

**Comment by nicolasbigot** [comment]
Hey @merdok, thank you for your work on this.
Just updated, but it looks like the main service is now a lightbulb and not the heater cooler. 
Was the last release supposed to fix the issue discussed here or not?
Many thanks !

**Comment by merdok** [comment]
The main service is still a switch and a heater cooler as before.
There was never a lightbulb as the main service.
The heater cooler in HomeKit is not meant for controlling oven or air fryer devices hence there are some limitations. During my testing this is simply the best way that you can get an air fryer device working in HomeKit.

**Comment by nicolasbigot** [comment]
But what about the solution I offered? Are you willing to consider it?
Heater cooler already has a button to start/stop, this eliminates the need to have a dedicated button.
Heater could report 0 degrees when off and target temperature when on.
Pause can be handled with dedicated button if necessary.
Target time remains with lightbulb.

**Comment by merdok** [comment]
That this solution does not work because of the way how the heater cooler service expects device to behave. The air fryer device simply does not behave as it is expected.
You need to understand that HomeKit is very limited regarding supported devices, hence there needs to be some workarounds and tricks to make certain devices work.

The service is not a lightbulb. Your accessory group might be a lightbulb, but that depends on some other factors which I cannot control, like what kind of service you are using in the group.

**Comment by nicolasbigot** [comment]
Hey @merdok, I checked and main service is absolutely defined as a lightbulb. I know HomeKit is very limited, don't get me wrong, and fully appreciate your work on this plugin, but I don't think this should be the case. There is a ON/OFF switch that could perfectly do the trick and avoid the Home app tile to be always ON (as the lightbulb never gets off).

Do you have any idea on how to make the switch the main service?

![image](https://user-images.githubusercontent.com/3419988/192140475-7f54b6bc-f7ce-466d-8d4b-3bb516642916.png)

**Comment by merdok** [comment]
The air fryer main service is certainly not a lightbulb. It is using a HeaterCooler and a ON/OFF switch service. It was like that from the beginning. It might be that for some reason your Home app is showing you the target time as you group main service, but hat i cannot control.
As a workaround i can recommend you to set `onlyMainService` property to `true`, which will only leave the ON/OFF switch and HeaterCooler services, and the rest what you need add by using `propertyControl`

**Comment by nicolasbigot** [comment]
I'll give it a go then. Maybe try to delete the accessory and re-add it. thanks.

**Comment by nicolasbigot** [comment]
Ok, ive deleted the accessory and added it again and it seems to have fixed the lightbulb as main accessory. I guess recent changes fucked up HomeKit cache and resetting everything did the trick.

thanks @merdok

**Comment by merdok** [comment]
Yeah, not sure on what basis HomeKit is selecting the service which is displayed as the group main service... but glad that the issue was resolved!
