### ISSUE TITLE
No support for cleaning zones

### ISSUE THREAD

**Issue by j08rebelo** [merdok/homebridge-miot#299]
**Describe the bug**
I'm trying to setup my Dreame F9 in home assistant.
Using Xiaomi Miot I can get the vacuum recognized and I can start/stop (among other features), but one thing that doesn't work is selecting a zone and sending the vacuum to clean that zone.

![image](https://user-images.githubusercontent.com/11061324/179193417-93252b3d-515e-439d-bddf-451c2c572351.png)

If I choose a zone and send the robot to clean it I get this error:
![image](https://user-images.githubusercontent.com/11061324/179193589-34b56ebc-d16e-440c-a37e-6b6f0f94f718.png)

I have also created several zones, but it's not working.
This is my current code:

type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_p2008_d43b_robot_cleaner
vacuum_platform: send_command
title: Dreame F9
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_goto_predefined
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - -5761
            - -2777
            - 782
            - 1810
        label:
          text: Sala
          x: -2355
          'y': -236
      - zones:
          - - 3979
            - -328
            - 8162
            - 3184
        label:
          text: Cozinha
          x: 6041
          'y': 1228
      - zones:
          - - 752
            - -2955
            - 2604
            - -1327
        label:
          text: WC
          x: 1768
          'y': -2029
      - zones:
          - - 3889
            - -3017
            - 8580
            - -521
        label:
          text: Quarto_Madalena
          x: 6179
          'y': -1790
      - zones:
          - - 3859
            - -5735
            - 8580
            - -3031
        label:
          text: Escritorio
          x: 6250
          'y': -4270
      - zones:
          - - 932
            - -5735
            - 3172
            - -3957
        label:
          text: WC_Quarto
          x: 1888
          'y': -4837
      - zones:
          - - 2635
            - -4181
            - 4009
            - 1810
          - - 962
            - -1104
            - 2665
            - 1840
        label:
          text: Hall
          x: 2293
          'y': 302
      - zones:
          - - -3908
            - -5854
            - 992
            - -2821
          - - 1022
            - -4093
            - 2696
            - -3001
        label:
          text: Quarto
          x: -234
          'y': -3493
  - template: vacuum_follow_path

**Expected behavior**

To be able to clean by zone.

**Comment by merdok** [comment]
This is the homebridge plugin github, and it is not related to the home assistant plugin. I guess you opened the bug in the wrong place.
