### ISSUE TITLE
Would you please to add support for Lonink Air Conditioner Gateway and Xiaomi Curtain (Wi-Fi)

### ISSUE THREAD

**Issue by JKSec** [merdok/homebridge-miot#300]
https://home.miot-spec.com/s/qdhkl.gateway.lonink
https://home.miot-spec.com/s/lumi.curtain.hmcn01

**Device model**
qdhkl.gateway.lonink
lumi.curtain.hmcn01

**Device name**
Lonink Air Conditioner Gateway
Xiaomi/Mijia Smart Curtain (Wi-Fi)

**Does the device require a MiCloud connection?**
_No_

**Anything special about the device?**
_No_

**Comment by merdok** [comment]
What happens if you add those devices now? Do they work?

**Comment by JKSec** [comment]
No. They don't work right now.

**Comment by merdok** [comment]
Did you try to enter your micloud credentials and set the `forceMiCloud `property to true or enable it in the homebridge ui?

**Comment by JKSec** [comment]
These devices are not in your supported list currently. Does this way work?

**Comment by merdok** [comment]
That does not matter, that list is more or less a tested devices list. You should try adding your devices and see what happens.

**Comment by JKSec** [comment]
Still not work 😟 The AC gateway is shown as a switch, and nothing happens

**Comment by merdok** [comment]
Then you need to post the debug log so I can have a look what is wrong.
