### ISSUE TITLE
zhimi.airpurifier.v7

### ISSUE THREAD

**Issue by luluhoc** [merdok/homebridge-miot#301]
**Device model**
zhimi.airpurifier.v7

**Device name**
Xiaomi Air Purifier PRO

**Does the device require a MiCloud connection?**
YES

The plugin is finding the device the only problem is that it wrongly named the buttons all were called air purifier and the biggest problem is that I can't add fan control it doesn't even appear in action in here https://merdok.github.io/miotspec/?model=zhimi.airpurifier.v7

**Comment by merdok** [comment]
The device is already supported, when there is no fan control then it means that your device does not support it and there is nothing i can do about it. Please note that devices which require MiCloud have a reduced feature set.

**Comment by skaldek** [comment]
But what about buttons names?

**Comment by merdok** [comment]
I assume that you are using iOS15 Beta? This is either a bug in the beta or something changed which i am not aware of, until iOS15 is officially released i am not sure what the issue exactly is and cannot really do anything. You must currently go back to iOS14 or wait until iOS15 is officially released.

**Comment by arturdobo** [comment]
@merdok is there any way to workaround the no fan control issue? I was able to control favourite mode level while using the purifier on Home Assistant

**Comment by merdok** [comment]
@arturdobo unfortunately no, as the device simply does not support this functionality using the miot protocol.
