### ISSUE TITLE
iOS 16 PB1 action button names not transferred towards HomeKit

### ISSUE THREAD

**Issue by GaborSchM** [merdok/homebridge-miot#302]
Hi Merdok, not sure if this is related to the plug-in, just a feedback. Under iOS16 PB1 the mode control buttons and the action buttons names are not getting transferred to HomeKit, everything gets the name of the device itself. 

Didn't see anything similar with other plugins yet. 

Attached a snippet of the config, cannot copy paste properly on phone, but no changes made in months, only the iOS version. 

Thanks for your great plug-in! 
Cheers 

![image](https://user-images.githubusercontent.com/94196335/179416850-e2bc7f1a-2bf9-4771-bff9-1290983fc266.jpeg)

![image](https://user-images.githubusercontent.com/94196335/179416855-8d74c1d2-23b9-419c-adc8-50b48a3e6ca9.jpeg)

**Comment by merdok** [comment]
I also have noticed that but not sure yet what is causing this. Maybe it is a bug in ios16? Since when you remove the name from the button then as a placeholder you will see the actual name which you have given...
