### ISSUE TITLE
Air Quality in HomeKit 

### ISSUE THREAD

**Issue by suzdalini7** [merdok/homebridge-miot#303]
After adding zhimi.airfresh.va4 (Smartmi Fresh Air System XFXTDFR02ZM) into Apple HomeKit by means of homebridge-miot plugin instead indications Air Quality (PM2.5) in Home app displayed temperature sensor which always shows 2.5 degrees Celsius 
![C17C07AD-719D-42AE-9B5E-C2CDD681A66F](https://user-images.githubusercontent.com/65533881/179725885-1715b1d0-f760-407c-b75b-0a4de7711af7.png)

**Comment by merdok** [comment]
Hi,

you would need to post a homebridge debug log with the deepDebugLog property set to true so I can have a look what is happening and where the issue might be.

**Comment by suzdalini7** [comment]
[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/9153676/homebridge.log.txt)

**Comment by merdok** [comment]
Thanks, based on the log, this is the correct value.
`"environment:temperature: 2.58",`
This is delivered by the device and the plugin just shows that up.

**Comment by suzdalini7** [comment]
Ok, can I see indications Air Quality (PM2.5) in home app like I see this in mi home?
![F28E2CCB-9B7C-4BC8-B0FD-9FFE1BB30726](https://user-images.githubusercontent.com/65533881/180563138-4dd58e74-4439-4092-832a-01661c503ac8.png)

**Comment by merdok** [comment]
Your device reports the co2 density and the air quality index hence they should be available in he home app.

**Comment by vanillabearr** [comment]
> After adding zhimi.airfresh.va4 (Smartmi Fresh Air System XFXTDFR02ZM) into Apple HomeKit by means of homebridge-miot plugin instead indications Air Quality (PM2.5) in Home app displayed temperature sensor which always shows 2.5 degrees Celsius
> ![C17C07AD-719D-42AE-9B5E-C2CDD681A66F](https://user-images.githubusercontent.com/65533881/179725885-1715b1d0-f760-407c-b75b-0a4de7711af7.png)

sensor not correctly identified. 
![9BB6EE8C-704F-42AB-8AFB-2FE119A0CE50](https://user-images.githubusercontent.com/98265036/180600690-fc4dec3f-16e3-4242-bd00-7a2afb807c69.png)

**Comment by vanillabearr** [comment]
I have another problem with a similar device. Maybe a specific type of device has changed api? 
https://github.com/merdok/homebridge-miot/issues/269#issue-1229860221

**Comment by merdok** [comment]
@vanillabearr what do you mean by sensor not correctly identified? You need to be quite specific about your issues and post some homebridge debug logs with the `deepDebugLog` property enabled.

**Comment by vanillabearr** [comment]
> @vanillabearr what do you mean by sensor not correctly identified? You need to be quite specific about your issues and post some homebridge debug logs with the `deepDebugLog` property enabled.

I have this parameter displayed correctly as an air quality sensor.  At the @suzdalini7, the system defines it as a temperature sensor.

**Comment by merdok** [comment]
Looking at the api everything is still the same so no changes there. @vanillabearr you also have the same device i suppose?

**Comment by vanillabearr** [comment]
My model zhimi.airfresh.va2, 
@suzdalini7 zhimi.airfresh.va4

**Comment by merdok** [comment]
Yeah, you have different models and there will be differences between your device and the other. It all depends on how the device reports certain stuff.

**Comment by suzdalini7** [comment]
![3](https://user-images.githubusercontent.com/65533881/181099142-34de123b-c719-48b5-b7e0-10aa52a18e3e.jpg)
![2](https://user-images.githubusercontent.com/65533881/181099143-302a5afc-49fc-43a7-a1f7-c6199a04bbfe.jpg)
![1](https://user-images.githubusercontent.com/65533881/181099146-5e9ac2fb-2874-4ef3-a945-9bc71661bde0.jpg)
In Mi home app my device shows co2 density (402 in screenshoot), the air quality index inside (008) and outside (32), temp (28) and humidity (49), but in Apple home I see humidity (49), co2 density, wrong temp (3.0) and don't see internal and external air quality index
