### ISSUE TITLE
Air Purifier wrong Device

### ISSUE THREAD

**Issue by jannnfe** [merdok/homebridge-miot#308]
Hello,

I have had the problem for a long time that the device has suddenly changed and is no longer indicated as an air purifier. How can I change that again? I've already completely deleted the two air purifiers and emptied the cache, but that didn't help.

Many Thanks.

![IMG_9176](https://user-images.githubusercontent.com/30130742/180663352-1a60d0c6-a470-4592-81b5-496b9e24192b.PNG)
![IMG_9178](https://user-images.githubusercontent.com/30130742/180663271-2ab96738-9d8a-4e62-8ae0-e04741bfb52d.PNG)
![IMG_9177](https://user-images.githubusercontent.com/30130742/180663272-819d0b74-b798-4108-91e6-e9870f21fa31.PNG)

**Comment by merdok** [comment]
Hi,
i am not quite sure what you mean, but i see that inside the group you still have the air purifier so it seems for me that everything is working fine. What you have in your favorites is the group of accessories and not the air purifier itself. You probably did show the group as separate tiles before, hence the change. In the group settings you can split it into separate tiles if this is what you need.

**Comment by jannnfe** [comment]
sorry for my late reply. i mean: the main unit does not show up as a purifier in homekit.  it's an electrical outlet and an air quality meter. I have grouped the different devices and would like to keep them grouped as well.  however, what bothers me is that the main unit is no longer an air purifier. It wasn't always like that. That suddenly changed.

**Comment by Olivierbkk** [comment]
I have a similar problem with air purifier, the icon displayed in homekit is a temperature sensor, not an air purifier. I cannot ungroup the accessories btw.

![image](https://user-images.githubusercontent.com/113991249/202840972-ebf8d053-eb71-4882-a3f5-9c5253591d51.png)

perhaps it has to do with the first accessory displayed in the list which is a thermometer

**Comment by merdok** [comment]
Yeah, probably that is how it is done by the Home app. Unfortunately as far as i know we cannot manually control the order of the accessories in the group, but you could try to re-add the device and see if the order changes?

**Comment by Olivierbkk** [comment]
it's fixed in the latest release apparently, thanks!
