### ISSUE TITLE
miot and hoobs

### ISSUE THREAD

**Issue by qforqiu** [merdok/homebridge-miot#309]
**Describe the bug**
_A clear and concise description of what the bug is._
Can't find Discover All Devices via MiCloud

**Expected behavior**
_A clear and concise description of what you expected to happen._
Trying to obtain token for Roborock S7 on hoobs

**Comment by merdok** [comment]
You either have to go to the homebridge ui and in the miot settings area you will find the button. Another option is that you use the command line tools to get the tokens.

**Comment by qforqiu** [comment]
Hi,

Thank you for your reply. I am new to homebridge, so I bought HOOBS due to my lack of knowledge. 
I tried to install homebridge, and I can't get it to work with HOOBS. 
With the command line miot cloud-devices -u <username> -p <password> is the username and password my mi username and password? 

Thank you so much.

**Comment by merdok** [comment]
Homebridge is already included in hoobs, you just need to visit the ui.

For cli:
1. miot cloud login -u user -p password
2. miot cloud list-devices

**Comment by qforqiu** [comment]
Hi,

Thank you for the help. Is there any article for visiting homebridge UI via hoobs?

**Comment by merdok** [comment]
Just look for homebridge ui and I am sure you will find info about it.

It is called homebridge-config-ui-X
