### ISSUE TITLE
No mop mode control for the Dreame d9 anymore 

### ISSUE THREAD

**Issue by Sauberkiwi** [merdok/homebridge-miot#311]
**Describe the bug**
_A clear and concise description of what the bug is._

Hey I got an dreame d9 connected to hk via hoobs and miot. Anything worked well so far until my card got corrupted. After a reflash (and no backup) all my plugins are gone. So I reinstalled miot and connected my dreame. But now, I got no controls over the mop mode anymore. Can anyone help me with this issue? It’s important because I use Automations that toggle she mop water mode.

Regards,
Sauberkiwi

**Comment by merdok** [comment]
You already opened a discussion for that. No need for an extra issue.
