### ISSUE TITLE
Add support for Aqara Roller Shade Driver E1?

### ISSUE THREAD

**Issue by robinviking** [merdok/homebridge-miot#312]
I was reading the compatibility list and didn't se Aqara Roller Shade Driver E1. Would love to se this plug-in work with that produkt. 
Are you gonna add support for this product?

Thanks.

https://www.aqara.com/en/product/roller-shade-driver-e1

**Comment by merdok** [comment]
As far as I can see that is not a wifi device but a zigbee device, hence support cannot be added.
