### ISSUE TITLE
Support dreame d10

### ISSUE THREAD

**Issue by lenny005** [merdok/homebridge-miot#314]
Could you please add the dreame d10 robot vaccum cleaner  ?

**Comment by merdok** [comment]
Sure, but you need to provide the unique model of the device so that I know what device it is.

**Comment by lenny005** [comment]
Ah yes sorry, the model is RLS3D and the base model is RCS7

**Comment by merdok** [comment]
That is not the device model which I need.
If you do not know the correct device model, then just add the device to the plugin and the plugin will automatically detect the correct one and display it in the homebridge log during startup.

**Comment by lenny005** [comment]
Do you know where can i find the model number elsewhere please? I don’t have a micloud account

**Comment by merdok** [comment]
You do not need a micloud account. Just put in your device ip and token and that should be enough. The plugin will then be able to connect to your device and determine the device model.

**Comment by lenny005** [comment]
dreame.vacuum.r2205

**Comment by merdok** [comment]
Thanks, that is the correct👍 The vacuum should already work now, full support I will add in the next update.

**Comment by merdok** [comment]
The device is now added in version 1.3.0
