### ISSUE TITLE
Please add support for Xiaomi Ultra-thin vacuum robot

### ISSUE THREAD

**Issue by PParit** [merdok/homebridge-miot#317]
**Device model**
_dreame.vacuum.p2148o

**Device name**
_Xiaomi Mijia Ultra-thin vacuum robot (STYTJ04ZHM)

**Does the device require a MiCloud connection?**
_Do not know_

**Anything special about the device?**
_Nope_

**Comment by merdok** [comment]
Sure, will add full support in the next update. It should already work right now if you try to add it.

**Comment by PParit** [comment]
wow, Thanks. I did not notice that :)

**Comment by merdok** [comment]
The device is now added in version 1.3.0
