### ISSUE TITLE
Better HOOBS integration

### ISSUE THREAD

**Issue by xazac** [merdok/homebridge-miot#318]
Your plugin works with HOOBS hub, but it’s not well integrated because whenever I add a new device with its own specific model, the script doesn’t adapt the right features as it does in the standard Homebridge environment.
So I can’t remove any options as I did in Homebridge and it’s a very messy experience.

Can you please consider to get it work on HOOBS hub as expected?
Thanks!

**Comment by merdok** [comment]
I am not sure why this should not work well with HOOBS, since it just uses the normal homebridge under the hood. As long as you provide a model then the configuration which is not relevant for the specified model should be hidden.

**Comment by xazac** [comment]
> 

This what I expected but it’s not.
In a standard Homebridge environment your plug-in adapt itself once a specific model is setup. In HOOBS this doesn’t happen and I can’t understand which options are relevant for the model and which are not as the plug-in doesn’t adapt.
Is there any workaround? A list of manual strings maybe could help to manually add relevant code lines. Let me know, thanks!

**Comment by merdok** [comment]
There are no manual ways, the only thing which needs to be provided is the device model. This is just a simply script based on the angular json schema form so not sure why this should not work in HOOBS.

**Comment by xazac** [comment]
Okay, so bad

**Comment by merdok** [comment]
I mean you can just simply ignore the sections which are not for your device. The section are named by device type so it should be pretty clear which sections corresponds to your device.

**Comment by xazac** [comment]
> I mean you can just simply ignore the sections which are not for your device. The section are named by device type so it should be pretty clear which sections corresponds to your device.

Well, it's not that simple. Even if I don't select advanced features like "fan level" or "fan mode" they still appears into Home.app accessory. So I have about 10 controls for each air purifier but I just need 2-3 of them.

**Comment by merdok** [comment]
I am not quite sure what the issue is now... HOOBS ha nothing to do with how the accessories are displayed in the Home app. Not all air purifiers support all of the configuration options. In the end it depends on the device itself what is displayed. Air purifiers by the way do not have any properties called "fan level" or "fan mode". The have "modeControl"  and "fanLevelControl", and both are enabled per default, meaning if you specify nothing then they will be enabled.
