### ISSUE TITLE
Humidifier 3c warning and Fan Speed in Homekit

### ISSUE THREAD

**Issue by mrachm** [merdok/homebridge-miot#32]
I'm constantly getting "[5/26/2021, 9:05:45 PM] [homebridge-miot] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -254 exceeded minimum of 0. See https://git.io/JtMGR for more info."
I connected the Xiaomi humdifier 3c to homebridge-miot. In the HomeKit App the Fan Level isn't shown correctly. It always says the Speed is 0, but i can pull up the bar to set it to a level.
Start: ![IMG_4870](https://user-images.githubusercontent.com/72085875/119717738-fb7ac200-be66-11eb-9168-83e717295fa3.PNG)
While I press: ![IMG_4871](https://user-images.githubusercontent.com/72085875/119717749-003f7600-be67-11eb-8cc2-bc314329c424.PNG)
After release: ![IMG_4872](https://user-images.githubusercontent.com/72085875/119717765-059cc080-be67-11eb-8342-be855d5dbaf7.PNG)

**Comment by merdok** [comment]
Thanks for reporting. Could you post some debug homebridge log? Ideally it would be if you set the `deepDebugLog` property to true and post a short log before and after the warning appears, so that i can see exactly what property values are fetched from the device.

**Comment by mrachm** [comment]
[37m[5/27/2021, 12:18:51 AM] [39m[36m[miot][39m [Luftfilter Xiaomi] Did not specified. Got did: 361081581 from device!
[37m[5/27/2021, 12:18:51 AM] [39m[36m[miot][39m [Luftfilter Xiaomi] Doing device specific setup
[37m[5/27/2021, 12:18:51 AM] [39m[36m[miot][39m [Luftfilter Xiaomi] Doing initial properties fetch
[37m[5/27/2021, 12:18:51 AM] [39m[36m[miot][39m [Luftfilter Xiaomi] Device setup finished! Device ready, you can now control your device!
[37m[5/27/2021, 12:18:52 AM] [39m[36m[miot][39m [Luftfilter Xiaomi] Filter life level: 96%.
[37m[5/27/2021, 12:18:52 AM] [39m[36m[miot][39m [Luftfilter Xiaomi] Filter used time: 122 hours.

and then a few times per minute:
[5/27/2021, 12:25:02 AM] [homebridge-miot] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -245 exceeded minimum of 0. See https://git.io/JtMGR for more info.

**Comment by merdok** [comment]
You need to run homebridge in debug mode. Check this link on how to do that https://github.com/merdok/homebridge-miot#troubleshooting

Afterwards a lot more info should come including property values retrieved from the device. This is what i actually need.

**Comment by mrachm** [comment]
This is my config:
![Screenshot 2021-05-27 093555](https://user-images.githubusercontent.com/72085875/119784954-049f7980-becf-11eb-9051-197a30620874.png)
Thats my console:
![Screenshot 2021-05-27 093148](https://user-images.githubusercontent.com/72085875/119784982-0f5a0e80-becf-11eb-9e5c-e62fa3ce8ff0.png)
And this is what i found in the hombridge.log:
![Screenshot 2021-05-27 093417](https://user-images.githubusercontent.com/72085875/119785084-2993ec80-becf-11eb-9cd8-47f1bc15390f.png)

**Comment by merdok** [comment]
Thanks for the update, but unfortunately this is still not the debug log. This is the standard log output without the necessary information. I need to exactly see what value the device reports. 

Are you using HOOBS? Maybe there is a different way to enable the debug log.

Your config looks fine. You just need to figure out why homebridge does not want to start in debug log for you...

**Comment by mrachm** [comment]
No, I‘m using Homebridge with HomeAssistant Portainer. In the homebridge folder is an empty logs folder. Should it be there, is it maybe an „invisible“ file?

**Comment by mrachm** [comment]
Ok fixed it, here is the log: 
 [[39m
[90m  {[39m
[90m    "name": "power",[39m
[90m    "value": true[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "mode",[39m
[90m    "value": 2[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "favorite_speed",[39m
[90m    "value": 1117[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "child_lock",[39m
[90m    "value": false[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "alarm",[39m
[90m    "value": true[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "screen_brightness",[39m
[90m    "value": 8[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "pm25_density",[39m
[90m    "value": 1[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "filter_life_level",[39m
[90m    "value": 96[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "filter_used_time",[39m
[90m    "value": 135[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "fan_speed_rpm",[39m
[90m    "value": 1124[39m
[90m  }[39m
[90m][39m
[37m[5/27/2021, 1:00:03 PM] [39m[36m[miot][39m [90m[Luftfilter Xiaomi] Splitting properties into chunks. Number of chunks: 1. Chunk size: 12[39m
[37m[5/27/2021, 1:00:03 PM] [39m[36m[miot][39m [90m[Luftfilter Xiaomi] Chunks:  [[39m
[90m [[39m
[90m  "power",[39m
[90m  "mode",[39m
[90m  "favorite_speed",[39m
[90m  "child_lock",[39m
[90m  "alarm",[39m
[90m  "screen_brightness",[39m
[90m  "pm25_density",[39m
[90m  "filter_life_level",[39m
[90m  "filter_used_time",[39m
[90m  "fan_speed_rpm"[39m
[90m ][39m
[90m][39m
[37m[5/27/2021, 1:00:04 PM] [39m[36m[homebridge-miot][39m This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -263 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[37m[5/27/2021, 1:00:04 PM] [39m[90m[36m[homebridge-miot][39m[90m Error: [39m
[90m    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)[39m
[90m    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)[39m
[90m    at RotationSpeed.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)[39m
[90m    at AirPurifierAccessory.updateDeviceStatus (/homebridge/node_modules/homebridge-miot/lib/modules/airpurifier/AirPurifierAccessory.js:251:157)[39m
[90m    at MiotController.<anonymous> (/homebridge/node_modules/homebridge-miot/index.js:123:33)[39m
[90m    at MiotController.emit (events.js:376:20)[39m
[90m    at /homebridge/node_modules/homebridge-miot/lib/MiotController.js:102:14[39m
[37m[5/27/2021, 1:00:04 PM] [39m[36m[miot][39m [90m[Luftfilter Xiaomi] Device properties updated: [39m
[90m [[39m
[90m  {[39m
[90m    "name": "power",[39m
[90m    "value": true[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "mode",[39m
[90m    "value": 2[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "favorite_speed",[39m
[90m    "value": 1117[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "child_lock",[39m
[90m    "value": false[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "alarm",[39m
[90m    "value": true[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "screen_brightness",[39m
[90m    "value": 8[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "pm25_density",[39m
[90m    "value": 1[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "filter_life_level",[39m
[90m    "value": 96[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "filter_used_time",[39m
[90m    "value": 135[39m
[90m  },[39m
[90m  {[39m
[90m    "name": "fan_speed_rpm",[39m
[90m    "value": 1124[39m
[90m  }[39m
[90m][39m
[37m[5/27/2021, 1:00:08 PM] [39m[36m[miot][39m [90m[Luftfilter Xiaomi] Splitting properties into chunks. Number of chunks: 1. Chunk size: 12[39m
[37m[5/27/2021, 1:00:08 PM] [39m[36m[miot][39m [90m[Luftfilter Xiaomi] Chunks:  [[39m
[90m [[39m
[90m  "power",[39m
[90m  "mode",[39m
[90m  "favorite_speed",[39m
[90m  "child_lock",[39m
[90m  "alarm",[39m
[90m  "screen_brightness",[39m
[90m  "pm25_density",[39m
[90m  "filter_life_level",[39m
[90m  "filter_used_time",[39m
[90m  "fan_speed_rpm"[39m
[90m ][39m
[90m][39m

**Comment by merdok** [comment]
Thanks! That is what i needed. I will investigate this and try to provide a fix. Will let you know when the fix is ready.

**Comment by mrachm** [comment]
Thank you very much :)

**Comment by merdok** [comment]
The warning should now be fixed in version 0.9.0. Could you check that out and let me know?

**Comment by mrachm** [comment]
It is working now, thank you for your fast help.
