### ISSUE TITLE
Roborock E4 no mode switch or charger status

### ISSUE THREAD

**Issue by atol71** [merdok/homebridge-miot#324]
The Roborock E4 is not approving mode selection or showing charger status in Homebridge accessories -tab nor iPhone or iPad. Can start cleaning by switch.

Like Roborock S7 it should show if it is docked and accept mode change switch.

**Your config.json**
                {
                    "name": "Roborock E4",
                    "ip": "192.168.1.242",
                    "token": "foobar",
                    "deviceId": "foobar",
                    "model": "roborock.vacuum.a01",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "foo@bar.com",
                        "password": "secret",
                        "country": "de",
                        "forceMiCloud": true
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": true
                }

No debug log available.

**Comment by merdok** [comment]
Sorry i do not quite understand what is missing. Could you explain more better?
Your device supports modes and also reports charging status so it should work. There is even a dedicated class for your device already existing here: https://github.com/merdok/homebridge-miot/blob/main/lib/modules/robotcleaner/devices/roborock.vacuum.a01.js

**Comment by atol71** [comment]
Well I do not understand it either. With other plugin (https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum) everything works fine. I can see charging and turn it on. With this plugin, no charging info or different speed settings. Can turn on and vacuum can't turn off and command to return to dock. What I see on log is that it needs login to miio services a.k.a one needs to fill the login info into plugin.

**Comment by merdok** [comment]
Well, sorry i still do not quite understand what you mean. Anyway, the vacuum supports everything what is available in the miot protocol. 
The other plugin which you linked uses the old miio protocol because that vacuum is quite old and does not support miot natively. Xiaomi offers a emulation layer in the cloud to allow control old miio devices using the new miot protocol but as a downside for that not all features are supported. 
Does that explain the situation for you?
