### ISSUE TITLE
Error Occurring on Xiaomi Philips Zhirui Candle Light Bulb

### ISSUE THREAD

**Issue by achrovisual** [merdok/homebridge-miot#328]
**Describe the bug**
I added my Philips Zhirui candle light bulb via Mi Cloud discover. It successfully added the bulb as a **philips.light.candle** device. I knew that this bulb was supported because its part of the supported devices list, but an error occurs after setup stipulating that a method is not found. See screenshot below.

![image](https://user-images.githubusercontent.com/46639608/187926656-5e161b2a-f858-44aa-907d-e9329101c97b.png)

**Workaround**
I looked at the supported devices list again and saw that the bulb is categorized as **philips.light.candle2** and not **philips.light.candle** in the list. As a workaround, I manually changed the device model to **philips.light.candle2** in the config.

**Possible Action**
As Mi Cloud sees the bulb as a **philips.light.candle** device, may I suggest that the **philips.light.candle2** module be renamed to **philips.light.candle** to reflect what Mi Cloud reports.

Great plugin by the way! I appreciate your work.

**Comment by merdok** [comment]
That is exactly the thing here. There are two version of the device. The v2 has a device class implemented where it is marked as a micloud device. For your device on the other hand there is no device class hence the plugin does not know if it requires micloud or not, in that case it defaults to a local connection. You need to tell the plugin that it is a micloud device by specifying your micloud credentials and set the flag forceMiCloud to true in your config.json
