### ISSUE TITLE
Please add support for Xiaomi Air Purifier 4 Compact

### ISSUE THREAD

**Issue by engelbrechtd** [merdok/homebridge-miot#329]
**Device model**
zhimi.airp.cpa4

**Device name**
Xiaomi Air Purifier 4 Compact

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
Not working currently

**Comment by merdok** [comment]
Will add support in the next update.

**Comment by merdok** [comment]
The device is now added in version 1.3.0
