### ISSUE TITLE
Possible to support Gosund smart outlet CP5 (powerstrip)?

### ISSUE THREAD

**Issue by chungccm** [merdok/homebridge-miot#33]
Firstly, Thank you for making this homebridge plugin to let xiaomi product connect to Apple HomeKit

Is possible to add support for Gosund smart outlet (powerstrip) CP5? this product support MIot protocol?

![CP5_control](https://user-images.githubusercontent.com/84955393/119937470-6c33f280-bfbd-11eb-948b-6628a75109c3.jpg)
![CP5_image](https://user-images.githubusercontent.com/84955393/119937476-6dfdb600-bfbd-11eb-8571-df89253be3a6.jpg)

**Comment by merdok** [comment]
Hi,
could you tell me the exact model name? I had already a look into the official miot protocol device list and unfortunately I could not find any gosund device...

**Comment by chungccm** [comment]
the model should be "cuco.plug.cp5"

**Comment by merdok** [comment]
Thanks! Yes, this model indeed exists and it should be possible to add support for it👍 I will try to prepare support for that device in the next update! I will let you know when the update is ready so you can test it!

**Comment by merdok** [comment]
Support should now be added in version 0.9.0. Could you please try it out?

**Comment by chungccm** [comment]
@merdok, Thank you so much. I will try the new version on my home.

**Comment by danielkit83** [comment]
@merdok Just bought this smart outlet. But i don’t how to config the setting to manage 4 power buttons and usb button independently. Thanks

**Comment by merdok** [comment]
@danielkit83 what do you mean? There should be a switch for every power and usb outlet.

**Comment by danielkit83** [comment]
> @danielkit83 what do you mean? There should be a switch for every power and usb outlet.

Yes. After using the autodiscover to add the CP5, i can't see every power and usb outlet on Homekit. Do i need to adjust the configuration manually? Thanks
<img width="903" alt="Screenshot 2021-12-25 at 11 19 29 PM" src="https://user-images.githubusercontent.com/88359393/147388282-b48c083c-5132-492d-b736-0d2f7e681cc3.png">

**Comment by merdok** [comment]
No, you do not need to adjust anything. This should automatically be added, if it is not there then probably your device is not supported (maybe it is not the same model as in this issue). You need to check your device model and make sure it is supported. You can easily see that if you start homerbidge in debug mode.

**Comment by danielkit83** [comment]
> No, you do not need to adjust anything. This should automatically be added, if it is not there then probably your device is not supported (maybe it is not the same model as in this issue). You need to check your device model and make sure it is supported. You can easily see that if you start homerbidge in debug mode.

After checking the device model, it is cuco.plug.sp5. I can find this model in the supported list. But it is very strange, it is showing not supported device in the logs.

[26/12/2021, 09:54:19] [homebridge-miot] [工具櫃電排插] Got device configuration, initializing device with name: 工具櫃電排插
[26/12/2021, 09:54:19] [homebridge-miot] [工具櫃電排插] Device model known: cuco.plug.sp5! Creating device!
[26/12/2021, 09:54:19] [homebridge-miot] [工具櫃電排插] Initializing device properties
[26/12/2021, 09:54:19] [homebridge-miot] [工具櫃電排插] Initializing device actions
[26/12/2021, 09:54:19] [homebridge-miot] [工具櫃電排插] Device not supported! Using a generic device with limited properties! Consider requesting device support!

**Comment by merdok** [comment]
The `cuco.plug.sp5` was added to the supported devices but the plugin needs to be updated. I will probably do that later today, and after the update your device should work!

**Comment by danielkit83** [comment]
> The `cuco.plug.sp5` was added to the supported devices but the plugin needs to be updated. I will probably do that later today, and after the update your device should work!

Many thanks for you support
