### ISSUE TITLE
Please add support for viomi.health_pot.v1

### ISSUE THREAD

**Issue by PParit** [merdok/homebridge-miot#332]
**Device model**
viomi.health_pot.v1

**Device name**
Xiaomi smart electronic health kettle 1.5 L

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
None

**Comment by merdok** [comment]
That device has unfortunately a very limited functionality with the miot protocol. You can try to add it already now by specifing your micloud credentials and setting the `forceMiCloud` property to true.
