### ISSUE TITLE
TVOC unit calculation for Air Quality Monitor (cgllc.airmonitor.b1)

### ISSUE THREAD

**Issue by andrewtzn** [merdok/homebridge-miot#335]
The unit Apple Home uses for TVOC is µg/m3 and Xiaomi is using mg/m3. Could you please add a calculation of x1000 when TVOC is exposed to Homekit please?
Currently, Apple Home shows the TVOC value directly from source but with the incorrect unit. 
For example, source is 1.2 mg/m3, Apple Home shows 1.2 µg/m3. The correct value should be 1200 µg/m3.

> Yeah, battery is actually not part of the main service hence it also disappeared. Adding it manually causes it be a light sensor hence it will only display the reported value by the device. 
> 
> Yes, please open a new issue for the value calculations so i do not forget it :)

_Originally posted by @merdok in https://github.com/merdok/homebridge-miot/issues/334#issuecomment-1242901589_

Thank you!

**Comment by merdok** [comment]
Thanks for opening the issue. Do you know if that is true for every xiaomi device or is it just specific to yours?

**Comment by andrewtzn** [comment]
No problem!
Thanks for getting back to me!

I am not sure since I only have that air quality device from xiaomi. 
Side note, I can change unit on the air quality monitor itself, it's only for its display though. There are three options mg/m3., ppm and ppb. Changing them doesn't effect the value going to the plugin.

**Comment by merdok** [comment]
Should now be fixed in version 1.4.0

**Comment by andrewtzn** [comment]
Thank you!

**Comment by andrewtzn** [comment]
Quick update: it seems like Homebridge is showing the error below after the update, it seems like the maximum value is set at 9.999.
`[26/10/2022, 18:54:37] [homebridge-miot] This plugin generated a warning from the characteristic 'VOC Density': characteristic was supplied illegal value: number 1279.0000000000002 exceeded maximum of 9.999. See https://homebridge.io/w/JtMGR for more info.`
`[26/10/2022, 18:54:47] [homebridge-miot] This plugin generated a warning from the characteristic 'VOC Density': characteristic was supplied illegal value: number 1332.0000000000002 exceeded maximum of 9.999. See https://homebridge.io/w/JtMGR for more info.`
I checked the [cgllc.airmonitor.b1.js](https://github.com/merdok/homebridge-miot/blob/88e46935cafab2b64a9ccd6856405e2d8bbe3df8/lib/modules/airmonitor/devices/cgllc.airmonitor.b1.js) file. The `"valueRange":[0.005,9.999,0.001]` should be changed to a higher value?
Please correct me if I'm wrong.
If it needed to be updated, can you please change 9.999 to a higher value? something like this: `"valueRange":[0,65535,1]`
Please take a look at some discussions regarding the VOC value here: https://github.com/ebaauw/homebridge-hue/issues/1092 

Thank you again.
Please let me know if a new ticket is needed.

**Comment by merdok** [comment]
Oh, that is odd. Will have a look! Thanks!

**Comment by andrewtzn** [comment]
thanks again!!

**Comment by merdok** [comment]
Found the issue, will be fixed in a bug fix release in the next days.

**Comment by andrewtzn** [comment]
thank you merdok! you're the best!
