### ISSUE TITLE
iOS 16 Home App doesn't display Air Purifier fan switch types

### ISSUE THREAD

**Issue by jessejacksonafterpay** [merdok/homebridge-miot#338]
**Describe the bug**
The new Home app in iOS 16 isn't displaying the "type" of fan on each switch for the `zhimi.airp.vb2a` purifier. Instead, every switch is just labelled "Air Purifier" (my device name) rather than all of the different fan speeds.

**Expected behavior**
Each switch should have the fan speed or individual control name as a label.

**Your config.json**
```
{
    "devices": [
        {
            "name": "Air Purifier",
            "ip": "XXX",
            "token": "XXX",
            "deviceId": "XXX",
            "model": "zhimi.airp.vb2a",
            "pollingInterval": 60,
            "deepDebugLog": false,
            "micloud": {
                "timeout": 5000
            },
            "buzzerControl": false,
            "ledControl": false,
            "childLockControl": false,
            "modeControl": true,
            "fanLevelControl": true,
            "showTemperature": true
        }
    ],
    "platform": "miot"
}
```

**Debug log**
No log required to see the issue

**Screenshots**
![IMG_A029EF1BEF68-1](https://user-images.githubusercontent.com/85544300/190645702-fb625025-c979-4dae-abe0-3925450bcb5a.jpeg)

**Additional context**
None

**Comment by merdok** [comment]
Not a bug with the plugin, but has something to do with a change in iOS16. As far as i know there is nothing at this point that i can do...
More info https://github.com/homebridge/homebridge/issues/3210#issuecomment-1217735865
A temporary solution: https://github.com/merdok/homebridge-xiaomi-fan/issues/123#issuecomment-1239074853
