### ISSUE TITLE
Since iOS 16 all property buttons have same generic name

### ISSUE THREAD

**Issue by JoeUser999** [merdok/homebridge-miot#339]
**Describe the bug**
Since iOS 16 update all property buttons have the same generic label, i.e “switch”. This makes it impossible to discern the function. 

**Expected behavior**
The buttons should be labeled with the respective property name i.e. “Angle 30” so that the user knows which property the actual button / switch controls. 

**Your config.json*
        {
            "devices": [
                {
                    "name": "Purifier",
                    "ip": "1.2.3.4",
                    "token": "mytoken",
                    "deviceId": "mydeviceid",
                    "model": "zhimi.airpurifier.za1",
                    "prefsDir": "/homebridge/.xiaomiMiot",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "onlyMainService": true,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": false,
                    "modeControl": true,
                    "fanLevelControl": true,
                    "ioniserControl": true,
                    "screenControl": true
                },
                {
                    "name": "Fan Studio",
                    "ip": "1.2.3.5",
                    "token": "fantoken",
                    "deviceId": "fanid",
                    "model": "zhimi.fan.za5",
                    "prefsDir": "/homebridge/.xiaomiMiot",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "onlyMainService": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true,
                    "swingControl": true,
                    "moveControl": true,
                    "fanLevelControl": true,
                    "ioniserControl": true,
                    "offDelayControl": true,
                    "horizontalAngleButtons": [
                        30,
                        60,
                        90,
                        120
                    ]
                },
                {
                    "name": "Fan Living Room",
                    "ip": "1.2.3.6",
                    "token": "fan2token",
                    "deviceId": "fan2id",
                    "model": "zhimi.fan.za5",
                    "prefsDir": "/homebridge/.xiaomiMiot",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "onlyMainService": true,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true,
                    "swingControl": true,
                    "moveControl": true,
                    "fanLevelControl": true,
                    "ioniserControl": true,
                    "offDelayControl": true,
                    "horizontalAngleButtons": [
                        30,
                        60,
                        90,
                        120
                    ]
                }
            ],
            "platform": "miot"
        }

**Debug log**
./.

**Screenshots**
![A6864A06-712A-47D4-B08F-18052123BBAD](https://user-images.githubusercontent.com/1868000/190790424-8e8dc420-7518-4b2c-a417-ba632da020d2.png)

![AD5CB221-6804-406F-8A2C-90B3D5A52293](https://user-images.githubusercontent.com/1868000/190791740-baefcf93-0035-4665-856b-c088fb06ba81.png)

**Additional context**
Fine and as expected in Home and Eve app prior to iOS 16 update.

**Comment by merdok** [comment]
Please have a look at #338
