### ISSUE TITLE
led & buzzer buttons

### ISSUE THREAD

**Issue by adamrzanek** [merdok/homebridge-miot#34]
Po ostatniej aktualizacji nie mogę wyłączyć przycisków do ledów i buzzera w oczyszczaczu.

![3626C651-9C62-41D8-A07C-6E674A6D7112](https://user-images.githubusercontent.com/65444919/120225210-1bcec600-c245-11eb-8dc1-20f0a04495ec.png)

**Comment by merdok** [comment]
@adamrzanek Please check under "General device settings". Buzzer and LED control are universal on most devices so i decided to move it under a separate section. 

Sprawdź w sekcji "General device settings". Buzzer i LED ma większość urządzeń dlatego są one pod osobna sekcja dla wszystkich urządzeń.

**Comment by adamrzanek** [comment]
@merdok Still the same

![FC425F1A-C01E-43EE-9A40-F3565418AA02](https://user-images.githubusercontent.com/65444919/120226940-86353580-c248-11eb-8a80-2275aa285951.jpeg)

**Comment by merdok** [comment]
@adamrzanek can you post your config.json?

**Comment by adamrzanek** [comment]
@merdok yup i know - it’s not working from hb ui. But when i’m configuring config.json it’s all good.

**Comment by merdok** [comment]
Ah, i see the issue now! Will fix that in the next update (hopefully later today). Will let you know when the update is released.

**Comment by adamrzanek** [comment]
@merdok thanks. 

One more thing - if you want to create the scene you have to set 0% power to set unifier to auto mode.

I have a small feature request. Can air purifier slider show actual status of the automatic mode. For example other plugin that I’m using for testing. When air quality drops and it’s in auto mode the slider shows actual power of the fan. 

Sorry for bothering you :) but you’ve the best plugin as always :)

**Comment by merdok** [comment]
@adamrzanek Well i can understand your request, but i find it bad usability and confusing when one slider displays different things. At some point the user will maybe forget if this is currently favorite mode or just the fan speed... 
Maybe a better way would be to show multiply sliders where each of them show a different property?!

**Comment by adamrzanek** [comment]
@merdok nah, two different sliders would be even more confusing. I think air purifiers with native support act this way in hk. I think uswer know when they are in manual or auto mode.

**Comment by merdok** [comment]
I will have a look at it and see if i can improve that. It would be also interesting to see an air purifier with native homekit support, do you know any?

**Comment by adamrzanek** [comment]
Smartmi p1, vocolinc pureflow and soon meross will release theirs. I want to buy smartmi this year - it looks so nice

**Comment by merdok** [comment]
Thanks for the the devices. I will have a look at them and see how they integrate into homekit. This will definitely help me to improve the air purifier support 👍 

Also please could you check version 0.9.1 and see if the initial issue was fixed and let me know?

**Comment by adamrzanek** [comment]
Thanks!
