### ISSUE TITLE
Please add support for zhimi.airp.sa4

### ISSUE THREAD

**Issue by kyledh** [merdok/homebridge-miot#340]
**Device model**
zhimi.airp.sa4

**Device name**
Xiaomi Air Purifier 4 Max

**Does the device require a MiCloud connection?**
Do not know_

**Anything special about the device?**
No

https://home.miot-spec.com/spec/zhimi.airp.sa4

**Comment by merdok** [comment]
The device should already work right now maybe with limited support, I will add full support in the next update.

**Comment by merdok** [comment]
Version 1.4.0 is now out with support for the device!
