### ISSUE TITLE
Please add support for Xiaomi Robot Vacuum X10+

### ISSUE THREAD

**Issue by BuSHari** [merdok/homebridge-miot#342]
**Device model**
dreame.vacuum.p2114a (https://home.miot-spec.com/s/dreame-p2114a)

**Device name**
Xiaomi Robot Vacuum X10+

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
Will add support in the next update.

**Comment by BuSHari** [comment]
Hi @merdok any update?

**Comment by merdok** [comment]
As mentioned, full support will be added in the next update. I am currently working on one more critical change for the next update and I hope that I can release the new version in the next 2 weeks...

**Comment by satrik** [comment]
@merdok I have this model already running with your plugin. I can create a PR if you want.
Btw your 3 "p" typo `statusMopppingValue` took me ~20 minutes to find my issue 😂

**Comment by merdok** [comment]
@satrik 
I already have the class implemented locally, did not submit my changes yet...
Oh gosh... thanks for pointing on that typo😅 Will fix that too in the next update.

Sorry, for the long wait here... did some critical changes to the plugin and currently running 24/7 stability tests with my own devices. When everything goes well, I plan to release the update next week...

**Comment by merdok** [comment]
Version 1.4.0 is now out with support for the device!
