### ISSUE TITLE
Please add support for deerma.humidifier.jsq2q

### ISSUE THREAD

**Issue by kyledh** [merdok/homebridge-miot#343]
**Device model**
deerma.humidifier.jsq2q

**Device name**
Mijia Smart Anti-bacterial Humidifier 2

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
NO

https://home.miot-spec.com/spec/deerma.humidifier.jsq2g

**Comment by merdok** [comment]
Will add support in the next update. You can already add the device now and see if it works by auto detection.

**Comment by kyledh** [comment]
Yes, the device is now supported!

**Comment by merdok** [comment]
Should work now in version 1.4.0
