### ISSUE TITLE
Add type configuration for value range properties

### ISSUE THREAD

**Issue by St3ve32** [merdok/homebridge-miot#345]
Currently when there is a propertyControl for any value ranged property it is shown as a light-bulb. This allows convenient control of the property, but can be confusing when displaying in Homebridge UI or Home app. Example: fan-speed in an air purifier.

I think it would be nice to be able to set the type of the "device" in propertyControl.

**Comment by merdok** [comment]
Thanks, will try to think of something!

**Comment by merdok** [comment]
Now added in version 1.4.0

**Comment by St3ve32** [comment]
Hi, thank you so much for adding the feature, it looks great in the Home app.

However if I set the property to fan, it won't allow me to change the speed. In the log I get:

[10/27/2022, 1:07:35 PM] [homebridge-miot] [Mi Air Purifier 3C] Property custom-service:favorite-speed seems to have already the value: 300. Set not needed! Skipping...

If I change it back to lightbulb, it works fine. 

I tried to remove the air purifier and add it again, but it doesn't help.

Do you have any idea why this might be happening please?

**Comment by merdok** [comment]
Will have a look, might be a bug...

**Comment by merdok** [comment]
Found the issue will be fixed in a bug fixes release in the coming days!

**Comment by St3ve32** [comment]
Thank you, it's working perfectly now :))

**Comment by merdok** [comment]
perfect, thanks for the feedback!
