### ISSUE TITLE
Possible to support Light Brightness and Color temperature?

### ISSUE THREAD

**Issue by randomActual** [merdok/homebridge-miot#35]
Firstly, Thank you for making this homebridge plugin to let xiaomi product connect to Apple HomeKit

Is possible to add support for a light accessory, the model is leshi.light.wy0b01, I want to control the brightness and the color temperature.

Thank you very much.

**Comment by merdok** [comment]
Hi, 
yes that should be possible. In fact you can already control the power right now, it will be detected as a generic device. 
I will add proper lights accessory support in the next update and let you know when it is ready.

**Comment by randomActual** [comment]
Thank you so much  !!

**Comment by merdok** [comment]
Support for the light is now added in version 0.9.3. Could you please try it out and let me know if it works?

**Comment by randomActual** [comment]
@merdok , the light accessory works fine. Thank you so much !

**Comment by merdok** [comment]
Great! Thanks for the info!
