### ISSUE TITLE
Configuring chuangmi.camera.ipc019 

### ISSUE THREAD

**Issue by jun6lee** [merdok/homebridge-miot#351]
**Describe the idea or improvement**
A little help, I think I am merely struggling to configure it, or support is limited.

**Describe the solution you'd like**
HomeKit to see my device as a camera, and show the video stream.

**Additional context**
How do I look up what action / property elements I need?
And will the end result show me video on homekit without the Mi app?

                {
                    "name": "MiCam",
                    "ip": "192.168.1.21",
                    "token": "xxx",  //  have this, redacted
                    "deviceId": "xxx", //  have this, redacted
                    "model": "chuangmi.camera.ipc019",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "myuser",  //  have this, redacted
                        "password": "mypass", //  have this, redacted
                        "country": "i2",
                        "forceMiCloud": true
                    },
                    "customAccessory": true,
                    "onlyMainService": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": true,
                    "actionButtons": [
                        {
                            "action": "x",
                            "name": "y",
                            "params": [
                                "z"
                            ]
                        }
                    ],
                    "propertyControl": [
                        {
                            "property": "2.1",
                            "name": "camera-control",
                            "value": "on"
                        }
                    ]
                }
            ],
            "platform": "miot"
        }

**Comment by merdok** [comment]
Adding the camera video stream is not that easy... this would require to add a lot of new code and for that someone who is a video stream expert can only do it as I am lacking the knowledge. Hence for now there is no plan to add it...
