### ISSUE TITLE
damker.fan.p220 speed-level by 1% steps

### ISSUE THREAD

**Issue by waterchill** [merdok/homebridge-miot#352]
**Device model**
dmaker.fan.p220

**Device name**
Mi Smart Standing Fan (with Battery)

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
The fan is working, I'm missing one feature. In the Xiaomi App you can set the fan speed level by 1% from 0% to 100% in 1% steps. In homebridge is only possible set by 25% steps so only 4 steps. Possible to fix this?

Thank you

**Comment by waterchill** [comment]
Thank you. I noticed also that the switches in the home menu have always same label. There is no label like 30° turn left or something like that. You know what I mean?

**Comment by merdok** [comment]
This is an issue with ios16, and there is nothing I can do right now about it, you need to as a workaround manually rename them.

**Comment by merdok** [comment]
The bug should now be fixed in version 1.4.0
