### ISSUE TITLE
mjsxj09cm cam Streaming

### ISSUE THREAD

**Issue by Mendelyeev** [merdok/homebridge-miot#353]
I finally get my mjsxj09cm into HB. The current plug-in version inputs camera power on/off control and led. But not streaming. Is that possible enable video streaming?

**Comment by merdok** [comment]
Streaming would be possible but I cannot do it by myself since this is quite a complicated topic and I do not have the knowledge. Hence if someone with expertise could do that then it would be great!
For now unfortunately this is not possible.
