### ISSUE TITLE
Update monitoring vacuum

### ISSUE THREAD

**Issue by igorxmath** [merdok/homebridge-miot#356]
**Describe the idea or improvement**
I would like a modification of how monitoring information is exposed

**Describe the solution you'd like**
![4F39C540-EB70-42F1-B81B-9704909F3F29](https://user-images.githubusercontent.com/103374874/194734811-4babbbe1-8ae9-4c5d-9100-bcabeb8d3821.jpeg)
![4B9C7293-CEAB-46C0-9F7B-0DA294162AD3](https://user-images.githubusercontent.com/103374874/194734812-27c66617-11f2-4053-a069-c3e715a43643.jpeg)

I think the battery information and the others should be included in the switch with this charging icon

**Comment by merdok** [comment]
I think that is because of switch is actually a group and the other is not. I think you would need to split the group into separate tiles and then that would work. I think that this is not possible to show on the group icon.
