### ISSUE TITLE
All miot action buttons appear as the same name on IOS16

### ISSUE THREAD

**Issue by AvivWn** [merdok/homebridge-miot#361]
Hi,

Before updating to IOS16, all the action buttons for each device worked fine using homebridge. I could see and activate the deviled actions in the Home app.

After updating, multiple actions received the default device name.

![C4CF4CBA-EDD3-42BD-A3B4-F8F4149DC8BC_1_102_o](https://user-images.githubusercontent.com/33226470/195974550-af203f64-5691-4f3d-97a4-9fed4b7d8334.jpeg)

Here, the device name is "Deep White" and its actions have the same name.

Note that the accessories on homebridge page named correctly (each action with its name), and so in the Mac Home app.

**Comment by merdok** [comment]
Please read about it here:  https://github.com/merdok/homebridge-miot/issues/338#issuecomment-1249729272
Nothing that i can do but there is a temporary solution.
