### ISSUE TITLE
Device not supported - Xiaomi Mi Air Purifier 4 

### ISSUE THREAD

**Issue by c-le** [merdok/homebridge-miot#367]
Hello,

My Air Purifier 4 is not reconize.

>  [27/10/2022 19:46:39] [miot] Initializing miot platform...
>  [27/10/2022 19:46:39] [miot] Initializing devices
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Got device configuration, initializing device with name: Air Purifier
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Model known: Xiaomi Mi Air Purifier 4!
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Initializing device!
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Fetching device miot spec by model: Xiaomi Mi Air Purifier 4
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Initializing device services
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Device services: [
>    "generic-switch"
>  ]
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Initializing device properties
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Device properties: [
>    "generic:on"
>  ]
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Initializing device actions
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Device not supported! Using a generic device with limited properties! Consider requesting device support!
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Initializing accessory!
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Accessory successfully initialized!
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Registering 1 accessories!
>  [27/10/2022 19:46:39] [miot] [Air Purifier] Everything looks good! Initiating property polling!

My configuration:

>         {
>             "devices": [
>                 {
>                     "name": "Air Purifier",
>                     "ip": "xxx.xxx.xxx.xxx",
>                     "token": "*************************",
>                     "deviceId": "zhimi.airp.mb5",
>                     "model": "Xiaomi Mi Air Purifier 4",
>                     "pollingInterval": 10,
>                     "deepDebugLog": true,
>                     "customAccessory": false,
>                     "buzzerControl": true,
>                     "ledControl": true,
>                     "childLockControl": true,
>                     "modeControl": true,
>                     "fanLevelControl": true,
>                     "ioniserControl": true
>                 }
>             ],
>             "platform": "miot"
>         },

Can you help me plz ?

**Comment by merdok** [comment]
Your config contains wrong data. The `deviceId` and `model` are wrong, if you not sure what to put there, just simply remove them and the plugin will take care of finding out the correct data.
