### ISSUE TITLE
Xiaomi Smart Pet

### ISSUE THREAD

**Issue by rdaries** [merdok/homebridge-miot#370]
**Device model**
1. mmgg.pet_waterer.wi11
2. mmgg.feeder.fi1

**Device name**
1. Xiaomi Smart Pet Fountain
2. Xiaomi Smart Pet Food Feeder

**Does the device require a MiCloud connection?**
Do not know

**Comment by merdok** [comment]
Hi,

the devices should already work now. Just add them and expose whichever action you want using the `actionButtons` or `propertyControl`
