### ISSUE TITLE
Please add Video Doorbell support

### ISSUE THREAD

**Issue by panamera888** [merdok/homebridge-miot#377]
**madv.cateye.mowl3g**
_The unique model of your device, e.g zhimi.fan.za5._

**Xiaomi Smart Doorbell 3**
_The friendly name of the device used by the manufacturer, e.g. Smartmi Standing Fan 3._

**Does the device require a MiCloud connection?**
_Do not know_
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by panamera888** [comment]
I was hoping it could function as a doorbell for HomeKit but till now I'm getting no response in home kitWith best regards,On 2 Nov 2022, at 02:56, Marcin ***@***.***> wrote:﻿
What features do you expect to be available from the doorbell?

**Comment by merdok** [comment]
Well if you expect to see the camera video stream then that will not be possible as this requires some work to implement and I am not so familiar with it.
But depending on what your doorbell exposes it should be possible to add some features. 
Can you post the homebridge debug log so we can have a look what is not working right now?
