### ISSUE TITLE
Integration of devices from Dreamehome app

### ISSUE THREAD

**Issue by mongrel15** [merdok/homebridge-miot#378]
**Describe the idea or improvement**
The idea is to integrate the robot vacuum from the Dreamehome app into HomeKit with this plugin.

**Describe the solution you'd like**
Due to the unsupported "live camera" function for the Dreame L10s Ultra in the Xiaomi Home app, I currently use the Dreamehome app for the robot vacuum.

So far, the plugin refers to devices from MiCloud (with the device token). Is there a way to integrate robot vacuums that work with the Dreamehome app into HomeKit with this Homebridge plugin?

The Dreame L10s Ultra is already listed as the most supported device (https://github.com/merdok/homebridge-miot/blob/main/supported_devices.md) but apparently only when connected via the Xiaomi Home app.

**Comment by merdok** [comment]
As long as you have the token of the device and the ip then it should work. I think the biggest problem here is on how to extract the token from the Dreamehome app...

**Comment by mongrel15** [comment]
The problem with this is that the device token does not stay the same after the vacuum cleaner is reset. 
I have already configured the L10s once using the Xiaomi app and then read out the valid token. After that, when I reset the device to be able to include it in the Dreamehome, the token changes. Unfortunately, simultaneous operation with both apps is not possible.

**Comment by merdok** [comment]
Unfortunately, this is not something that i can fix or change. We would need to retrieve the token from the app but as far as i know this is not possible currently.

**Comment by mongrel15** [comment]
I tried again with method 5 a and b without success -> https://github.com/merdok/homebridge-miot/blob/main/obtain_token.md
I get a token for each method, but no direct communication with the robot via the plugin works.

My request to the Dreame support if the function of the "live camera" for the Dreame L10s Ultra will be available in one of the upcoming versions of the Xiaomi Home App was denied.
So unfortunately, you currently have to decide whether live camera function or integration into HomeKit. 
Perhaps Apple will eventually integrate the category of vacuum robots in HomeKit and the problem fixes itself ;)

Thanks for your answer anyway.

**Comment by mongrel15** [comment]
I tried again with method 5 a and b without success -> https://github.com/merdok/homebridge-miot/blob/main/obtain_token.md
I get a token for each method, but no direct communication with the robot via the plugin works.

My request to the Dreame support if the function of the "live camera" for the Dreame L10s Ultra will be available in one of the upcoming versions of the Xiaomi Home App was denied.
So unfortunately, you currently have to decide whether live camera function or integration into HomeKit. 
Perhaps Apple will eventually integrate the category of vacuum robots in HomeKit and the problem fixes itself ;)

Thanks for your answer anyway.

**Comment by merdok** [comment]
Yeah, well there is nothing that can be done currently. Maybe the dreamehome app uses a different protocol to communicate with the device...
