### ISSUE TITLE
Camera chuangmi.camera.029a02 Video streaming

### ISSUE THREAD

**Issue by Mendelyeev** [merdok/homebridge-miot#379]
I managed to add the camera, but only the options to turn it on or the led appear. But the video does not appears. Is that any extra config to enabling streaming?

Thanks for this wonderful job!

**Comment by merdok** [comment]
Hi,
i have already briefly explained here why at this point it is not possible: https://github.com/merdok/homebridge-miot/issues/365#issuecomment-1288211712
Maybe if someone has time to implement that then it would be nice, other then that i might someday come back to it and try again...
