### ISSUE TITLE
Labels for switches in HomeBridge

### ISSUE THREAD

**Issue by JonoHaysom** [merdok/homebridge-miot#381]
Hi,

in iOS 16 (and maybe it was the case earlier) there is no way to see what a toggle, switch or slider will do. Is there any way to fix this? This is confusing when trying to use air purifiers etc. 
![IMG_1084](https://user-images.githubusercontent.com/8393299/200114616-5efaba49-c922-4d1a-a5e7-40870912dc20.PNG)
![IMG_1085](https://user-images.githubusercontent.com/8393299/200114620-e7dfc594-47a0-440a-8529-3d43f37b1d2d.PNG)

**Comment by merdok** [comment]
Unfortunately a known issues which was introduced with ios16 in the home app. More info here: https://github.com/merdok/homebridge-miot/issues/338#issuecomment-1249729272
