### ISSUE TITLE
Disable light on Mi Air Purifier C3

### ISSUE THREAD

**Issue by Stetocasa** [merdok/homebridge-miot#383]
I not found any possibility to remove the light of the Air Purifier screen
![image](https://user-images.githubusercontent.com/70729310/200123802-ea32929b-93f5-46dc-865c-478aa7ace172.jpeg)

**Comment by merdok** [comment]
I am not quite sure what you mean, but is it `screenControl` what you are looking for? Just set that to true in your config.json.
