### ISSUE TITLE
Descriptive service names

### ISSUE THREAD

**Issue by Avamander** [merdok/homebridge-miot#384]
**Describe the idea or improvement**
Additional services should have names accepted by HomeKit. Currently I can see that the additional services (such as "Fan Speed - Level 1") do have descriptive names, if the name is manually cleared and retyped without the dash `-` one can save them, but HomeKit/Home currently defaults to the device's name. That is not very usable.

**Describe the solution you'd like**
Additional services such as ionizer control, fan levels, child lock etc. should have names accepted by HomeKit that are descriptive of the functionality. Renaming things manually they reset sometimes, so it's not sustainable for even two fans (2 * 7 = 14 toggles to rename).

**Comment by merdok** [comment]
Unfortunately a known issue which was introduced with ios16 in the home app. More info here: https://github.com/merdok/homebridge-miot/issues/338#issuecomment-1249729272

**Comment by Avamander** [comment]
Dang, good to know, thanks.
