### ISSUE TITLE
Possible to Support Projector as TV/STB/Streaming Device?

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#387]
**Device model**
fengmi.projector.fm05

**Device name**
Xiaomi Smart Projector (Fengmi Young)

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
No

I’m not sure if this is even possible but I don’t see any plugin are able to expose a Xiaomi projector as a television/set top box/streaming device to HomeKit. Currently relying on Siri Shortcuts but its unreliable and breaks everytime there’s an iOS update.

![F40A217A-9DBA-43C2-A8F1-E45CB79C9E39](https://user-images.githubusercontent.com/66505845/200322714-77db1a22-3a85-4819-a06f-eede93c665ae.jpeg)

**Comment by merdok** [comment]
It should actually work.
You can already do it now, just add the device into the plugin and it should be detected automatically.
Although it will be detected as a generic device, you can use the actionButtons and propertyControl to expose to HomeKit whatever you need and be able to control it.

**Comment by merdok** [comment]
The plugin does not supports TV accessories yet so that is an expected behavior, but it should not cause any issues. You can post the homebridge debug so i can have a look what it dos not work, it might be that it requires a micloud connection...

**Comment by merdok** [comment]
The log is not enough as I do not see if the property sync is working, meaning if the plugin could connect to the device. You need to post some more log.

**Comment by merdok** [comment]
Yeah, it seems that it only has a turn off action, so I guess that it goes in some kind of a deep sleep when in standby hence it is not possible to turn it on.
But besides that it looks good I guess.

**Comment by merdok** [comment]
It might be that the device uses wake on lan to wake up. You can try to send a magic packet using generic wake on lan tools to the MAC address of your device to test it out.
In the miot spec there is nothing to turn it on hence it will never work over the miot protocol. It also makes sense since the device only can listen to protocol calls when it is turned on and running.

**Comment by merdok** [comment]
Yeah, not really sure what it means. I mean to execute an action the plugin needs to be connected to the device and you say that the device is not available in the network as long as it is turned off... so not really sure how the app does the turn on then.
