### ISSUE TITLE
Problem with my smartmi fan heater 

### ISSUE THREAD

**Issue by Reddyzinho** [merdok/homebridge-miot#388]
**Describe the bug**
unfortunately after update my smartlife fan heater stop working. The IP that is returned  from the plugin is different the one is registered in the router. Is strange. Inhale tried both but non works ;( 

the model is this: zhimi.heater.na1

**Your config.json**

devices": [
                {
                    "name": "Smartmi Heater 1 ",
                    "ip": "192.168.1.218", (in my router it end at 107) 
                    "token": "xxxxxxxxxxxxx",
                    "deviceId": "xxxxxxxx",
                    "model": "zhimi.heater.na1",
                    "pollingInterval": 7,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "xxxxxxx@gmail.com",
                        "password": "xxxxxxxxx",
                        "country": "tw",
                        "forceMiCloud": true,
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": true,
                    "offDelayControl": true,
                    "heatLevelControl": true,
                    "showTemperature": true
                },
                {

Any ideia what should be ? ;((

**Comment by merdok** [comment]
Hi, 
then you should simply change the ip adress to the one which you know is correct. Sometimes the Micloud has outdated data and it retrieves the wrong one due to that.

**Comment by Reddyzinho** [comment]
Thanks for the reply but unfortunately changing the IP address doesn’t work ;( any other idea ? Atentamente,Tiago CunhaNo dia 12/11/2022, às 10:29, Marcin ***@***.***> escreveu:﻿
Hi,
then you should simply change the ip adress to the one which you know is correct. Sometimes the Micloud has outdated data and it retrieves the wrong one due to that.

**Comment by merdok** [comment]
Probably the token is also invalid in that case.

**Comment by Reddyzinho** [comment]
Anyway I get obtain tento-lhe without the miio plugin ? Because the plugin is giving me one different that I have previously updating. The old doesn’t work either :( Atentamente,Tiago CunhaNo dia 12/11/2022, às 18:15, Marcin ***@***.***> escreveu:﻿
Probably the token is also invalid in that case.

**Comment by merdok** [comment]
Either your token or your ip address has changed, you need to make sure that they are correct. As already mentioned the ip and token in the micloud are not always up to date.
