### ISSUE TITLE
Xiaomi Smart Home Hub 3 ( lumi.gateway.mgl03 ) Question

### ISSUE THREAD

**Issue by toma9777** [merdok/homebridge-miot#389]
Hello,

this is code:

                    "propertyControl": [
                        {
                            "property": "3.1",
                            "name": "Basic Arming",
                            "value": 0
                        },
                        {
                            "property": "3.1",
                            "name": "Home Arming",
                            "value": 1
                        }
                    ]

I want to ask you if it is possible to make one switch ON/OFF:
- ON - to be "Home Arming"
- OFF - to be "Basic Arming"
![IMG_0131](https://user-images.githubusercontent.com/76265066/201439788-087ce319-dc8b-4b01-8235-eb3105e282e4.jpeg)

**Comment by merdok** [comment]
Hi,
there was a very similar discussion about that here: https://github.com/merdok/homebridge-miot/issues/320#issuecomment-1212887360
Unfortunately it is not that easy to solve when you have more then 2 values as the switch can only show 1 of 2 values, so what would happen if you set a third value which the switch does not support?
For now, this is the best way which we currently have for customization. Hopefully Apple will add new kind of accessories in the future which will enable such things to be possible...
