### ISSUE TITLE
Mi Bedside Lamp (yeelink.light.bslamp1) cannot switch off in Home app

### ISSUE THREAD

**Issue by scegg** [merdok/homebridge-miot#390]
**Describe the bug**
In iOS Home app, Mi Bedside Lamp can switch on and modify brightness and color, but not able to switch off.
The Mi Bedside Lamp shows 4 controls in Home App: Brightness, Switch A, Switch B and color selection. It seems that Switch A and B are for different working mode. When either A or B is on, the light is on. When switching one to on, another is switched off automatically. BUT, when switch one from on to off, it reverts to on automatically. So there is no way to turn off the light in Home app.

**Expected behavior**
The both switches can be set to off.

**Your config.json**
                {
                    "name": "Mi Bedside Lamp",
                    "ip": "xxx.xxx.xxx.xxx",
                    "token": "83f3b254649cf2e900f26ec2df7ecf2f",
                    "deviceId": "88347109",
                    "model": "yeelink.light.bslamp1",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "<myphone>",
                        "password": "<mypassword>",
                        "country": "cn"
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                }

**Comment by merdok** [comment]
I am not sure what you exactly mean but you have to tap on the brightness slider to turn off the lamp...
