### ISSUE TITLE
Add additional temperature and humidity sensor for Air Conditioner Companion

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#392]
The air conditioner itself does not have a temperature and humidity sensor. Can you add an external temperature and humidity sensor, such as through mqtt, etc.
In addition, can you modify the wind speed to the style in the picture.
Thank you for your work!
![98EE34E1-5EA8-4E6F-84F6-71F00607CBCF](https://user-images.githubusercontent.com/37586254/202852922-ce383620-1f9d-4aa2-95d0-b88d34f5b6d3.png)

**Comment by merdok** [comment]
Hi,
unfortunately it is not possible to add external temperature and humidity sensors, and i do not plan to add as this plugin is about the miot protocol. You can easily add such sensors to Home using other plugins and the use automations to combine them. 

What style do you mean, and what device are you using?
