### ISSUE TITLE
Exclude the optional sensor

### ISSUE THREAD

**Issue by alexanderek** [merdok/homebridge-miot#395]
**Describe the idea or improvement**
Can the temperature sensor be excluded from the device? 

**Describe the solution you'd like**
The Xiami humidifier, for example, has a temperature and humidity sensor, which I would like to remove from the HomeKit.

**Comment by merdok** [comment]
Currently no, if a device supports  temperature and humidity reporting then it will automatically create the accessories for that.
Why would you like to disable that?

**Comment by alexanderek** [comment]
@merdok 
The values are not correct, compared to the external sensor.

**Comment by merdok** [comment]
I mean, I am not quite sure why the humidifier would report incorrect values? Maybe a different place of measurement?

**Comment by alexanderek** [comment]
I do not know, but the values are very different from the external sensor, I think that the built-in sensor is not accurate in such devices, and in automations should not be used.

**Comment by merdok** [comment]
Understood, i will think of adding a functionality to disable those, but it might take a while...

**Comment by diogomontenegro** [comment]
This feature would also be very useful for Mi Heater Temperature Sensor...
Thanks and keep up this great work!

**Comment by romacv** [comment]
You can exclude incorrect values from accessory via home app accessory settings.
![IMG_7174](https://user-images.githubusercontent.com/3684453/224542857-9906dfb5-621b-4b7e-bf46-8525c9e1fa4c.jpg)

**Comment by merdok** [comment]
Some of the auto created sensors can now be excluded in 1.6.0
