### ISSUE TITLE
Is it possible to support xiaomi bluetooth and zigbee devices?

### ISSUE THREAD

**Issue by randomActual** [merdok/homebridge-miot#40]
My home have some xiaomi devices, they use zigbee and bluetooth protocol , such as isa.magnet.dw2hl, lumi.plug.v1 ....etc.
they are connected to the lumi.gateway.mgl03 Gateway, is it possible to support in the future?

**Comment by merdok** [comment]
Hi,

right now the devices which does not have a direct connection to the network cannot be supported. I am not sure if that will change in the future. I will investigate possibilities to support them but I cannot promise anything at this point...
