### ISSUE TITLE
Report Humidity as Humidity, not as Lux

### ISSUE THREAD

**Issue by wernerik** [merdok/homebridge-miot#403]
**Describe the idea or improvement**
Hi! I am using zhimi.airp.vb4 to control my Xiaomi Air Purifier. It works fine, but I have troubles getting humidity readings akin to the temperature readings. I have managed to add the accessory, but it is reported as Lux. I know this is a workaround used in the plugin, however Homekit has nice support for humidity readings now and I would like to see averages across my other devices in other rooms.

Thanks a lot for considering this!

**Describe the solution you'd like**
Introduce a type "Humidity" for accessories
**Additional context**

**Comment by merdok** [comment]
Hi,
you would need to post your config and some screenshoots. Your device is supported and should automatically create a temperature and humidity sensor.
