### ISSUE TITLE
Slider to adjust speed for Robot Cleaner

### ISSUE THREAD

**Issue by webjib** [merdok/homebridge-miot#41]
Hello. First, thank you very much for this wonderful plugin, it works perfectly with my Dream D9!

Do you think it would be possible to implement a slider instead of different switches, in order to control the Suction Mode? I know that another plugin [https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/HEAD/models/speedmodes.js](url) can do that. For example: OFF /  0-25% = Quiet / 25-50% = Normal / 50-75% = Strong / 75-100% = Turbo.

Obviously, it should be an option only, because people could prefer the switches.

EDIT: event better, is it possible to have steps in the slider?

**Comment by merdok** [comment]
In theory it would be certainly possible to show a slider to control the modes, but I would first need to come up with some universal solution for that, since there are different vacuums with different modes. But anyway I will check it out!

**Comment by webjib** [comment]
Great! You're right, this needs to be adapted to each sort of robot cleaner. If you need help, don't hesitate :)

**Comment by merdok** [comment]
I am actually asking myself what is the advantage of having this as a slider? I mean i know that the other plugin has it as a slider, but what is the advantage? I change the mode maybe only once/twice a year when something unusual happen like something falls down and causes dirt so i maybe want to use the Turbo mode for that. The rest of the year i use normal. 
This is generally not something which you change that often so not sure why show it as a slider which has literally no meaning?

**Comment by webjib** [comment]
Actually, I need to set a different "speed" according to wether I'm home or not, wether my home is quite clean or not... Because speed means also noise, sometime I want the quiet mode, sometimes the turbo mode. The switches are working fine, but it's quite disturbing when you have multiple switches grouped (not your fault, I'm not huge fan of Homekit presentation). The reason is also that each mode is exclusive to the others.

Maybe there's another solution : 1 switch for on/off, and a slider for the Mode (instead of 4 switches for the Mode)?

**Comment by merdok** [comment]
Need to think about it... You are right that a slider is more compact then 4/5 switches, but on the other hand if you represent a simple value in a percentage slider then you will lose information about what value you are selecting. Apple is really missing a multi selection switch in HomeKit which would solve the issue, not sure why they do not provide such item...

**Comment by webjib** [comment]
Completely agree! No solution is perfect, my point was to give user a custom setting, so that the plugin fits his needs. Actually, the only multiple states switch I know, is for Alarm. But I'm not sure you can define the labels...

![a2d7c65cfde556af3eae227afa57ef154d8d7663](https://user-images.githubusercontent.com/33569886/121481697-b01af480-c9cc-11eb-8572-b6124dcab102.jpeg)

**Comment by merdok** [comment]
I think the labels of the security system cannot be changed, besides that displaying modes as an slant would be even more confusing I think😅

Anyway, I plan to allow users to configure any property of the device similar like now the actions can now be configured. So ideally the goal is that you can say in the future that you want to have the mode property displayed as slider. In the end this should allow users to completely customize how the accessory will look like as their needs are.
This is rather complicated to implement so it will still take some time till I can provide that.
I think this solution will make all users happy🙂 Not sure if I make a custom solution for vacuums till then...

**Comment by merdok** [comment]
Sorry it took quite long. I decided not to add a slider for adjusting speed of a vacuum cleaner, since there is only a handful of older devices which actually allow that. I think the best way is to offer the mode switches since you do not do that often. If a slider is still required, you can add it manually now since version 1.0.0 as a `propertyControl`.
