### ISSUE TITLE
Add control of a background light on Yeelight Arwen

### ISSUE THREAD

**Issue by mishablokhin** [merdok/homebridge-miot#415]
Please add support to control background lightning on yeelink.light.ceilc (Yeelight Arwen). For now plugin can control only brightness and light modes (day and night)

**Comment by merdok** [comment]
Thanks for the feedback. Will have a look at it!

**Comment by mishablokhin** [comment]
> Thanks for the feedback. Will have a look at it!

Thanks a lot! For now it is a best plugin for Xiaomi devices. For example, with Yeelighter my Yeelight Arwen lost connection several times a day. With Homebridge Miot it works flawlessly. If you could add support for backgroud lightning, it will be awesome! Thanks for your work.

**Comment by merdok** [comment]
Should now be available in 1.5.0
