### ISSUE TITLE
Support for Xiaomi Smart Doorbell 3

### ISSUE THREAD

**Issue by iLex93** [merdok/homebridge-miot#416]
**Device model** - madv.cateye.mowl3g
_The unique model of your device, e.g zhimi.fan.za5._

**Device name** - Xiaomi Smart Doorbell 3
_The friendly name of the device used by the manufacturer, e.g. Smartmi Standing Fan 3._

**Does the device require a MiCloud connection?** - Do not know
_Yes/No/Do not know_
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?** - The plugin finds the device, but fails to poll and logs "[Smart Doorbell 3] Device not supported! Using a generic device with limited properties! Consider requesting device support!"
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
What do you expect from the doorbell to work? Video will not be possible.

**Comment by iLex93** [comment]
Hi @merdok ! Thanks for your answer. Would be great to have at least notification that someone at the door, if video is not possible.

**Comment by merdok** [comment]
As far as I can see, it should be possible to expose a sensor which would trigger on the camera motion sensor detection. I can try to add that.
