### ISSUE TITLE
Property screen:on does not exist on leshow.humidifier.jsq1

### ISSUE THREAD

**Issue by jackscorpse** [merdok/homebridge-miot#418]
Added new property "screen:on" from the latest firmware update (2.2.6.1236), but the plugin skips property when loading with an error that this property does not exist on this device. 
With property "screen:brightness" same issue.

**Comment by jackscorpse** [comment]
I figured out the issue, the new property is not yet in the file for this device. I believe that it will be added in the next plugin updates.

**Comment by merdok** [comment]
Yes, you are right! They updated the spec with this new features. Will update the spec in the next update.
