### ISSUE TITLE
Possible to give Names which Mode it is?

### ISSUE THREAD

**Issue by tommyMX** [merdok/homebridge-miot#419]
Hi,

is it possible to give it names from the switches in HomeKit?

Thank you
![IMG_1495](https://user-images.githubusercontent.com/36209886/211767263-b6bdff3b-8f0e-4366-8059-2d2c9d738c29.PNG)

**Comment by merdok** [comment]
This is very likely a bug in ios16.
Please read about it here:  https://github.com/merdok/homebridge-miot/issues/338#issuecomment-1249729272
Nothing that i can do but there is a temporary solution.
