### ISSUE TITLE
Support for Mi 360° Home Security Camera 2K Pro

### ISSUE THREAD

**Issue by SUL3** [merdok/homebridge-miot#420]
**Device model**
chuangmi.camera.021a04

**Device name**
Mi 360° Home Security Camera 2K Pro

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
I found more info with specs [here](https://home.miot-spec.com/spec/chuangmi.camera.021a04)

**Comment by merdok** [comment]
What do you expect from the camera to work? Video will not be possible currently

**Comment by merdok** [comment]
In general it would be possible, but i am not an expert about streams and especially including them into home as this is rather complex. So if somebody has time in the future and can take this over then it would be good!

**Comment by FinocchiaroGR** [comment]
@merdok Not sure if this might help somehow, but there is a guy on GitHub that knows how to get the video stream of miot cameras that have stream for google in their specs. I leave the link here, in case someone knows how to translate it to here: https://github.com/al-one/hass-xiaomi-miot/issues/166

**Comment by merdok** [comment]
Thanks, I will have a look at this and see if I can use that as a base.

**Comment by khmyznikov** [comment]
@merdok @SUL3 any luck?

**Comment by merdok** [comment]
Not yet, I did not have the time to have a look...
