### ISSUE TITLE
New device support  Aqara Door Lock N200 / lumi.lock.bzacn1

### ISSUE THREAD

**Issue by imeSven** [merdok/homebridge-miot#421]
**Device model**
lumi.lock.bzacn1

**Device name**
Aqara Door Lock N200

**Does the device require a MiCloud connection?**
Yes ?
Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
i wish i could add the Ring Button to homebridge, has a doorbell button and i want to put it inside homekit.
thank you!

i have the gateway  v3 that appears inside miot plugin but the door child does not.

**Comment by merdok** [comment]
Seems like the device does not send any events for pressing a button. Do you mean the ring button?

**Comment by imeSven** [comment]
> Seems like the device does not send any events for pressing a button. Do you mean the ring button?

Yes , the ring button 🛎️

**Comment by merdok** [comment]
I will have a look it I can find something out but at least from the specs it does not look good...

**Comment by merdok** [comment]
It does not seems that the devices supports reporting that, so i unfortunately must say that this would not be possible. There are just a couple of configuration properties exposed over the miot protocol.
