### ISSUE TITLE
Autogenerate from metadata?

### ISSUE THREAD

**Issue by filipef101** [merdok/homebridge-miot#424]
**Describe the idea or improvement**
Autogenerate device configs from metadata

**Describe the solution you'd like**
Would it be possible to autogenerate configs from metadata or is there some limitation?
I would imagine a list of actions, methods, property, propmonitor, let the user select what to enable

**Additional context**
 I'm noticing that mantaining a config per device is a bit unmantainable(?) so this could be a friendly alternative

**Comment by merdok** [comment]
It is already being done automatically. The device specific files are not really needed, but some devices have special handling or different values for properties so this is more or less handled there.
