### ISSUE TITLE
Yeelight Lightstrip Plus

### ISSUE THREAD

**Issue by tosziro** [merdok/homebridge-miot#425]
**Device model**
Yeelight Lightstrip Plus

**Device name**
yeelink.light.strip2

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
"Poll failed 4 times in a row! Stopping polling and trying to reconnect! Reason: Error: Call to device timed out"

**Comment by merdok** [comment]
If you say that this device requires a MiCloud connection then you need to specify your MiCloud credential sin the config.json and set the `forceMiCloud` property to `true`. That should work for your device.

**Comment by tosziro** [comment]
I tried to force MiCloud but it's still not working. I'm not sure if it require MiCloud, but I guess so. Some other variant of Lightstrip Plus (yeelink.light.strip2) as I saw required that.

**Comment by merdok** [comment]
What error do you get when you force it to use MiCloud?
