### ISSUE TITLE
Add room cleaning support for dreame.vacuum.mc1808

### ISSUE THREAD

**Issue by mivalme** [merdok/homebridge-miot#426]
Actually you support the dreame.vacuum.mc1808 and it is working well, but doesn't have an option for a custom cleaning (rooms, or zones). I use this vacuum in my home, and through the Xiaomi app you can select the zone that you want to clean. I attach here a screenshot.

As you can see in the image, you can check the room that you wanna clean, so I wanna have the option to do it through homebridge.

<img src="https://user-images.githubusercontent.com/33386326/214625542-d809102f-a8c0-4768-b449-bc701e39dba1.jpeg" height="800" />

**Comment by merdok** [comment]
Hi,
did you have a look at the room cleaning guide under docs?
There is a guide for dreame vacuum s.

**Comment by mivalme** [comment]
Hi, thanks for your answer
Yes, I have already checked it, but those configs didn't work for my vacuum, also I check the `dreame.vacuum.mc1808.js` file and I watch that the called action in the docs is not listed for that model.

**Comment by merdok** [comment]
Yeah, well some actions you need to adapt to your specific use case since those are not always the same but at least similar. Doing something generic which works on every device is quite difficult.
