### ISSUE TITLE
How to add lumi.curtain.hmcn02 (Xiaomi BLE Curtain Driver E1)

### ISSUE THREAD

**Issue by joyzainzy** [merdok/homebridge-miot#428]
How to add lumi.curtain.hmcn02 (Xiaomi BLE Curtain Driver E1)

**Comment by merdok** [comment]
Since it seems that this is a BLE device, you would need to add it through a gateway. You need to specify the ip and token of your gateway, and the deviceid and model from your device, that should make it work.

**Comment by mrmaximas** [comment]
> Since it seems that this is a BLE device, you would need to add it through a gateway. You need to specify the ip and token of your gateway, and the deviceid and model from your device, that should make it work.

what about reading from Mi Flora / HHCC sensors via Xiaomi Smart Home Gateway 3 gateway?

**Comment by merdok** [comment]
Seems to work, but you would need to configure yourself the properties manually since there is no plant monitor module yet.

**Comment by mrmaximas** [comment]
> Seems to work, but you would need to configure yourself the properties manually since there is no plant monitor module yet.
thanks
it is possible to add?
https://miot-spec.org/miot-spec-v2/spec/service?type=urn:miot-spec-v2:service:plant-monitor:0000784B

{"type":"urn:miot-spec-v2:service:plant-monitor:0000784B","description":"Plant Monitor","optional-properties":["urn:miot-spec-v2:property:status:00000007","urn:miot-spec-v2:property:fault:00000009","urn:miot-spec-v2:property:temperature:00000020","urn:miot-spec-v2:property:relative-humidity:0000000C","urn:miot-spec-v2:property:soil-ec:00000084","urn:miot-spec-v2:property:illumination:0000004E"]}

**Comment by merdok** [comment]
If there is no battery level in the spec then it means that the device does not support that. You should try to use propertyControl and propertyMonitor to expose which data you want to see.

**Comment by mrmaximas** [comment]
this device definitely reports the battery status via bluetooth.
now i'm using this plugin https://github.com/oretman/homebridge-mi-flora-care but my sensors are too far away from the my ble dongle. it's enough for me to get data through the mi cloud a couple of times a day.
[2/28/2023, 10:02:43 AM] [Asparagus L] Lux: 509, Temperature: 26.5, Moisture: 31, Fertility: 674
[2/28/2023, 10:02:43 AM] [Asparagus L] Firmware: 3.3.5, Battery level: 100

**Comment by merdok** [comment]
It might be that it reports battery but not using the miot spec!

**Comment by mrmaximas** [comment]
strange things
it's my config for plant monitor
                              {
                    "name": "MIOT Monstera",
                    "ip": "ххххх",
                    "token": "ххххх",
                    "deviceId": "blt.3.1bl3btnhc5g00",
                    "model": "hhcc.plantmonitor.v1",
                    "pollingInterval": 600,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "ххххх",
                        "password": "ххххх",
                        "country": "cn",
                        "forceMiCloud": true
                    },
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "propertyMonitor": [
                        {
                            "property": "plant-monitor:relative-humidity",
                            "name": "Hum"
                        },
                        {
                            "property": "plant-monitor:soil-ec",
                            "name": "Soil"
                        },
                        {
                            "property": "environment:temperature",
                            "name": "Temp"
                        }
                    ]
                }
            ],
but Num & Soil seems like light sensors. what am I doing wrong?

**Comment by merdok** [comment]
There is no humidity or soil accessory in HomeKit, hence the plugin uses a light sensor to display the raw values from the device.

**Comment by mrmaximas** [comment]
> There is no humidity or soil accessory in HomeKit, hence the plugin uses a light sensor to display the raw values from the device.

yes,  how to display/convert soil moisture as an air humidity sensor?

**Comment by mrmaximas** [comment]
and if there is a way, for example, when the soil moisture is less than a set value (e.g. 20%) to display this as an door sensor in open state, as my current plugin does.

**Comment by merdok** [comment]
You can do that by specifying a value in the propertyMonitor. That will create a sensor which will trigger when the value is reached.

**Comment by mrmaximas** [comment]
Please help me, I don't fully understand how to do it correctly. Thanks!

**Comment by merdok** [comment]
Just go check out the examples in the README.

**Comment by mrmaximas** [comment]
i don't understand how to create air humidity sensor linked to plant-monitor:relative-humidity property instead of light sensor

**Comment by merdok** [comment]
You cannot do that! I just explained you that there is no plant monitor module yet!

**Comment by mrmaximas** [comment]
thank you. can this be added in future releases?

**Comment by merdok** [comment]
Probably. Might have a look at it when I have some time.

**Comment by mrmaximas** [comment]
> Probably. Might have a look at it when I have some time.

Thanks! It will be very good! Have a good day!
