### ISSUE TITLE
Support for viomi.vacuum.v10

### ISSUE THREAD

**Issue by yogiee** [merdok/homebridge-miot#43]
Please add support for viomi.vacuum.v10 device.

**Comment by merdok** [comment]
Should be straight forward! Will add support for that vacuum in the next update!

**Comment by merdok** [comment]
@yogiee can you tell me what the official name of that vacuum is?

**Comment by yogiee** [comment]
> 
> 
> @yogiee can you tell me what the official name of that vacuum is?

It's called **Mi Robot Vacuum Mop P**.

https://www.mi.com/in/mi-robot-vacuum-mop-p/

**Comment by merdok** [comment]
Perfect! Thanks!

**Comment by merdok** [comment]
Added in version 0.9.4. Please try it out and let me know if everything works.

**Comment by yogiee** [comment]
Awesome, will test it out.

**Comment by yogiee** [comment]
Okay, so the device shows up in the homekit as it did before, but still not functional. Initially it shows battery low (robovac is on the charging dock and full battery), when powered on, following error is generated in Homebridge log. Also attaching the screenshots from homekit app.

`[6/20/2021, 2:56:18 AM] [miot] [Mi Robovac] Poll failed 4 times in a row! Stopping polling and trying to reconnect!`
`[6/20/2021, 2:56:18 AM] [miot] [Mi Robovac] Connected to device: viomi.vacuum.v10`
`[6/20/2021, 2:56:18 AM] [miot] [Mi Robovac] Setting up device!`
`[6/20/2021, 2:56:18 AM] [miot] [Mi Robovac] Doing device specific setup`
`[6/20/2021, 2:56:18 AM] [miot] [Mi Robovac] Doing initial property fetch`
`[6/20/2021, 2:56:18 AM] [miot] [Mi Robovac] Device setup finished! Device ready, you can now control your device!`
`[6/20/2021, 2:56:40 AM] [miot] [Mi Robovac] Poll failed 4 times in a row! Stopping polling and trying to reconnect!`
`[6/20/2021, 2:56:40 AM] [miot] [Mi Robovac] Connected to device: viomi.vacuum.v10`
`[6/20/2021, 2:56:40 AM] [miot] [Mi Robovac] Setting up device!`
`[6/20/2021, 2:56:40 AM] [miot] [Mi Robovac] Doing device specific setup`
`[6/20/2021, 2:56:40 AM] [miot] [Mi Robovac] Doing initial property fetch`
`[6/20/2021, 2:56:40 AM] [miot] [Mi Robovac] Device setup finished! Device ready, you can now control your device!`

![screenshot](https://filedn.com/lDMfKBbQGmpyuQfpIp30Seb/2021-06-20%2002-56-41.png)
![screenshot](https://filedn.com/lDMfKBbQGmpyuQfpIp30Seb/2021-06-20%2002-56-45.png)

**Comment by merdok** [comment]
You need to provide a homebridge debug log, ideally with the `deepDebugLog` property enabled. Without that there is no way for me to know what is wrong...

**Comment by yogiee** [comment]
> `deepDebugLog`

I enabled deep debug log, but not sure where exactly to find it? I'm running homebridge in docker setup and I checked the volume where homebridge settings are stored. I could only find standard homebridge log file.

**Comment by merdok** [comment]
`deepDebugLog` will only work when you start homebridge in debug mode. So you need to start your homebridge as described in the README with the `-D` flag:  `homebridge -D`

**Comment by yogiee** [comment]
Yeah, figured that out while exploring homebridge settings. Here's the log.

[log file](https://filedn.com/lDMfKBbQGmpyuQfpIp30Seb/homebridge.log)

**Comment by merdok** [comment]
Seems like the device is most probably not a miot device but a an older miio device, for that reason you need to use MiCloud. You need to specify your MiCloud credentials, the country where your device is located and enable the "Force MiCloud connection" button. If that will work, then i will mark your device as a MiCloud device in the next update.

**Comment by yogiee** [comment]
> 
> 
> Seems like the device is most probably not a miot device but a an older miio device, for that reason you need to use MiCloud. You need to specify your MiCloud credentials, the country where your device is located and enable the "Force MiCloud connection" button. If that will work, then i will mark your device as a MiCloud device in the next update.

Aha, I see. Checked MiCloud connection, however, my country (in, and i2) is not listed in the supported countries on this plugin.

**Comment by merdok** [comment]
You would need to temporary move your vacuum to the china server then and test it out.

**Comment by yogiee** [comment]
> 
> 
> You would need to temporary move your vacuum to the china server then and test it out.

Cool, will try that out and report. Thanks.

**Comment by merdok** [comment]
Just let me know if it works. If it will then i will mark the device as a MiCloud device and add the `in` (i suppose India?) server to the list.

**Comment by yogiee** [comment]
> 
> 
> Just let me know if it works. If it will then i will mark the device as a MiCloud device and add the `in` (i suppose India?) server to the list.

Yes, there are two listings that I saw in token_extracter app. **in** should be India, but by default the devices were added to **i2** servers.

**Comment by merdok** [comment]
What country are the `i2` servers in?

**Comment by yogiee** [comment]
> 
> 
> What country are the `i2` servers in? A secondary India server?

Apparently both `in` and `i2` are for India region, according to OpenHAB doc.

https://www.openhab.org/addons/bindings/miio/#country-servers

**Comment by merdok** [comment]
👍 Makes sense

**Comment by yogiee** [comment]
So apparently even after your update and trying to jump between regions in my Mi Home app, I couldn't get the Robovac working. However, I noticed that now by Robovac is listed on 3 different servers (CN, US and i2).

Sorry for the off-topic question, but is there any way to remove devices from different region servers (if not, just remove everything and start over)?

**Comment by merdok** [comment]
As far as I know adding the device to one server, should remove it from another. Not sure if you can remove all device from a server... maybe in the xiaomi home app?

**Comment by yogiee** [comment]
So after lot of tinkering and meddling with region, I'm happy to report that I've finally managed to get it working with MiCloud connection option and while the options are limited just a simple starting and stopping the vacuuming run works just fine and should be more than enough to map to HomeAssistant server to set automation schedules. Thanks a lot mate for quick update to the plugin.

**Comment by merdok** [comment]
Thanks for the info! Good to hear! You should also be able to enable modes with the modeControl property. 
Anyway in that case I will mark the device as a MiCloud device on the next update!

**Comment by merdok** [comment]
The device is now marked as MiCloud required as of version 0.9.6!
