### ISSUE TITLE
ows.tow_w.mjjs1

### ISSUE THREAD

**Issue by neyestrabelli** [merdok/homebridge-miot#432]
**Device model**
ows.tow_w.mjjs1

**Device name**
OWS S1 Towel Rack

**Does the device require a MiCloud connection?**
_Do not know_

**Anything special about the device?**
Yes I can controller, but I can't set temperature or change mode (idle,low, mid, high), I tryied to configure  properties, but I don't understand what I need to add at configs.

**Comment by merdok** [comment]
You have to go here http://www.merdok.org/miotspec/?model=ows.tow_w.mjjs1
Find the properties which you need and configure them based on that.

**Comment by merdok** [comment]
Good to hear!
