### ISSUE TITLE
Device discovered via MiCloud is constantly offline

### ISSUE THREAD

**Issue by fitur** [merdok/homebridge-miot#434]
**Describe the bug**
I signed in to MiCloud and fetched my device info. The device token, name and IP is the same as I've used with the plugin homebridge-xiaomi-roborock-vacuum which no longer works for me. 

**Expected behavior**
I tried to control the vacuum with the HomeKit buttons but they do nothing. Homebridge log show that my device is offline even though I connect and remote control it via the Roborock app.

**Your config.json**
```
{
    "devices": [
        {
            "name": "Roborock S7",
            "ip": "<device local ip>",
            "token": "<device token>",
            "deviceId": "<device id>",
            "model": "roborock.vacuum.a15",
            "pollingInterval": 10,
            "deepDebugLog": true,
            "micloud": {
                "username": "<email address>",
                "password": "<password>",
                "country": "de",
                "forceMiCloud": true,
                "timeout": 5
            },
            "buzzerControl": false,
            "ledControl": false,
            "childLockControl": false,
            "modeControl": false
        }
    ],
    "platform": "miot",
    "micloud": {
        "username": "<email address>",
        "password": "<password>",
        "country": "de"
    }
}
```

**Debug log**
[2/19/2023, 8:28:44 PM] [miot] [Roborock S7] The device with deviceId <device id> is not online! Device must be online for proper synchronization!

**Screenshots**
N/A

**Additional context**
N/A

**Comment by merdok** [comment]
The cloud reports that the device is offline hence it cannot be controlled. Maybe the device id is incorrect? You need to make sure that the device is correct!
