### ISSUE TITLE
Humidifier  device properties

### ISSUE THREAD

**Issue by koles0ff** [merdok/homebridge-miot#435]
Hello,

Looks like there is a bug in the plugin. I have 2 Mi Smart Antibacterial Humidifiers and both are showing water level in HB = 100%. Additionally, I can see that discovered properties do not show the water level at all. Is it possible to add water level value to mentioned device properties?

Discovered properties:
`
  "humidifier:fault",
  "humidifier:fan-level",
  "humidifier:target-humidity",
  "environment:relative-humidity",
  "environment:temperature",
  "alarm:alarm",
  "indicator-light:on",
  "custom:water-shortage-fault",
  "custom:the-tank-filed"
]`

Config:

`{
                    "name": "Влагодуй в Детской",
                    "ip": "192.168.1.108",
                    "token": "xxxx",
                    "deviceId": "xxx",
                    "model": "deerma.humidifier.jsq5",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": false,
                    "ledControl": true,
                    "childLockControl": false,
                    "modeControl": false,
                    "fanLevelControl": false,
                    "screenControl": false
                }`

Properties in HB:
https://i.postimg.cc/Wb397Rxz/Screenshot-2023-02-23-at-11-11-59.png

Real value is less than 70%

Than you for reply in advance.

**Comment by merdok** [comment]
Hi,

it seems like your device does support that, at least using the miot protocol, since when I look at the spec there is no such property. 

You can check here by entering your device model:
http://www.merdok.org/miotspec/
