### ISSUE TITLE
lumi.curtain.hmcn02 (Xiaomi BLE Curtain Driver E1) did not recognizing

### ISSUE THREAD

**Issue by romacv** [merdok/homebridge-miot#436]
I see that curtain driver is in supported devices list https://github.com/merdok/homebridge-miot/blob/main/supported_devices.md
But anyway it doesn't showing in devices list. Hub is connected.

**Comment by merdok** [comment]
How does your config look like?

**Comment by romacv** [comment]
@merdok https://drive.google.com/file/d/1HxnbvaWwNR_CYoMuek_-cm0MaUTCuCn1/view?usp=drivesdk

**Comment by merdok** [comment]
I do not see it in your config. You have to specify the token and ip of the gateway, but the model and deviceId needs to be that of the BLE device.

**Comment by romacv** [comment]
Thank you for your help @merdok, it's worked! I am so happy.
