### ISSUE TITLE
Smartmi Air Purifier TVOC

### ISSUE THREAD

**Issue by terrorhai** [merdok/homebridge-miot#44]
I use two Smartmi Air Purifier which work nice with miot. But the don't only have PM2.5, they also monitor TVOC (gas concentration). Is it possible to give this value to Homekit?

**Comment by merdok** [comment]
You probably mean the Air Quality property http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-za1:1, since there is no TVOC property. The property is already retrieved from the device, the issue is that with the limited Home app Ui there is no meaningful way to display it since the Home app does not support TVOC. 
Probably i could use a Illumination sensor to display the TVOC value, at least that way it would be visible in the UI...

**Comment by terrorhai** [comment]
Hey merdok, thx for the answer. Is it possible to switch between Lux sensor for native home app and probably a better displaying for the EVE app?

**Comment by merdok** [comment]
Automatically it would not be possible, just manually. But i do not think that it would be a good idea to differentiate between various apps...

**Comment by terrorhai** [comment]
Afaik the official Weather Plus plugin does this too, because many people use the EVE app with thing like fakegato. I attached a screenshot from Weather Plus.
![Uploading 9F45CAFA-7557-43CF-B9D4-C97D11CC5875.png…]()

**Comment by merdok** [comment]
For now I have no plans to do something similar, mostly because there are other more important things which needs to be done.

**Comment by terrorhai** [comment]
Okay, understood!
Is it easy todo with only the Lux sensor thing?

**Comment by merdok** [comment]
Yes, with the lux sensor it would be straightforward.

**Comment by terrorhai** [comment]
Yeah, then this should be enough for the start :-)

**Comment by merdok** [comment]
Ok, i will add the TVOC value as a lux sensor in the next update!

**Comment by terrorhai** [comment]
Thanks!!

**Comment by merdok** [comment]
As of version 0.9.7 TVOC should be displayed as part of the air quality sensor!

**Comment by terrorhai** [comment]
Hey merdok, nice update and way better than a lux sensor 🙃 

I'm just thinking about a probably missing 0 in front of the VOC value because 8mg/m3 in my case would be a really hardcore high value while the Mi app says very good.

Hit me if I'm wrong 😃 ![image](https://user-images.githubusercontent.com/44736283/125027824-30458000-e087-11eb-9cb4-ad92255e7346.jpeg)
![image](https://user-images.githubusercontent.com/44736283/125027830-34719d80-e087-11eb-855d-ef24f3e574fa.jpeg)

**Comment by merdok** [comment]
The value 8 should be the raw value that the device is reporting. I mean you can enable debug log and you will see in the terminal what raw values are synced from the device to make sure that it is correct.

But also like I already said, your device does not report the TVOC value but an Air quality value, so I am not sure if this air quality value is actually the TVOC value...

**Comment by terrorhai** [comment]
Okay, ignore what I've said. The unit is in micrograms, not milligrams 😅 

So it's working better than expected and is exactly how it should work!

**Comment by merdok** [comment]
Good to hear👍
