### ISSUE TITLE
Child accessory fetches name from main accessory after adding to HomeKit

### ISSUE THREAD

**Issue by romacv** [merdok/homebridge-miot#440]
I encountered the issue that when you add a bridge to the Home application, the accessory is added normally, but takes the name of the main device and overwrites it to all child controls. See here what accessories look like in homebridge. Humidifier is the main device and then there are switches of its modes.
<img width="693" alt="Screenshot 2023-02-25 at 22 25 50" src="https://user-images.githubusercontent.com/3684453/221365394-59d766b2-5cf2-4da3-a5a7-5b8b4c1691dd.png">
Next this is what a grouped accessory looks like after being added.
<img width="320" alt="" src="https://user-images.githubusercontent.com/3684453/221365464-053f6561-ff0d-455e-9ac1-ea182d15ef65.jpg">
Look - the name of the child device is taken from the main one, though...
<img width="320" alt="" src="https://user-images.githubusercontent.com/3684453/221365481-5159714f-8158-4071-93ee-f2ead0d5f099.jpg">
although... if I erase the name, then seeing the placeholder showing is a correct name.
<img width="320" alt="" src="https://user-images.githubusercontent.com/3684453/221365516-adffe4a0-3561-4de0-89e4-a983539f13ce.jpg">
It seems this is some kind of bug in the bridge structure, the name of the Home Kit child should be the same as in homebridge.
`{
                    "name": "Air humidifier",
                    "ip": "192.168.1.11",
                    "token": "-hidden-",
                    "deviceId": "530142419",
                    "model": "zhimi.humidifier.ca4",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true,
                    "fanLevelControl": true,
                    "screenControl": true
                }`
Thank you.

**Comment by merdok** [comment]
Hi, 
this is a know issue with ios16.
Please read about it here:  https://github.com/merdok/homebridge-miot/issues/338#issuecomment-1249729272
As far as i know there is still nothing that i can do about so as a temporary solution you would need to rename your accessories manually.
