### ISSUE TITLE
Token vacuum cleaner dreame L10 ultra

### ISSUE THREAD

**Issue by djrams10** [merdok/homebridge-miot#441]
hello, I would like please to recover the token of my dreame L10 ultra vacuum cleaner.
After several searches I can't find how to get it.

can you help me? THANKS.

**Comment by djrams10** [comment]
Here is his name: dreame-r2250 Thanks

**Comment by djrams10** [comment]
On the other hand, I think it is impossible to add it in the mi home application.

**Comment by merdok** [comment]
If you cannot add it to the mi home app or into the micloud then you need to find another way to retrieve the token. I am sure that there are other ways on how to do it.

**Comment by djrams10** [comment]
Thank you for your answer, I searched a lot but couldn't find anything. If anyone has a solution please let me know.

**Comment by merdok** [comment]
Somebody requested the support of that device I guess so you might want to try to search for that issue and try to ask the requester there.

**Comment by djrams10** [comment]
But I finally wonder if it is not the L10s ultra that is compatible and not the L10 ultra.

**Comment by djrams10** [comment]
Thank you for your answer. in fact there is the L10s ultra on xiaomi home but not the L10 ultra. I'll try again tomorrow, I may have made a mistake. because it's really amazing it's practically the same.
