### ISSUE TITLE
Support for more BLE-based Devices

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#443]
**Device model**

1. cleargrass.sensor_ht.dk1
2. miaomiaoce.sensor_ht.t2
3. lumi.flood.bmcn01
4. philips.light.nlight

**Device name**

1. Mi Temperature and Humidity Monitor
2. Mi Temperature and Humidity Monitor 2 BLE
3. Mi Flood Detector
4. Mijia Philips BLE Nightlight

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
Using the same method of adding Mi Door and Window Sensor 2, the plugin was able to identify all device types correctly but stated as Not Supported in HomeKit. These device types supports native HomeKit feature like temperature sensor, submersion sensor, etc.

Based on helpful thread here #442, I manage to expose the (not-yet-supported on the plugin) Qingping Door/Window Contact sensor the same way as Xiaomi's ones.

**Comment by merdok** [comment]
Thanks for the request!
Can you shortly describe what is working and what i snot working with the sensors, so i have an idea what i should focus on?

**Comment by mrmaximas** [comment]
Please don't remember about my hhcc.plantmonitor.v1 ;) 
It's works via light sensor property, but please link plant-monitor:relative-humidity to the humidity sensor in homekit.

**Comment by merdok** [comment]
@ahmadnazirafiq whatever the gateway reports will be displayed, in debug mode you will be able to see in the log what values come back.

@mrmaximas i will try to add that too

**Comment by mrmaximas** [comment]
> i will try to add that too
thks for this hardwork!

**Comment by mrmaximas** [comment]
By the way, is it possible to do this:
the first one plant-monitor:relative-humidity with the "value": "XX" signals that it is time to water, the second one just shows the humidity?
"propertyMonitor": [
                        {
                            "property": "plant-monitor:relative-humidity",
                            "name": "Singonium Humidity Alram",
                            "value": "25"
                        },
{
                            "property": "plant-monitor:relative-humidity",
                            "name": "Singonium Humidity Alram",
                            "value": "25"
                        },
                        {
                            "property": "plant-monitor:soil-ec",
                            "name": "Singonium Soil"
                        }

**Comment by merdok** [comment]
Yeah, it is possible and you can create as many `propertyMonitor` entries for a property as you need.

**Comment by mrmaximas** [comment]
> Yeah, it is possible and you can create as many `propertyMonitor` entries for a property as you need.
I often get a message like this:
[Singonium] Poll failed 4 times in a row! Stopping polling and trying to reconnect! Reason: FetchError: network timeout at: https://api.io.mi.com/app/miotspec/prop/get
I've tried to add  "propertyChunkSize": 1, but there are more and more of these messages. 
I have 10 such sensors in total. is this a micloud problem?
My polling interval is 10 minutes ( "pollingInterval": 600, ), I don't see the point of polling the plant sensors more often.

**Comment by merdok** [comment]
Sometimes the micloud server might be slow to respond, you can try to increase the timeout by double and see if that helps.

**Comment by mrmaximas** [comment]
> Sometimes the micloud server might be slow to respond, you can try to increase the timeout by double and see if that helps.

trying to :)  "timeout": 10000,

**Comment by merdok** [comment]
@ahmadnazirafiq it has to be the gateway where your BLE devices are connected to.

@mrmaximas 👍

**Comment by mrmaximas** [comment]
> Does the BLE gateway's IP address has to be the ones added with this plugin?

In fact, BLE devices can only be polled via micloud. I think the plugin should add the otion "ble": true and force the use of micloud by default.

> @ahmadnazirafiq it has to be the gateway where your BLE devices are connected to.

It works with my external GW IP for example, I think it will work with the 1.1.1.1 )

**Comment by mrmaximas** [comment]
> @mrmaximas 👍

didn't help much. trying 20000

**Comment by merdok** [comment]
I am certain that you do not need to use micloud if everything is entered correctly. It should also work with a local connection directly to the gateway which should be more stable.

**Comment by mrmaximas** [comment]
> I am certain that you do not need to use micloud if everything is entered correctly. It should also work with a local connection directly to the gateway which should be more stable.

i will try to use BLE gateway IP, but i have two Xiaomi Smart Home Gateway 3 each of which partially sees my ble devices

**Comment by merdok** [comment]
Not sure how to handle it when you have multiple gateways😅
Anyway, your BLE temperature sensor looks like this http://www.merdok.org/miotspec/?model=cleargrass.sensor_ht.dk1
The temperature and humidity are on a not supported service. Will need to add that...
Just it will take some time until i can start to work on that as i am on vacation starting from tomorrow for 3 weeks...

**Comment by mrmaximas** [comment]
> Pick the gateway closest to the sensor itself. The way BLE-sensor works is that it connects to multiple gateways at the same time.

Of course,  I gave for part of the sensors first gateway IP and the others second gateway IP, but it doesn't seem to be working, it only works when I specify the external ip of my gateway, which micloud sees and wich token extractor gives me.

**Comment by mrmaximas** [comment]
> Just it will take some time until i can start to work on that as i am on vacation starting from tomorrow for 3 weeks...

Sorry for offtopic, but I hope you spend your holidays in Portugal ))

**Comment by romacv** [comment]
+1 for **miaomiaoce.sensor_ht.t2** (Mi Temperature and Humidity Monitor 2 BLE), really need to support it. Let me know if i can help somehow.

**Comment by mrmaximas** [comment]
> Just it will take some time until i can start to work on that as i am on vacation starting from tomorrow for 3 weeks...
hi! Have you forgotten about us? Thanks!

**Comment by merdok** [comment]
Version 1.6.0 now adds support for those devices.

**Comment by mrmaximas** [comment]
> Version 1.6.0 now adds support for those devices.

it's possible to automatically add sensor name before temperature/soil and illumination?
it is difficult to understand which sensor corresponds to which value )
![IMG_8769](https://user-images.githubusercontent.com/61165387/228954528-910e5c39-5cf4-4cae-8aa2-ee05299d9609.png)
![IMG_8770](https://user-images.githubusercontent.com/61165387/228954577-38d21798-2fe8-4c93-a6b3-7d8082c93c8b.png)

**Comment by merdok** [comment]
You should be able to rename them.

**Comment by mrmaximas** [comment]
> You should be able to rename them.

yes, but the sensor name is added to the temperature automatically 🤷🏻‍♂️
![Uploading IMG_8772.png…]()

**Comment by merdok** [comment]
Yeah, well that is quite odd. I guess that is the downside after fixing the switch names...

**Comment by mrmaximas** [comment]
> Yeah, well that is quite odd. I guess that is the downside after fixing the switch names...

besides - nothing happens when the "presence detector" is below the limit.
I have set a 25% humidity for the alarm, such as this.
some sensors have a value below 25%
,
                {
                    "name": "Klara",
                    "ip": "xxxx",
                    "token": "xxxxx",
                    "deviceId": "blt.3.13le5i950e000",
                    "pollingInterval": 300,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "xxxxxx",
                        "password": "xxxx",
                        "country": "cn",
                        "forceMiCloud": true
                    },
                    "suppressAutoServiceCreation": [
                        "temperature",
                        "illumination"
                    ],
                    "propertyMonitor": [
                        {
                            "property": "plant-monitor:relative-humidity",
                            "name": "Klara Humidity Alarm",
                            "value": "25"
                        }
                    ]
                },
                
![Screenshot 2023-04-08 at 13 44 49](https://user-images.githubusercontent.com/61165387/230717043-a230449c-37b1-4332-bdce-c1ac9b3328c2.png)
![Screenshot 2023-04-08 at 13 44 57](https://user-images.githubusercontent.com/61165387/230717046-c13b0a18-01c1-4d0e-ab59-3db45798b0c8.png)

**Comment by merdok** [comment]
The value has to be exact 25 to trigger. It would make sense to introduce the possibility to set below or above. If you could open a feature request for that then i will not forget it and include it in the next update.

**Comment by mrmaximas** [comment]
> The value has to be exact 25 to trigger. It would make sense to introduce the possibility to set below or above. If you could open a feature request for that then i will not forget it and include it in the next update.

done!

**Comment by romacv** [comment]
@ahmadnazirafiq my suggestion is: rename it in parent Mi Home app like “Bedroom Thermometer”, “Living Room Thermometer”, etc.
Then after adding to HomeKit - you can clear name of sensor and see what exact name and location of sensor.
![IMG_8441](https://user-images.githubusercontent.com/3684453/230755503-e1ec2a3d-549d-4cd5-ac4e-e3ca9ee9edf2.png)

**Comment by merdok** [comment]
Hmmm, it should work. Might be a bug if the illumination sensor is still created for the device.
If that is indeed the case then it would be great if you can open a separate bug.

**Comment by mrmaximas** [comment]
> Hmmm, it should work. Might be a bug if the illumination sensor is still created for the device. If that is indeed the case then it would be great if you can open a separate bug.

PPA for this log:
[Asparagus L] Device properties: [
"plant-monitor:relative-humidity",
"plant-monitor:soil-ec",
"plant-monitor:illumination",
"environment:temperature

may be because temperature is environment?

**Comment by merdok** [comment]
It is very strange. Just double checked the code and everything seems fine, the light sensor should not show up...

**Comment by mrmaximas** [comment]
> It is very strange. Just double checked the code and everything seems fine, the light sensor should not show up...

but they were created 
![Screenshot 2024-03-01 at 16 43 43](https://github.com/merdok/homebridge-miot/assets/61165387/251f0f2f-9248-4719-8e39-b300bf999180)

**Comment by mrmaximas** [comment]
> It is very strange. Just double checked the code and everything seems fine, the light sensor should not show up...

i'm sorry for this mistake, soil-ec is the illumination sensor too in the HK

**Comment by merdok** [comment]
Yes, disabling soil ec is not supported. You would need to set the onlyMainAccessory property to disable that.
