### ISSUE TITLE
Support for IR remotes from Xiaomi Smart Speaker.

### ISSUE THREAD

**Issue by romacv** [merdok/homebridge-miot#446]
**Device model**
- Living Room Xiaomi Smart Speaker  xiaomi.wifispeaker.l05g 6b4f316b556150307270383556797959  561346725 192.168.1.41 tw
- Living Room AC  miir.aircondition.ir02    ir.1622213879634477056    tw

**Device name**
- Living Room Xiaomi Smart Speaker (IR Control)
- Created from app air conditioner remote

I have Speaker with IR Remote control.
<table><tr><td><img width = "300" src="https://user-images.githubusercontent.com/3684453/224072346-70569ba8-7e3b-4fd0-afb1-5eda1d3e4387.PNG" /></td><td>
<img width = "300" src="https://user-images.githubusercontent.com/3684453/224072611-285874b8-f7eb-4d97-80e3-a0d32743b553.PNG" /></td></table>

Successfully added this custom IR remote to homebridge, looks like it's supported and recognized as air conditioner, **but doesn't work and does't response.**
<img width = "300" src="https://user-images.githubusercontent.com/3684453/224072695-fc79c946-97a5-4995-862e-3380f96c9b70.JPG" />
Here's config, i used  IP and token of speaker and model and id of created remote.
`{
                    "name": "Living Room AC Xiaomi",
                    "ip": "192.168.1.41",
                    "token": "6b4f316b556150307270383556797959",
                    "deviceId": "ir.1622213879634477056",
                    "model": "miir.aircondition.ir02",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": true
                }`

**Comment by merdok** [comment]
I mean the ir remote seems like a completely new device type.
As I understand it does not support Bluetooth but uses infrared?
How does it work? Does the ir remote send a signal to the gateway?

**Comment by romacv** [comment]
Speaker connect through Wi-Fi to cloud, then you can add sub devices, it will add new device like ac, tv, fan. I believe it send commands and works same like gateway-connected BLE/Zigbee devices.
Here's you can see video about this device https://youtu.be/qWxBLC-iC4M

 ![image](https://user-images.githubusercontent.com/3684453/224210413-5916f7d5-c707-4bc1-ba63-be0a67a0bf58.png)

**Comment by merdok** [comment]
Are you requesting support for a ir remote or the smart speaker? This is something which is confusing me😅

**Comment by romacv** [comment]
This is Smart Speaker with IR gateway feature. Please check the link: https://www.mi.com/global/product/xiaomi-smart-speaker-ir-control/
I need to support Air Conditioner control via IR remote functionality. 
I believe it should work with cloud same like BLE/Zigbee child devices, but child devices - IR remotes.

**Comment by merdok** [comment]
So this is the device model which you need support for miir.aircondition.ir02?

**Comment by romacv** [comment]
> So this is the device model which you need support for miir.aircondition.ir02?

Right.

**Comment by merdok** [comment]
Thanks for creating the pull requests! If the devices now work can we close this?

**Comment by romacv** [comment]
I'll duplicate updates here:
> [romacv](https://github.com/romacv) commented [19 hours ago](https://github.com/merdok/homebridge-miot/pull/450#issuecomment-1465208393)
Unfortunately doesn't work, looks like IR control gateway more complicated.

> [merdok](https://github.com/merdok) commented [20 minutes ago](https://github.com/merdok/homebridge-miot/pull/450#issuecomment-1465737553)
I think it should work the same or similar as BLE devices...

Let's study the issue in more detail later.

**Comment by merdok** [comment]
How do you enter the device data into the config? The same as for BLE devices?
Did you try to use the miot cli to directly communicate to the device from the command line? That way you will be able to quickly test the communication and retrieve property values or execute actions.

**Comment by AlokBansal8** [comment]
Is anyone working on providing support for IR Remote?

**Comment by merdok** [comment]
@AlokBansal8 what IR Remote do you have?
