### ISSUE TITLE
Mi Smart Dishwasher and Rice cooker - No response.

### ISSUE THREAD

**Issue by romacv** [merdok/homebridge-miot#447]
**Describe the bug**
Devices successfully added to HomeKit, mapped all the actions/switches correctly, but don't respond.

**Your config.json**
`{
                    "name": "Mi Smart Dishwasher",
                    "ip": "192.168.1.39",
                    "token": "3e887e607dcd2c5f28c23b23400ce60d",
                    "deviceId": "469364068",
                    "model": "viomi.dishwasher.m02",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                },
{
                    "name": "Rice cooker",
                    "ip": "192.168.1.35",
                    "token": "dd85a97cf4ca6f7dae4001b9f1e11284",
                    "deviceId": "403948114",
                    "model": "chunmi.cooker.normalcd1",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                }
`

**Screenshots**
Videos: https://share.icloud.com/photos/0fbdSgh-wwyfwPiIy8sCDyZZg

**Comment by merdok** [comment]
Maybe the devices use the miio protocol and not the miot? In that case did you try to specify the forceMiCloud property and add your micloud credentials?

**Comment by romacv** [comment]
Thank you! viomi.dishwasher.m02 started working with micloud force connection option.
But chunmi.cooker.normalcd1 unfortunately no, but looks like this device doesn't supported.

**Comment by merdok** [comment]
You would need to use actionButtons and propertyControl to expose whatever you need from the cooker. That should work!
