### ISSUE TITLE
Support Mi Robot Vacuum-Mop 2 Ultra 

### ISSUE THREAD

**Issue by Hydings** [merdok/homebridge-miot#448]
**Device model**
dreame.vacuum.p2150a

**Device name**
Mi Robot Vacuum-Mop 2 Ultra 

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
It doesnt work with the default tools.

**Comment by merdok** [comment]
What is the issue currently? Does it not work completely or just partially?

**Comment by Hydings** [comment]
That was my mistake. It works with default settings if your plugin is up to date.
