### ISSUE TITLE
Roborock S50

### ISSUE THREAD

**Issue by Marrand** [merdok/homebridge-miot#454]
**Device model**
roborock.vacuum.s5

**Device name**
Roborock S50, S51, S55 (White, Gold, Black)

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
Device works actually, but plugin says :

[miot] [Roborock S55] Device services:
  "vacuum",
  "battery",
  "identify"

[miot] [Roborock S55] Initializing device properties
[miot] [Roborock S55] Device properties:
  "vacuum:status",
  "vacuum:mode",
  "battery:battery-level",
  "battery:charging-state"

[miot] [Roborock S55] Initializing device actions
[miot] [Roborock S55] Device actions:
  "vacuum:start-sweep",
  "vacuum:stop-sweeping",
  "battery:start-charge",
  "identify:identify"

And then :

[miot] [Roborock S55] =AB= Action vacuum:start-room-sweep does not exist on this device. Skipping action button!

But Roborock S55 do have room cleaning, please update it 👍

**Comment by merdok** [comment]
According to the spec found here: http://www.merdok.org/miotspec/
there is no start-room-sweep action in the miot protocol for this device.

**Comment by Marrand** [comment]
There is no way to add it? In another plug-in I can select room cleaning.

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum

**Comment by merdok** [comment]
The other plugin uses the old miio protocol. This plugin uses the new miot protocol and old devices that natively does not support it have limited functionality hence it is missing for your device.

**Comment by Marrand** [comment]
Ok I will keep with the other plug-in
