### ISSUE TITLE
Support for Xiaomi Mi Temperature and Humidity Sensor 2 (miaomiaoce.sensor_ht.t2)

### ISSUE THREAD

**Issue by dimkagithub** [merdok/homebridge-miot#456]
**Device model**
miaomiaoce.sensor_ht.t2

**Device name**
Xiaomi Mi Temperature and Humidity Sensor 2

**Does the device require a MiCloud connection?**
Do not know but now it does not work without MiCloud force connection

**Anything special about the device?**
It work with property monitor, but shows luxes instead % of humidity

**Comment by merdok** [comment]
Added in version 1.6.0

**Comment by dimkagithub** [comment]
Nice)
