### ISSUE TITLE
Support for Mi Smart Power Plug 2 (Wi-Fi and Bluetooth Gateway)

### ISSUE THREAD

**Issue by charleszhai1991** [merdok/homebridge-miot#46]
Can you add the full support for Mi Smart Power Plug 2 (Model: chuangmi.plug.212a01 ) ?
My plug works well but there are some minor issues:

a. On HomeBridge it says "Device not supported! Using a generic device with limited properties! Consider requesting device support!"
b. It appears on Apple Home as a "Switch" rather than an "Outlet", the product type needs to be corrected.

_Device information:
Name(s) of the device: Mi Smart Power Plug 2 (Wi-Fi and Bluetooth Gateway)
Link: https://www.mi.com/buy/detail?product_id=12777
Model: chuangmi.plug.212a01_

Thanks!
Charles

**Comment by merdok** [comment]
Hello,
yes, that should be no problem to add full support :) 
If you use the switch right now, then i assume that you already can control it (turn on/off), right?

**Comment by charleszhai1991** [comment]
Thanks, Merdok, I appreciate it!
Yes I can control it perfectly, except for the wrong product type, I am looking forward to seeing the update for this Mi device.

**Comment by merdok** [comment]
So that confirms that it is indeed a miot device! Will add correct support for it in the next update!

**Comment by merdok** [comment]
Please try version 0.9.6. The device should now be supported.

**Comment by charleszhai1991** [comment]
Thanks, it works! But there is a temperature sensor that groups with the outlet once I add it to Home App, does it mean there is a temperature sensor build-in? How can I disable it?
![IMG_9376](https://user-images.githubusercontent.com/85482123/123669201-6a847580-d86e-11eb-8999-23bd535eb7ae.PNG)

**Comment by merdok** [comment]
Yes, the outlet has a temperature sensor that is why you see it there. You can ungroup the tiles and hide the temperature sensor in a separate room if you do not need it.
