### ISSUE TITLE
Camera Xiaomi presence sensor - chuangmi.camera.046a01

### ISSUE THREAD

**Issue by RavidCo** [merdok/homebridge-miot#463]
**Describe the bug**

When I set the: “motion-detection:motion-detection”

It only shows me the sensor at HomeKit, but when there is a motion detected, it doesn't notification at HomeKit, 

my question is, how should I set it to receive an alert from the HomeKit as well and not only from the Xiaomi app

It is important for me to point out that the config.json I mentioned is temporary, because I tried almost everything, with true, false, numbers 0,1.. , and also without anything

**Expected behavior**

when there is a motion detected, receive an notification from the HomeKit

**Your config.json**

  "name": "Home Camera",
                    "ip": "zzzzzzz",
                    "token": "xxxxx",
                    "deviceId": "yyyyyyy",
                    "model": "chuangmi.camera.046a01",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "customAccessory": false,
                    "onlyMainService": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "propertyMonitor": [
                        {
                            "property": "motion-detection:motion-detection",
                            "name": "Motion Detection",
                            "value": 1,
                            "linkedProperty": "motion-detection:motion-detection",
                            "linkedPropertyValue": true
                        }
                    ]
                },

**Comment by RavidCo** [comment]
![IMG_1273](https://user-images.githubusercontent.com/128496741/229168350-40d06868-bb15-4d34-9933-423a7c84a397.jpeg)

**Comment by merdok** [comment]
The property which you are monitoring might not be the actual value of the state but a configuration property, meaning a property which only allows you to turn on or off the Feautrw.

**Comment by RavidCo** [comment]
Hey

and you know what is the actual value of the state? 

In the manual there is an value “-“

**Comment by merdok** [comment]
I think that it is an event, but events unfortunately currently does not work
