### ISSUE TITLE
Can't see how to setup actionButtons in a user-friendly way dreame.vacuum.r2228o

### ISSUE THREAD

**Issue by ufkel** [merdok/homebridge-miot#466]
I'm opening an issue not for a bug but for a hard time understanding how to handle actionButtons in a user-friendly way. Maybe you can help me to understand how to do it?

The task is simple, I think: I want to set up a button to initiate the cleaning of a single room.

- The dreame.vacuum.r2228o is a supported device.
- According to the excellent guide https://github.com/merdok/homebridge-miot/blob/main/docs/robotcleaner.md
the robot needs two separate commands. One for the room selection, and one for actually starting the cleaning job. Understood.

But having two separate buttons in the Home App for a single room is not user-friendly. Can I somehow merge these two commands into a single button?

Sorry if this is a stupid question. But right now I cannot see how to do it. Any help is very much appreciated.

**Comment by merdok** [comment]
You only need 1 action button for every room or every room group which you need.

**Comment by ufkel** [comment]
Thank you for that hint. It is exactly what I want to achieve, but how can I merge a "6.2" action plus a "4.1" action into a single action button?

**Comment by merdok** [comment]
You do not need both, just one of them whichever your vacuum supports.

**Comment by ufkel** [comment]
Well, my device belongs to the Xiaomi X10 class.
The guide says about those robots: "A device which needs the actions for the room configuration and the actual room selection in 2 separate commands."

My understanding: 
The first command is the room configuration (6.2), the second command is the actual room selection (4.1). 

Following your recommendation, I will try to use just one of them, and will report the result. Thank you for the helping hand.

**Comment by ufkel** [comment]
As promised, here are my results: 
A single 6.2 command is not sufficient, nor is a single 4.1 command. 
You have to send both commands one after the other to let the robot know what to do (6.2 command) and give it the start (4.1 command).

**Comment by merdok** [comment]
Well then it seems that this is how it needs to be done for your vacuum. Like already mentioned there are different devices out there and not everyone behaves the same.
