### ISSUE TITLE
Mijia Robot Vacuum-Mop 3C

### ISSUE THREAD

**Issue by sergeybutakov** [merdok/homebridge-miot#467]
Hello! What about Mijia Robot Vacuum-Mop 3C support?
I was able to find and add it, but I can’t add buttons for cleaning in the rooms((

`miot send 192.168.0.187 -t 65646a517831415841686c6c346f3868 get_room_mapping '[]'
INFO  Connecting to device at  192.168.0.187
ERROR  Could not connect to device, handshake timeout

miot send 192.168.0.187 -t 65646a517831415841686c6c346f3868 get_properties '[{"siid":8,"piid":2}]'
INFO  Connecting to device at  192.168.0.187
ERROR  Could not connect to device, handshake timeout`

**Comment by merdok** [comment]
`handshake timeout` usually indicate an incorrect token

**Comment by sergeybutakov** [comment]
> `handshake timeout`обычно указывают неправильный токен

reconnected the device, tried with a new token - still an error ((
![image](https://user-images.githubusercontent.com/49130876/229566984-5740effd-9249-49be-82e9-61d67ee6f5ee.png)
![image](https://user-images.githubusercontent.com/49130876/229567225-ca3f7752-4957-4945-b0b1-9a7eb492713c.png)

**Comment by merdok** [comment]
Then maybe the local ip might be wrong. `handshake timeout` is a strong indicator that a connection cannot be made to the device, whether it is the token or the ip or local network issues. i cannot tell...
