### ISSUE TITLE
Dreame L10s Ultra: Room-IDs reported are wrong (in a funny way)

### ISSUE THREAD

**Issue by ufkel** [merdok/homebridge-miot#468]
Getting the room IDs for my Dreame L10s Ultra does not work the way it should be.

Both methods, namely using a propertyMonitor or via "miot send <IP> -t <TOKEN> get_properties '[{"siid":8,"piid":2}]' do work technically, but they deliver wrong results.

In my case: 
- Reported room ID is 2175234 - in fact it is 2.
- Reported room ID is 2175238 - in fact is is 6.
The reported room ID is always 2175232 higher than it really is.

If I use that high number in an actionButton config, the robot tells me it cannot reach that room and returns to the base station. If I subtract 2175232 from the reported number, and use the smaller number in my config, the actionButton does work.

Here is an example output from propertyMonitor:
[4/4/2023, 9:13:02 AM] [homebridge-miot] [Sauger] <-W-> Monitored string property time:timer-clean value changed to ---> 2-1-12:04-0000000-0-1-0-0-2175234

**Comment by merdok** [comment]
Well, this is something I have no control over. The value is Bering reported by the vacuum, why it is like that I cannot tell you. Although all the different manufacturers use the xiaomi miot protocol, the results how they leverage it may vary hence there are differences. 
Maybe dreame changed that behavior with the recent vacuums...
