### ISSUE TITLE
Add support for Yeelight Ceiling Lamp

### ISSUE THREAD

**Issue by chankarchung** [merdok/homebridge-miot#469]
**Device model**
yeelink.light.ceiling1

**Device name**
Yeelight Ceiling Lamp

**Does the device require a MiCloud connection?**
Do not know (Most likely yes)
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_

**Comment by merdok** [comment]
What is the exact issue with the device? It is being reported as a light device hence it should without issues already work with he plugin.

**Comment by chankarchung** [comment]
I figured out the problem.  It is working now.

**Comment by merdok** [comment]
Good to hear! Thanks for the info!
