### ISSUE TITLE
Adding zhimi.fan.sa1 without having to provide username and password? 

### ISSUE THREAD

**Issue by 4rianton** [merdok/homebridge-miot#471]
Hi there, thanks for your development work on such great plugin. 

I already use https://github.com/merdok/homebridge-xiaomi-fan but I saw in an issue there that if I want to see the oscillate function as a separate switch, I should be using this plugin instead, so I installed it and added a couple of accesories along with the fan. 

My air purifier works without issues, but when I add my fan with all the details like IP, token, device ID and some fan specific settings, I get an error that I should supply the username and password for miCloud. 

Now, I was able to control the fan with your other plugin without having to enter the username and password and not this one. Is there a reason for it, and is there a workaround to be able to add the fan without having to store my username and password in the plugin? 

Thanks in advance for looking. Cheers!

**Comment by merdok** [comment]
Hi,
this plugin uses the miot protocol where the other one uses the miio protocol. The zhimi.fan.sa1 is by now an old device and does not support the miot protocol natively (only the old miio one). Xiaomi offers a miot protocol emulation for older devices but that only worked over the cloud and with limited property support. For this reason when using this plugin you have to specify your mi cloud credentials to be able to control older devices.

**Comment by 4rianton** [comment]
Sorry for the late response, but thank you for the detailed explanation. Once again, appreciate your work on all the plugins. Cheers!
