### ISSUE TITLE
Dehumidifier controllable value is wrong

### ISSUE THREAD

**Issue by oupeng** [merdok/homebridge-miot#472]
The control range of dehumidifier(dmaker.derh.22l) is 40%-70%, in homekit adjustable 1%-100%, can not correspond to the correct value.thanks
![image](https://user-images.githubusercontent.com/3167663/231350913-349cdbb1-ce0e-4472-aa09-4604b8e32ed7.png)
![image](https://user-images.githubusercontent.com/3167663/231350975-7359551e-0ebf-446e-82c2-26b4cebf7e09.png)

homebridge-miot v1.6.0
Node.js  v18.15.0

**Comment by merdok** [comment]
This is only a visual limitation. In HomeKit you cannot change the range of the slider, it has to always be 1% to 100%. In the background this is being calculated from the HomeKit value into the actual slider value. I know that this is white odd, but there is nothing that can be done currently.

**Comment by oupeng** [comment]
When the dehumidifier set to 40%, home kit shows 25%, does it correspond to this zone? (40%-70%)
thanks.good luck!

**Comment by merdok** [comment]
And what does it show at 70%?

**Comment by oupeng** [comment]
58%

**Comment by merdok** [comment]
You would need to post some debug log of that so I can see what the actual values are which you set
