### ISSUE TITLE
Expose manually-run Mi Home scenes to HomeKit

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#474]
**Describe the idea or improvement**
I have a couple of manual scenes (where we tap to launch manually) to trigger an action or device. Would be nice to have those manual scenes exposed as a switch in Apple Home as well. Other IoT providers like Tuya plugins made this possible by exposing one-time scenes already created in the app as a switch on the Apple Home app.

**Describe the solution you'd like**
This is useful because some devices on Mi Home app uses custom controls and connectivity that is simply not possible with this plugin yet (like turning on a Projector, IR controls, etc). Best example is with the Tuya plugins which while does not support a pet feeder yet, can still be triggered with a scene that was first created in the Tuya app. The plugin simply exposed the manual scene to Apple Home as a switch, that can be triggered manually or as part of an automation.

**Benefits**
This pretty much simplifies the use of device features that are not exposed by this plugin by default (like we have to add the action trigger manually etc).

**Comment by merdok** [comment]
Hi,
could you explain more detailed or even provide an example of your idea. Maybe how would you imagine the config entry would look like and what would be the expected output. I am currently struggling to understand what this would look like.

**Comment by merdok** [comment]
I still do not quite get the idea 😅
Why not just create an action button in the plugin and wrap it into a scene? If you have more actions then you can add all those actions into a single scene and execute it when needed.
I do not quite understand what scenes should the plugin generate and expose to HomeKit? If you need scenes in HomeKit then why not create them there as described above?
