### ISSUE TITLE
Additional section in robotcleaner.md for dreame.vacuum.mc1808/dreame.vacuum.mb1808

### ISSUE THREAD

**Issue by mavoronin** [merdok/homebridge-miot#477]
**Describe the idea or improvement**
Add new section to robotcleaner.md "Room cleaning" for dreame.vacuum.mc1808/dreame.vacuum.mb1808 as their action and params for room cleaning differ from other dreame devices. 

**Describe the solution you'd like**
```js
"actionButtons": [
    {
        "action": "18.1",
        "name": "Clean first room",
        "params": [
            {
                "piid": 1,
                "value": 18
            },
            {
                "piid": 21,
                "value": "{\"selects\":[[1,1,1,1,1]]}"
            }
        ]
    }
]
```

**Additional context**
Source: [this article](https://sprut.ai/article/odin-iz-variantov-upravleniya-pylesosom-1c-stytj01zhm-dreame-vacuum-mc1808-iz-home-assistant). Tested on my own dreame.vacuum.mc1808. Works well.

**Comment by merdok** [comment]
Thanks for the info! That makes sense! If you want you can try to submit a pull request, if not then it is fine and i will add it.

**Comment by mavoronin** [comment]
[Pull request](https://github.com/merdok/homebridge-miot/pull/478) submitted.
