### ISSUE TITLE
Dreame Robot vacuum f9

### ISSUE THREAD

**Issue by kimo790** [merdok/homebridge-miot#487]
Thank You for your work and time.
i used the fetch metadata option you integrated in the UI, it works great.
I was unable to use other Metadata actions and properties due to my limited syntax and parameters knowledge,  can you please provide a little more data about the syntax or how to use the other actions like 2.1 and 2.3, etc ... and the in and out piid.

thank you again for providing this valuable service to us

**Comment by merdok** [comment]
Hi,
did you have a look at the docs for robot cleaners? There are some examples there on how to handle in and out values.
The in piid's for actions usually correspond to the property id on the same service as the action. There you can see what expected value does the action need.

**Comment by kimo790** [comment]
nope, do you have it in this repo ? I apologize for my clumsiness, im new to all of this with a little to intermediate knowledge of coding

**Comment by merdok** [comment]
That is correct! That is why you have to check the metadata of a device and see what parameters they accept. Most actions from my experience do not accept any parameters. Every action has its own parameters if any, so you cannot just simply take the parameters from action and use it with a different one.

**Comment by merdok** [comment]
http://www.merdok.org/miotspec/

**Comment by kimo790** [comment]
Thank you so much

**Comment by merdok** [comment]
I just described that above. You have to switch to the properties tab, check on the same service as the action (first number in action id) search for the piid specified in the action on or out section and you find the property description there.

If you have an action 2.3 and there is a in piid which says 2, the. You have to go to the properties tab and check property 2.2

**Comment by kimo790** [comment]
Thank you
