### ISSUE TITLE
Air Purifier specific settings advice

### ISSUE THREAD

**Issue by Hyejeongdd** [merdok/homebridge-miot#49]
Hi merdok, I used two MiAirPurifier2S which work well with miot. But the device info about temperature and humidity is not      unreliable. Can you add a plug or other options to block this value?

**Comment by merdok** [comment]
I mean why do you want to hide them? If the device reports unreliable values then just simply ignore them... Those items does not take any extra switches space on the group tile so that should not cause any issues.

**Comment by Hyejeongdd** [comment]
> I mean why do you want to hide them? If the device reports unreliable values then just simply ignore them... Those items does not take any extra switches space on the group tile so that should not cause any issues.

I found lots of document but still not find how to hide accessory in Homebridge, air purifier sensor is not a good so I think this ignore button need your help.

Regards!

**Comment by merdok** [comment]
Right now there are no plans to add a possibility to remove them.
