### ISSUE TITLE
Air Quality display bug?? on zhimi.airp.mb5, zhimi.airp.cpa4

### ISSUE THREAD

**Issue by Jern777** [merdok/homebridge-miot#490]
Hi,

First of all, appreciate your work really. 🙏

I have no Air Quality shown when "Show only the main accessory service" is ticked (preferred this to be ticked) while the only way for it to be shown is to untick the "Show only the main accessory service" but unfortunately will bring up 3 other controls for Screen - Brightness (Bright, Brightest, Close) which I do not want and can't figure out how to remove them.

The goal here is to show only the main accessory service + Air Quality / Humidity / Temp. That's it!

Thank you.

**Comment by Jern777** [comment]
Hi again, so basically setting the "screenControl" to false worked!

But unfortunately setting the "fanLevelControl" to false does not remove the fan level slider switch, any way to remove this as well? or may be I'm doing sth wrong. Thanks!

**Comment by merdok** [comment]
Fan level control is not the same as fan slider. The rotation speed control is part of the main service for air purifiers.

**Comment by Jern777** [comment]
Got it! All is working fine though.
