### ISSUE TITLE
loock.lock.t1pro

### ISSUE THREAD

**Issue by fbi007130** [merdok/homebridge-miot#491]
**Device model**
loock.lock.t1pro

**Device name**
Xiaomi Automatic Smart Door Lock

**Does the device require a MiCloud connection?**
Do not know_
It is a product of 2021.

**Anything special about the device?**
Device would be display in homekit after setting up in homebridge-miot plugin,but nothing could be done via homekit.
A home icon and not support would be show in homekit for this device.

**Comment by merdok** [comment]
According to the miot spec which you can check here http://www.merdok.org/miotspec/
there is no lock control, just some configuration options. Not sure if this is what you expect?
