### ISSUE TITLE
dmaker.fan.p221

### ISSUE THREAD

**Issue by FrankkX** [merdok/homebridge-miot#494]
**Device model**
_dmaker.fan.p221_

**Device name**
_Mi Smart DC Standing Fan (Battery Edition)_

**Does the device require a MiCloud connection?**
_No_

**Anything special about the device?**
_It seems to work by modifying the Device model code to “dmaker.fan.p220” in advanced settings. Hope to be able to add a button to control the vertical rotation like controlling the horizontal rotation in Homekit APP，instead of adding a switch to achieve_

**Comment by merdok** [comment]
My last status is that there is no native home kit way to control the vertical rotation, hence a dedicated switch is needed to control that function, so I think that it would be not possible.
