### ISSUE TITLE
Mi smart microwaveoven 

### ISSUE THREAD

**Issue by Sopyay3588** [merdok/homebridge-miot#500]
**Describe the bug**
_A clear and concise description of what the bug is._Oven mi home application is connect but cannot operate heat and other function 
when i operate heat or other function couldn't  sync device status error appear 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Your config.json**
_Provide the config.json entry for your device._

**Debug log**
_Provide a snippet of a debug log when the issue occurs. Ideally with the `deepDebugLog` property enabled._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Comment by Sopyay3588** [comment]
Hello Help me how to fix

**Comment by merdok** [comment]
Did you try to specify your mi cloud login details and set the forceMiCloud flag to true?
