### ISSUE TITLE
Add support for Aqara smart wall switch H1 EU (no neutral, single rocker)

### ISSUE THREAD

**Issue by denisgabriel5** [merdok/homebridge-miot#502]
**Device model**
`lumi.switch.l1aeu1`

**Device name**
Aqara smart wall switch H1 EU (no neutral, single rocker)

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
It currently doesn't work at all with the plugin. In my `Mi Home` I can start the pairing process, but at some point it says that is not compatible with my gateway (`lumi.gateway.mgl03 `).

**Comment by merdok** [comment]
It might be that it is a micloud only device. Did you try to specify your MiCloud credentials and set the `forceMiCloud` property to true?

**Comment by denisgabriel5** [comment]
I can’t because I don’t have its token or IP address.

**Comment by merdok** [comment]
Sorry, i do not understand how you are even trying to connect it if you are missing the ip address or token...
