### ISSUE TITLE
Support for yeelink.light.color7

### ISSUE THREAD

**Issue by yogesh-bansal** [merdok/homebridge-miot#503]
**Device model**
yeelink.light.color7

**Device name**
Mi LED Smart Control Bulb (B22)

**Does the device require a MiCloud connection?**
Yes
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
The light turning ON/OFF doesn't work, Neither do any other features associated with the light

[7/22/2023, 12:28:30 PM] [miot] [Light] Device found! Setting up miot device from local connection!
[7/22/2023, 12:28:30 PM] [miot] [Light] Connected to device: yeelink.light.color7
[7/22/2023, 12:28:30 PM] [miot] [Light] Doing initial property fetch.
[7/22/2023, 12:28:42 PM] [miot] [Light] Starting property polling.
[7/22/2023, 12:29:34 PM] [miot] [Light] Poll failed 4 times in a row! Stopping polling and trying to reconnect! Reason: Error: Call to device timed out

**Comment by merdok** [comment]
Ip or token is invalid or you did not setup your micloud account correctly in the plugin. Please recheck that!

**Comment by yogesh-bansal** [comment]
<img width="281" alt="image" src="https://github.com/merdok/homebridge-miot/assets/8408205/50ee2312-5400-4d78-9257-4df073ab7e98">
It has all the settings like IP and token etc but still turning on and off the light is not working.
Plus when I add devices a `Mi 360° Home Security Camera 2K Pro` camera is also added from my micloud account which i am able to turn on and off without any issue.

**Comment by merdok** [comment]
Then as already mentioned, you did not properly setup the micloud credentials in the plugin and also you need to enable the forceMiCloud property.

**Comment by yogesh-bansal** [comment]
Thanks, apparently I had the username with phone number and I was selecting `in` as the country for India and it was `i2`
