### ISSUE TITLE
Support for Aqara Zigbee Switches

### ISSUE THREAD

**Issue by TJT-JTJ** [merdok/homebridge-miot#505]
**Device model**
lumi.158d0002c7f0f8

**Device name**
Aqara D1

**Does the device require a MiCloud connection?**
Do not know
Runs through Mi Gateway

**Anything special about the device?**
I would like to get Alexa access to this device through Homebridge, the device natively supports Homekit through the Mi Gateway.

**Comment by merdok** [comment]
The specified device does not seems to have a miot spec so it will not work.
https://www.merdok.org/miotspec/?model=lumi.158d0002c7f0f8
