### ISSUE TITLE
Is it possible to add support for Mi Routers?

### ISSUE THREAD

**Issue by starthypelol** [merdok/homebridge-miot#506]
<img width="1135" alt="image" src="https://github.com/merdok/homebridge-miot/assets/140654276/f493593b-cd97-46d4-bde3-81ae7c3645d3">

**Device model**
Do not know

**Device name**
Xiaomi Router AX6000

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
Is it possible to support for its homekit mesh security functionality?

**Comment by merdok** [comment]
You need to tell me what is the device id so we can check if there is a miot spec for your device. If your router is in your mi cloud account then it should appear in the device list with the model.

**Comment by starthypelol** [comment]
ok this is the device model that I found xiaomi.router.ra72. The router is in my mi cloud but it doesnt appear in the device list, not sure if it's because of it's in chinese region?

**Comment by merdok** [comment]
Here is the miot spec of your device https://www.merdok.org/miotspec/?model=xiaomi.router.ra72

You should be able to control it over the plugin. You would need to check if there are any actions or properties which interest you, and then use customAccessory and propertyControl to expose what you want to home.

**Comment by starthypelol** [comment]
alright Thank you!
