### ISSUE TITLE
I get this error   throw er; // Unhandled 'error' even

### ISSUE THREAD

**Issue by rubengr** [merdok/homebridge-miot#508]
![homebridge](https://github.com/merdok/homebridge-miot/assets/6231423/2407050e-fc6e-4514-ab62-dd7e260cff72)

**Comment by merdok** [comment]
Probably an issue related to some other packages, maybe try to update nodejs?

**Comment by rubengr** [comment]
I have a new image installed in beaglebone and just tried to install this package in homebridge. I think i have all updated..

**Comment by merdok** [comment]
I think that the issue has something to do with your local environment, maybe some combination of packages or versions cause this, you would need to investigate. I cannot reproduce the issue on my machine...
