### ISSUE TITLE
Feature Request: Custom AC Temperature

### ISSUE THREAD

**Issue by TJT-JTJ** [merdok/homebridge-miot#512]
**Describe the idea or improvement**
I have a number of Mi/Aqara AC companions. These work great for control, but in the Home app the reported temperature is just the current set temperature of the AC, not the actual temperature. On Homebridge MIoT, I have a number of devices in the same room which are capable of reporting the temperature of the room. Primarily Mi Air Purifiers.

**Describe the solution you'd like**
It would be great if within miot setting pages I could select the temperature property of another device to replace the room temperature for the AC device within Home. This would significantly improve how the AC controller works in the Home app as it would correctly show ‘TEMP, cooling to SET TEMP’. 

An example of this would be within the miot settings, I could easily select an air purifier already in the same room and already set up with miot to have this device be the temperature reading for the AC, instead of just the ‘set temperature’.

**Additional context**
For the relatively recent Aqara AC Companion device, they achieve a similar thing natively with a linked zigbee temperature and humidity monitor. It would be nice if we could replicate something similar to this with devices already connected and reporting temperature within miot.

**Comment by merdok** [comment]
Thanks for the request.
So do I understand it correctly that you want to use the temperature value from another device to show it on the ac companion?
If not could you describe the use case more detailed?

**Comment by TJT-JTJ** [comment]
You've got it exactly right. If you see in the picture below it seems within HomeKit that there are two temperatures involved - the room temp and the 'set to' temp. So when the AC is on the thermostat (AC device) will show as say '27deg, cooling to 22deg'.

This way it would mimic how an actual AC/thermostat device works natively with HomeKit, plus mimic the significantly more expensive functionality of the native Aqara AC controller. Plus the temperature value of other devices in the same room is already right there within homekit-miot so it seems like it would be a great feature addition.

<img width="374" alt="image" src="https://github.com/merdok/homebridge-miot/assets/63647882/133797de-094c-40bf-a5ba-92e423cb5538">

**Comment by merdok** [comment]
Well currently that is unfortunately not easily possible as the devices run independently and do not about their existence. That would require some architectural adjustments. Would need to think about that first.
