### ISSUE TITLE
Ajout d'une minuterie et modification des noms des accessoires :

### ISSUE THREAD

**Issue by Stewart06** [merdok/homebridge-miot#523]
Bonjour,

Avant tout merci pour ce plugin et donc le travail que cela doit être pour un plugin si fonctionnel.

Depuis quelque mise à jour si je modifie le nom d'un accessoires par exemple le nom de la minuterie, et que je redémarre le plugin le nom d'origine reviens. C'est dommage car je prend plaisir a traduire les fonctionnalités de mes ventilateur par exemple.

Est-il possible de corriger cela ?

Deuxième point, je viens d'acheter le purificateur d'air zhimi.airp.cpa4 (Xiaomi Air Purifier 4 Compact), celui-ci n'as pas de minuterie directement il me semble, du moins je ne l'ai pas trouvé, il faut créer une automatisation directement. Cela est dommage je trouve, est-il possible que vous puissiez créer une minuterie au style ampoule comme c'est le cas pour les ventilateurs Xiaomi ?

Merci d'avance. 

Good morning,

First of all, thank you for this plugin and therefore the work that it must be for such a functional plugin.

Since some update if I modify the name of an accessory for example the name of the timer, and I restart the plugin the original name comes back. It's a shame because I enjoy translating the functionalities of my fans for example.

Is it possible to correct this?

Second point, I just bought the zhimi.airp.cpa4 air purifier (Xiaomi Air Purifier 4 Compact), this one doesn't have a timer directly it seems to me, at least I didn't find it, you have to create an automation directly. This is a shame I think, is it possible that you can create a light bulb style timer as is the case for Xiaomi fans?

Thanks in advance.

**Comment by merdok** [comment]
Hi,

yeah I am aware of the name disappearing issue. This is unfortunately related to HomeKit itself and not sure if I can do anything about it.

As for the timer, the device which you specified does not have a timer property in the miot protocol hence it is not appearing. The device simply does not support it.

**Comment by Stewart06** [comment]
Je comprends pour la minuterie c’est dommage qu’une telle fonctionnalité ne puisse pas être ajoutée.

Concernant les noms des accessoires qui changes à chaque redémarrage du plugin, il y a eu le même problème avec le plugin Tesla (certifié) ainsi que le plugin Samsung Tizen ou une option a pu être implantée pour laisser le choix de renommer les accessoires. Si cela peut vous aider à trouver la solution…


I understand about the timer it's a shame that such a feature can't be added.

Concerning the names of the accessories which change each time the plugin is restarted, there was the same problem with the Tesla plugin (certified) as well as the Samsung Tizen plugin where an option could be implemented to give the choice of renaming the accessories. If this helps you find the solution...

**Comment by merdok** [comment]
Yeah I might have a look at the naming as indeed that is a little bit odd but it might take a while till I have time to check it out.
