### ISSUE TITLE
yeelink.light.fancl6 issue

### ISSUE THREAD

**Issue by merv2k4** [merdok/homebridge-miot#524]
Hi Marcin,

Im having an issue with yeelink.light.fancl6. It was working previously, i did not notice but it stopped working.

It can detect the fan, but when i try to control the light or fan, it has no response. But I can control it in yeelight app.

I enabled the debug log but i cannot find the error when i it has no response

Below si the config for the particular fan
                {
                    "name": "L1 Balcony CFAN left",
                    "ip": "192.168.102.94",
                    "token": "1df155189a94fabe58a75c4aea30a743",
                    "pollingInterval": 10,
                    "propertyChunkSize": 1,
                    "deepDebugLog": true,
                    "buzzerControl": false,
                    "ledControl": true,
                    "childLockControl": false,
                    "modeControl": false
                },

Thanks

**Comment by merdok** [comment]
Hi,

I would guess that token or ip is invalid. Based on the info which you provided that could be the only reason.
