### ISSUE TITLE
Add dreame.vacuum.mb1808 

### ISSUE THREAD

**Issue by pzim-devdata** [merdok/homebridge-miot#527]
**Device model**
dreame.vacuum.mb1808

**Device name**
Mi Robot Vacuum-Mop

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
Already work with the plugin 

Close to the dreame.vacuum.mc1808

**JS**
[dreame.vacuum.mb1808.js.zip](https://github.com/merdok/homebridge-miot/files/12646266/dreame.vacuum.mb1808.js.zip)

**Comment by merdok** [comment]
Thanks for the file with support, will add as soon as I am back from  my travel!
