### ISSUE TITLE
How to get the dreame D10s pro token?

### ISSUE THREAD

**Issue by JonyBCN** [merdok/homebridge-miot#544]
I'm trying to add my Dreame D10s Pro vacuum cleaner to homebridge.
 Apologies in advance in case I missed something, but I don't know how to get the token. The guides refer to the Mi Home app, but the vacuum cleaner does not appear in the list of those supported by the app.
Consulting the documentation I have tried method 5 (Packet Sender Tool), but with no response from the vacuum cleaner.
 Can anyone give me any clues on how to obtain the token or get the integration to work? My final goal is to send the vacuum cleaner to each room using Siri.

**Comment by merdok** [comment]
The token is here the crucial part and there seems to be indeed some issues with newer Dreame devices, see here: #542
As i do not have a Dreame device i cannot do any direct tests on that, so somebody would need to help me here...

**Comment by JonyBCN** [comment]
Well, I've been digging through an ios backup hoping to find something like a SQL file with no luck.
  But searching the web I found this: [here](https://github.com/Tasshack/dreame-vacuum/issues/92#issuecomment-1402013393)
It seems that at some point the vacuum cleaner will be available in the MI HOME app and the token can be obtained.

**Comment by merdok** [comment]
Yeah, that is quite odd that dreame went this way, the previous devices were also directly in the mi home app...
