### ISSUE TITLE
Question: Property monitor and Roborock S8

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-miot#546]
If I issue a miot get_status command to my Roborock S8 I get the following:

`[{"msg_ver":2,"msg_seq":26,"state":8,"battery":100,"clean_time":84,"clean_area":835000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":1,"fan_power":106,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":204,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":385,"is_exploring":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":5,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":12,"mop_mode":302,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":4,"unsave_map_flag":0,"clean_percent":0,"rss":2,"dss":128}]`

I am asking myself now if there is a way to create a occupancy sensor for the "mop_forbidden_enable" value which changes whether the mop is attached or not (1 and 0). Couldn't figure it out.

**Comment by merdok** [comment]
Hi,
You would need to check the miot spec for your device here http://www.merdok.org/miotspec/ if the property exists in the spec. Based on that you can create a property monitor.

**Comment by CooperCGN** [comment]
Model ID is roborock.vacuum.a51, but from what I get as output it doesn't seem to be in there as a property. :(

Thank you very much for the quick answer.

**Comment by merdok** [comment]
Yeah, I guess your device uses the older miio protocol, and emulates the miot protocol over the cloud. Unfortunately xiaomi decided that they will not emulate all properties that way hence it is missing there probably...

**Comment by CooperCGN** [comment]
I don't know but the S8+ was just released this year and I have no cloud connection enabled for it.

**Comment by merdok** [comment]
Then I guess for some reason they devicded not to expose that property in the miot spec...
