### ISSUE TITLE
Not compatible with Mi Air Purifier Pro

### ISSUE THREAD

**Issue by ojoaosemtil** [merdok/homebridge-miot#55]
When I add the Mi Purifier Pro it shows only a switch to turn on or off, nothing more…it is the model zhimi.airpurifier.v7

I have a Mi Purifier 3C added and it works perfectly. There’s no support for the Pro version?

**Comment by merdok** [comment]
The zhimi.airpurifier.v7 is a miio device, hence it is not supported. I can add basic support for that device but it will require a MiCloud connection.

**Comment by ojoaosemtil** [comment]
It would be great to be able to do more than just on or off, do you think it is possible with a MiCloud connection?

**Comment by merdok** [comment]
Yes, MiCloud will be required!

**Comment by ojoaosemtil** [comment]
In that case, I use the credentials from the Mi Home app? Can you add support for this?

**Comment by merdok** [comment]
Yes, you will need to provide the same credentials as in the Mi Home app + the server country at which your device is located (china is the default so no need to specify that). Yes, i will add support for this device in the next update. 
You are in luck because I will publish an update later today so i can also include the device in it.

**Comment by ojoaosemtil** [comment]
Oh great! In my case my server is from Europe, I’m in Portugal, hope it works!
I’ll test it later today when you update!

**Comment by merdok** [comment]
Portugal i guess uses the Germany server, but not sure about that. You can check that in the Mi Home app in which country server your devices are on.

**Comment by ojoaosemtil** [comment]
In the Mi Home I choose Portugal in the country list, but it’s possible it is a server from other European country

**Comment by merdok** [comment]
Version 0.9.7 is now online with support for the device. Please try it and let me know!

**Comment by ojoaosemtil** [comment]
Thank you! I think it’s working fine, I’ll be testing this week. Thanks 😁

**Comment by ojoaosemtil** [comment]
So…it was working fine and today it showed no response..I tried to re-add it through the plug-in with no success, it is recognized but when specifying actions while running the plug-in it shows nothing.
Do you have any idea what it could be? I’m connected through mi cloud and the mi home app works fine.

**Comment by merdok** [comment]
You would need to provide some homebridge debug log in order for me to know what is happening.

**Comment by ojoaosemtil** [comment]
For some reason the device ID disappeared from the configuration, but I put it there again and it’s working!
