### ISSUE TITLE
Hot to get all properties from cloud for hhcc.plantmonitor.v1 device via miot cloud command?

### ISSUE THREAD

**Issue by mrmaximas** [merdok/homebridge-miot#551]
Subj.
Thanks!

**Comment by merdok** [comment]
Enter your device model here http://www.merdok.org/miotspec/

**Comment by mrmaximas** [comment]
Sorry, I mean to read the current values from mi cloud.

**Comment by merdok** [comment]
You have to use the miot cli to request the values from the cloud for specific properties.

**Comment by mrmaximas** [comment]
> You have to use the miot cli to request the values from the cloud for specific properties.

I don't understand the miot cloud command format, I couldn't find a manual how to request for specific value of specific device. please give me an example of such a command for request soil ec (2.2) for device ID: blt.3.1bl3btnhc5g00
http://www.merdok.org/miotspec/?model=hhcc.plantmonitor.v1

**Comment by merdok** [comment]
An example for a local request would be:
`miot send <IP> -t <TOKEN> get_properties '[{"siid":2,"piid":2}]'`
For cloud you would need to send the same request over the cloud cli tools

**Comment by mrmaximas** [comment]
> An example for a local request would be: `miot send <IP> -t <TOKEN> get_properties '[{"siid":2,"piid":2}]'` For cloud you would need to send the same request over the cloud cli tools

thanks, but i need example of command for getting same properties form the cloud. 
by the way my BLE devices does not have IP.

**Comment by merdok** [comment]
As mentioned, the same command applies to the cloud cli tools. You can type in the command in the terminal empty and it will show guide and show you on how to login and send the command.

**Comment by mrmaximas** [comment]
@NVR ~ % miot send 192.168.1.124 -t 46a999eaff49a308eb5b5f9f765e58 get_properties '[{"siid":2,"piid":5}]'
 INFO  Connecting to device at  192.168.88.124
 INFO  Device found! Sending command: get_properties [{"siid":2,"piid":5}]
 SUCCESS  Response from device -> [{"did":"333830665","siid":2,"piid":5,"code":0,"value":1}]

@NVR ~ %  miot cloud 192.168.1.124 -t 46a999eaff49a308eb5b5f9f765e58 get_properties '[{"siid":2,"piid":5}]'
@NVR ~ %
what i do wrong?

**Comment by merdok** [comment]
Did you even type `miot cloud` in the terminal and read the description there?
Anyway, the command should look like:
`miot cloud get-props '[{"siid":2,"piid":2,"did":"<DID>"}]'` 
where DID is the deviceId of the device which you are trying to get the properties from, you can use
`miot cloud list-devices` 
to get a list of device including their device ids

**Comment by mrmaximas** [comment]
It's works
Thank You!
@NVR ~ % miot cloud get-props '[{"siid":2,"piid":1,"did":"blt.3.1abh1244d2ee56"}]'
 INFO  Executing get_properties command over MiCloud country cn with params [{"siid":2,"piid":1,"did":"blt.3.1abh1244d2ee56"}] - timeout: 10000
 SUCCESS  Response from MiCloud -> [{"did":"blt.3.1abh1244d2ee56","iid":"0.2.1","siid":2,"piid":1,"value":87,"code":0,"updateTime":1701202460,"exe_time":0}]
@NVR ~ % miot cloud get-props '[{"siid":2,"piid":2,"did":"blt.3.1abh1244d2ee56"}]'
 INFO  Executing get_properties command over MiCloud country cn with params [{"siid":2,"piid":2,"did":"blt.3.1abh1244d2ee56"}] - timeout: 10000
 SUCCESS  Response from MiCloud -> [{"did":"blt.3.1abh1244d2ee56","iid":"0.2.2","siid":2,"piid":2,"value":1043,"code":0,"updateTime":1701202190,"exe_time":0}]
@NVR ~ % miot cloud get-props '[{"siid":2,"piid":3,"did":"blt.3.1abh1244d2ee56"}]'
 INFO  Executing get_properties command over MiCloud country cn with params [{"siid":2,"piid":3,"did":"blt.3.1abh1244d2ee56"}] - timeout: 10000
 SUCCESS  Response from MiCloud -> [{"did":"blt.3.1abh1244d2ee56","iid":"0.2.3","siid":2,"piid":3,"value":63,"code":0,"updateTime":1701202490,"exe_time":0}]
@NVR ~ % miot cloud get-props '[{"siid":3,"piid":2,"did":"blt.3.1abh1244d2ee56"}]'
 INFO  Executing get_properties command over MiCloud country cn with params [{"siid":3,"piid":2,"did":"blt.3.1abh1244d2ee56"}] - timeout: 10000
 SUCCESS  Response from MiCloud -> [{"did":"blt.3.1abh1244d2ee56","iid":"0.3.2","siid":3,"piid":2,"value":17.8,"code":0,"updateTime":1701202239,"exe_time":0}]

**Comment by mrmaximas** [comment]
@merdok it's possible to get multiple values at ones via miot cloud get-props command?

**Comment by mrmaximas** [comment]
> @merdok it's possible to get multiple values at ones via miot cloud get-props command?

found issue with _miot cloud list-devices_ command - ble devices not listed.
![Screenshot 2023-12-05 at 20 11 36](https://github.com/merdok/homebridge-miot/assets/61165387/f7961004-1074-41df-9816-ad858ab6d02b)

**Comment by merdok** [comment]
Yes it is possible,` {"siid":2,"piid":2,"did":"<DID>"}` is one section you can add multiple of those comma separated.

About the micloud list devices, yeah i guess i had an filter for that initially because those were not working, i guess that can be removed now! Thanks for reminding me😅

**Comment by merdok** [comment]
Ah, there is already a flag for that, you should try -> `micloud list-devices --showAll=true` that should show all the devices

**Comment by mrmaximas** [comment]
> Ah, there is already a flag for that, you should try -> `miot cloud list-devices --showAll=true` that should show all the devices

it's works, thanks! have you another secret keys? ;)
