### ISSUE TITLE
Mi LED Smart Color Bulb (B22)

### ISSUE THREAD

**Issue by alx-xlx** [merdok/homebridge-miot#552]
**Device model**
yeelink.light.color7

**Device name**
Mi LED Smart Color Bulb (B22)

**Does the device require a MiCloud connection?**
Probably Yes

**Anything special about the device?**

- It only works with the "Mi Home" app. 
- I have no idea why the device country comes out to be "us" instead of "in"
- The Bulb is connected to my Router via WiFi and has 192.168.0.161 reserved via MAC-ADDR
- The device shows up on the "Home app" marked as "All Off", and when the hombridge is down then the device is marked as "unavailable"
- And the switches doesn't turn on or off

Discovering devices
![](https://i.imgur.com/V15SObv.png)

upon homebridge restart I get the following logs
![](https://i.imgur.com/kk4mULv.png)

upon running `miot test` I get the following logs
![](https://i.imgur.com/lXGgsuI.png)

three accessories gets added but they don't work
![](https://i.imgur.com/HTKxryz.png)

upon adding force micloud connection in the plugin settings I get the following logs
![](https://i.imgur.com/Nloq8ix.png)

**Comment by merdok** [comment]
Hi,
the yeelight devices usually use a could connection hence foreMiCloud should be used.
The device need to be added in your mi home app and you should be able to co tell it from there, afterwards it should also work with the plugin.

**Comment by merdok** [comment]
The miot test only tests a local connection using the miot protocol.
A handshake timeout usually indicated an incorrect token.

For the cloud connection to work the device needs to be added to your account using the xiaomi home app and actually be online.

**Comment by alx-xlx** [comment]
I double checked the token and its what the micloud shows when I use the Discover button.
I have also added the device to xiaomi home app and the device works fine with the home app. All the devices are connected to the same wifi internet access point. And the home app works fine.

I guess this won't work for some reason
anyways thanks for the help,
