### ISSUE TITLE
Question: How does the "New 'contains' value operator" work?

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-miot#556]
This is actually what I am looking for but how I actually set this up in my config.json?

For example I want to check towards different values for the status of my vacuum. For a single value my entry would look like this:

```
"propertyMonitor": [
                {
                    "property": "vacuum:status",
                    "name": "Paused",
                    "value": 10,
                    "valueOperator": "equal"
                }
            ]
```

How do I set up the values parameter?

**Comment by merdok** [comment]
You have to specify an array (list) as calue. Something like that:

```
"propertyMonitor": [
                {
                    "property": "vacuum:status",
                    "name": "Paused",
                    "value": [10,11,12,13,14],
                    "valueOperator": "equal"
                }
            ]
```
Any of those values specified in the array will then trigger the given property.

**Comment by merdok** [comment]
As in my example and the documentation `contains`

**Comment by CooperCGN** [comment]
Thank you, awesome. That feature is reducing my automations a lot.
