### ISSUE TITLE
Integrate Roborock S5

### ISSUE THREAD

**Issue by T-Bone90** [merdok/homebridge-miot#557]
Hello everyone,
I wanted to insert my Roborock S5 with the great plugin, but it only worked to a limited extent. I would like to add a second "Pause" switch and a "Where am I" switch. But I couldn't find any action buttons or anything like that.
Are there any instructions on how to implement all of this?

Thanks in advance

**Comment by merdok** [comment]
hi, not sure what the issue is, but you probably have to enable the `actionButtons`

**Comment by T-Bone90** [comment]
I would like to have 2 extra buttons next to the start/stop.

Yes, thanks, but how do I find out which action buttons I can use? Or where do I get the variables? I read the readme but couldn't find anything.

**Comment by T-Bone90** [comment]
Thank you so much!
