### ISSUE TITLE
yeelink.light.color5 turn off issue

### ISSUE THREAD

**Issue by Semir333** [merdok/homebridge-miot#558]
Hello. I use many of the Xaiomi Essential Bulb in my home (yeelink.light.color5) and the included plugin have a very annoying issue.
The plugin took 2 switches and one bulb to the Homekit, and you can't turn off the bulb with slider (stay on in 1%) , and also not turn off if you turn off colour or day mode. Evrey time you need to go trough the menus and go in the bulb and push on it to turn off.

I could give any data, photo, video from the problem if needed.

**Comment by merdok** [comment]
Hi, sorry, I am not quite sure what you mean. Could you try to explain it more detailed?

**Comment by Semir333** [comment]
Yes of course. 
Here you see a normal homekit added plugin for the yeelink.light.color5. When you try to turn off with the slider, the light is not turning off as at showed, when you refresh it goes back to 1% and the light not turned off in real also. When you try to turn of example color mode, the light also not turn off, the switch going back to on.

![Képernyőfotó  2023-12-23 12 37 49 jpeg](https://github.com/merdok/homebridge-miot/assets/76537009/2e32d352-d5c4-449c-b1ab-b419650d47aa)


[RPReplay_Final1703331667.zip](https://github.com/merdok/homebridge-miot/files/13758908/RPReplay_Final1703331667.zip)
Video from the problem.

**Comment by Semir333** [comment]
If you need anything more i'm open to help, and show or send anything about this what you want.

**Comment by merdok** [comment]
Probably, the lamp only supports brightness with a value range of 1-100%, if that is the case then this is a normal behavior.

**Comment by Semir333** [comment]
Okay, thanks the info. By the way i want to tell it’s very user unfriendly to use. Could be add a button to turn off the light somehow, or the slider 0-position marked to turn off? Evrey time you need to go torugh the lamps to turn off. Thats very amnoying. Or make choosable the Color/day button to show to make the Light turnable without mess up the screen with a lot of Day/color buttons if you unmerge the Light bulb.

Thank you!

**Comment by merdok** [comment]
If you need an extra switch for turning on/off the lamp then you do that by yourself. The plugin is fully customizable.
You can just simply make a `propertyControl` on the `light:on` property and that should make such a switch appear.
