### ISSUE TITLE
Roborock S5 Vacuum gets a "lamp" icon in Apple Home app and not an Vacuum icon

### ISSUE THREAD

**Issue by phattrance** [merdok/homebridge-miot#560]
Does anyone know why via this plugin, my roborock S5 vacuum gets a "lamp" icon in apple home, instead of a Vacuum icon?

Is there a way to fix this? i couldnt see it any setting for this in the plugin settings, and apple home only allows me to change the icon to "controls", "lamp", or "fan", but vacuum is missing.

**Comment by merdok** [comment]
HomeKit does not support Vacuum devices hence the plugin needs to emulate that behavior with the available accessories which in that case is a lamp or fan.
