### ISSUE TITLE
Feature Request: Multiple states

### ISSUE THREAD

**Issue by Willian-Zhang** [merdok/homebridge-miot#561]
**Describe the idea or improvement**
turns this (3 modes: manual, auto, sleep)
<img width="487" alt="image" src="https://github.com/merdok/homebridge-miot/assets/5165840/da60fa1f-5ecd-4bdb-b7c2-d8e3a0591ab4">
into something more like this
<img width="539" alt="image" src="https://github.com/merdok/homebridge-miot/assets/5165840/ab6547a6-869b-4922-ae12-a28d7cb7c471">
or this 
![image](https://github.com/merdok/homebridge-miot/assets/5165840/13d40360-3564-48ee-b6f4-02827826bdaf)

**Describe the solution you'd like**
Merge states with same key into multiple state UI multiple choice or a big switch that supports multiple state (I'm not sure what those kind of UI would be, but I have saw them on different native HomeKit devices) 

**Additional context**

**Comment by merdok** [comment]
Hi,

unfortunately this is not possible that easy. I have already investigated that possibilities.

For the first screenshoot I would need to make the accessory a TV which does not really makes sense that for example a fan will be displayed as a TV.
For the second screenshot it is not possible to rename the buttons which would also be confusing as you do not know which mode is actually selected.

As far as I know there is currently no better way to display multiple states as simply with multiple switches...

**Comment by Willian-Zhang** [comment]
how about an option to make them like this:
<img width="1143" alt="image" src="https://github.com/merdok/homebridge-miot/assets/5165840/ac32965c-8b15-4199-a422-c2a420af83be">

**Comment by merdok** [comment]
There is also no way to change the labels or even the amount of displayed options!
As you see unfortunately the home app is currently quite the limiting factor for a much better UX😅 We can only hope that Apple will improve that in future...

**Comment by hejsiri** [comment]
@merdok Cześć. Jak mogę się z Tobą skontaktować? Robię taki fajny projekt z Shelly API cloud i do niego potrzebuje przerobić plugin który już jest na gicie. www.teslagarage.app. Chce to po prostu dodaj do HK przez HB.

**Comment by merdok** [comment]
@hejsiri discord albo x

**Comment by hejsiri** [comment]
> @hejsiri discord albo x

Na X nie można wysłać do Ciebie wiadomość. FB lub @ ?

**Comment by Willian-Zhang** [comment]
Hi @merdok, I want to ask if this is still possible in 2025?
Here is what one of my native Air purifier looks like.

![Image](https://github.com/user-attachments/assets/3b64050b-7d17-4da3-bc87-ec1d49a3fd71)
![Image](https://github.com/user-attachments/assets/a1737a55-2365-4c72-a181-cfa4950808a8)

and the original one still looks a bit awful in compare.

I think I can even give up on options that I can use on HomeKit, just to make it look better.
