### ISSUE TITLE
Bridge pair fail

### ISSUE THREAD

**Issue by Semir333** [merdok/homebridge-miot#562]
**Describe the bug**
After years of work, the bridge is stopped it self, and not work anymore. Homepod restarted, Icolud turned off/on, whole system reseted include homebridge, plugin, Applehome kit, and still can't add the bridge for MioT plugin ONLY!!! Evrey other HB plugin works. Plugin up to date.

**Your config.json**
Nevermind before it works, not configured. The problem happend in daily use, not config.

**Debug log**
Evreything works in HB admin site, evrey accessories only the bridge pair is not working. First appear in the accessories, after say can't pair. Again try, say bridge paired to another home (what is a lie) and plugin said it's paired, but in real it's not paired at Home app. Than disappear until i reset the whole system.

**Comment by merdok** [comment]
Sorry i do not understand your issue. Could you explain more better? What device are you using and what are you trying to do?

**Comment by Semir333** [comment]
> Sorry i do not understand your issue. Could you explain more better? What device are you using and what are you trying to do?

I try to add miot child bridge to the homekit, but it said "Accessory not compatible" then miot bridge is disapear from "Add new accessory". If i try to add again from QR it said already added, but it wont! The plugin works from HB Admin Accessory tab. But the bridge can't add directly to Homekit. I reseted evreythin,uninstall evreything include Apple side nad HB side, nothing solve this issue. 4 hours ago all of my 39 devices working properly, than rnadomly all of my devices not respond and not work anymore. Any other plugin works properly, and can be add to Homekit, only Miot bridge not work. I haven't any idea what can i try more.

**Comment by merdok** [comment]
Sorry I am not aware of any such issue, but seems like you are having a problem with homebridge and not this plugin itself. This plugin has nothing to do with child bridges and other stuff related directly to homebridge...

**Comment by Semir333** [comment]
A full reimaged reset and reinstall or HB system helped. Now i can add, but i don't know what can be cause a problem like this, without any pre issue. And only for this plugin. It's intresting for me...

**Comment by merdok** [comment]
Glad to hear that it works again! Thanks for letting me know!
