### ISSUE TITLE
Dreame D10 Plus

### ISSUE THREAD

**Issue by JordanLa89** [merdok/homebridge-miot#566]
Good morning

I have a problem getting my Dreame D10 plus robot to work in homebridge.

I managed to find the id and token, it also adds to Homekit.

But I can't do anything.
I tried to add actions via MIOT SPEC but nothing.

I have this as a config, I took audio as an example.

--------

{
"name": "DreameBot D10 Plus",
"ip": "192.xxxxxxx6",
"token": "78xxxxxxxxxxxxx503379",
"deviceId": "72xxxxxxxx1",
"model": "dreame.vacuum.r2205",
"pollingInterval": 10,
"deepDebugLog": false,
"buzzerControl": true,
"ledControl": true,
"childLockControl": true,
"modeControl": false,
"actionButtons":[
{
"action": "audio:position",
“name”: “audio”
}
]
}

------

Thank you for your help :)

I'm French, sorry for my English...

**Comment by merdok** [comment]
Hi, you have validate if your token and ip are correct. For that you can easily use the cli command `test`. Have a look here https://github.com/merdok/homebridge-miot?tab=readme-ov-file#troubleshooting

**Comment by JordanLa89** [comment]
It's a bad start :s

I did the test with my IP and my token in the terminal:

Here is the answer

bash: syntax error near unexpected token `newline'
