### ISSUE TITLE
zhimi.airp.mea1 support

### ISSUE THREAD

**Issue by viventus** [merdok/homebridge-miot#568]
Device model
zhimi.airp.mea1

Device name
Xiaomi Smart Air Purifier Elite

Plz add support for this device. Need toggles for Plasma and UV lamp

**Comment by merdok** [comment]
Does the device not work? What is the exact issue?
If you need those specific stuff exposed then you should use `propertyControl` to add them.

**Comment by viventus** [comment]
> Does the device not work? 
Device is working as expected, but i tried to add options for UV lamp/Plasma and failed.

I dont know excact property for seting propertyControl

**Comment by merdok** [comment]
You have to check the properties for your device here: https://www.merdok.org/miotspec/?model=zhimi.airp.mea1
