### ISSUE TITLE
how to establish  connection if the plug and homebridge are not in the same subnet ?

### ISSUE THREAD

**Issue by douglasleft** [merdok/homebridge-miot#57]
Plug ip:192.168.10.8
homebridge ip :192.168.20.100

The networks of the two subnets are connected.
but the homebridge must have the IP 192.168.10.xx to connect to the plug. 
and after the connection is established, it still works if I delete the IP.

**Comment by merdok** [comment]
I think you have to move both of them into the same subnet. Not sure if the miio package, which I use for the connection to the device, can specify to connect to a different subnet...
