### ISSUE TITLE
Kettle only responds after turning on then off and on again

### ISSUE THREAD

**Issue by Movieaholic** [merdok/homebridge-miot#570]
I have a smart kettle 2 pro and it works perfectly apart from this one issue.  I have to toggle on then off and it will respond as it should for a while,  I havent tested exactly how much time but im not sure why that first time i have to toggle it on off then on again to get it to work?

**Comment by merdok** [comment]
Well, you would have to provide some [debug log](https://github.com/merdok/homebridge-miot?tab=readme-ov-file#troubleshooting) so i can check if the connection is ok.

**Comment by Movieaholic** [comment]
I enabled deep debug logs but nothing shows on the plugin logs screen some logs from the plugin show on the main log screen but not debug logs and also when the kettle does turn on and of nothing is shown on the main log screen
![Screenshot 2024-02-05 213748](https://github.com/merdok/homebridge-miot/assets/61401734/e003f08a-e361-4d06-8aef-0ee5aa86aa9f)
![Screenshot 2024-02-05 213944](https://github.com/merdok/homebridge-miot/assets/61401734/c12d512b-148c-4ad2-b8f7-dfd6afbf674d)
![Screenshot 2024-02-05 214156](https://github.com/merdok/homebridge-miot/assets/61401734/f041bc55-3ff4-4893-9181-9d61774007be)

**Comment by merdok** [comment]
Please read the linked section carefully! For it to take effect you have to start homebridge in debug mode.

**Comment by Movieaholic** [comment]
If i turned it on and waited for HomeKit to update naturally i could keep turning it on with nothing happening it doesnt actually turn the kettle on untill i turn it on then off then on again 
[Miotlogs.txt](https://github.com/merdok/homebridge-miot/files/14177258/Miotlogs.txt)

**Comment by merdok** [comment]
The logs look fine, there are no connection errors or other issues. I guess this how the device behaves.
What is the exact device model of your device? It is usually written in the logs during startup so i can check the spec here https://www.merdok.org/miotspec/ to check how it behaves.

**Comment by Movieaholic** [comment]
![IMG_0709](https://github.com/merdok/homebridge-miot/assets/61401734/9b1fded2-2a35-4ab9-ac22-03923ac82243)

**Comment by merdok** [comment]
The device model must be wrong which you entered.

**Comment by Movieaholic** [comment]
![Screenshot 2024-02-07 064144](https://github.com/merdok/homebridge-miot/assets/61401734/2eec70c7-8d04-476f-b81f-883e270e5c81)

**Comment by merdok** [comment]
You must had a typo in the model as it indeed works:
https://www.merdok.org/miotspec/?model=yunmi.kettle.v19

It looks fine so I guess this is how the kettle behaves.
I actually want to also buy this kettle but I am waiting for the official Europe release. After I get it myself then I can validate if it works as expected.

**Comment by Movieaholic** [comment]
Yeah sorry my error, im not to sure what you mean by this is how the kettle behaves? It turns on fine every time with the mi app.

**Comment by merdok** [comment]
Every device behaves differently, some need special handling which might be the case for the kettle. Without having access to the actual device it is hard to tell...

**Comment by Movieaholic** [comment]
Ok thanks
