### ISSUE TITLE
xiaomi-derh-13l support 

### ISSUE THREAD

**Issue by bkchaw** [merdok/homebridge-miot#571]
**Device model**
xiaomi-derh-13l

**Device name**
Mijia Smart Dehumidifier 13L

**Does the device require a MiCloud connection?**
don't think so

**Anything special about the device?**
does not work. 

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:dehumidifier:0000A02D:xiaomi-13l:1

**Comment by merdok** [comment]
What does the log say? Did you try the connection test from the cli? https://github.com/merdok/homebridge-miot?tab=readme-ov-file#troubleshooting
