### ISSUE TITLE
Reset sensor names after homebridge reboot

### ISSUE THREAD

**Issue by grzech1991** [merdok/homebridge-miot#572]
Hi,

I have a problem - after changing the name of the sensor in the home app, homebridge does not remember it - after a reboot it is restored to default to Temperature. The same problem applies to humidity sensors.

As long as I do not perform a reboot homebridge is ok.

![Zrzut ekranu 2024-02-09 201611](https://github.com/merdok/homebridge-miot/assets/99332031/b2c80793-17b5-4aba-893a-17888417334c)

I am writing about the configured name option

**Comment by merdok** [comment]
Hi, yeah I am aware of that. The issue is that there is a bug in the home app and previously after a reboot all the accessories had the same name and each of them had to be renamed automatically. So I changed that to the current behavior, which is also not optimal but a better one than before. In order to manually store the name I would need to do some re-writing of the plugin, just not sure when I will have the time to tackle that...

**Comment by grzech1991** [comment]
Ok thanks, that means this is normal behavior. Is there possibly a halfway solution to default the sensors to names such as:

Temperature Humidifier
Temperature Purifier

Or that they can be edited in the json file? Although I guess that doesn't change anything.

Another option, is it possible to delete them? E.g. by unchecking?

You know, I'm thinking of such half-hearted solutions.

**Comment by merdok** [comment]
Yeah for now this is a normal behavior. You can use the suppressAutoServiceCreation property if you wish to disable some of them.

**Comment by grzech1991** [comment]
Can you write me how to do it or is there any instruction on the web? I am closer to an administrator than a programmer

**Comment by merdok** [comment]
Just check the documentation, the property is described there.

**Comment by mrmaximas** [comment]
@merdok hi! Is there any news on resolving this issue? Every time after restarting HB, I have to rename the temperature sensor of `zhimi.airfresh.ua1` from `Temperature` to `Inlet`. Is there a way to hard set the sensor name through the config?

**Comment by mrmaximas** [comment]
@merdok Thank you! This is not something you need to apologise for. I am grateful to you for giving me and thousands of people the opportunity to control  Mi devices in HomeKit. 🙏🏻 All the best, and have a good evening!
