### ISSUE TITLE
Some new MIOT devices need to be supported

### ISSUE THREAD

**Issue by bbluvgg** [merdok/homebridge-miot#575]
**Device model**
xiaomi.esteamer.mes01

**Device name**
Mijia Smart Food Steamer 12L

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
This is a new kind of electric steamer device , Is there a way to add it to HomeKit? Just set the mode "optional" and support setting the working hours
---------------------------------------------------------------------------------------------------------------------------------------------------
**Device model**
xiaomi.blanket.mj2

**Device name**
Mijia Smart Water Heating Blanket

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
This is a new kind of electric blanket device, and it is expected that it can use the HomeKit Thermostat controller with a temperature setting range of 25-55°C. It would be nice to be able to show the water temperature as well as the water level.
---------------------------------------------------------------------------------------------------------------------------------------------------
**Device model**
mrbond.airer.m1s

**Device name**
Mr. Bang electric Airer

**Does the device require a MiCloud connection?**
YES

**Anything special about the device?**
Nothing special, would love to work with cover controls, including pause, up, down, and an extra light
--------------------------------------------------------------------------------------------------------------------------------------------------
**Device model**
bj352.airp.y106m

**Device name**
352 Air Purifier Y106

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
Currently it works in compatibility mode, fan_level can only work with switch controls, which will generate 5 switches, which is very cumbersome and not good-looking.I don't have other air purifiers as an example, so don't know how you deal with this.
--------------------------------------------------------------------------------------------------------------------------------------------------
Thank you very much again for your job！

**Comment by merdok** [comment]
Did you already try to add the devices to the plugin? Do they work? What kind of issues are you facing?

**Comment by merdok** [comment]
1. It probably requires a micloud connection so you can try to use the forceMiCloud property.

2. and 3. Do not have dedicated accessories as those are minor devices so you could try to use the propertyControl property to expose any functionality that you need.

4. You can try to use the modeControl property or if that does not work you  can also use propertyControl to expose the wind speed functionality.
