### ISSUE TITLE
Requesting Xiaomi Mi Smart Video Doorbell 2 Lite support

### ISSUE THREAD

**Issue by DamienSilvert** [merdok/homebridge-miot#578]
**Device model**
madv.cateye.miowlv2l

**Device name**
Mi Smart Video Doorbell 2 Lite

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
The plugin detects it as a motion sensor, but nothing works, if i try to force MiCloud connection it says its not reachable.

**Comment by merdok** [comment]
You would need to put a debug log. Also if you expect the video feed to work then that will currently not work.

**Comment by DamienSilvert** [comment]
Thank you for the fast reply, how can i generate that debug log? About the video feed, i do not need a real time feed, i was thinking more about receiving the small video clip it generates when someone press the button o at least a snapshot.
