### ISSUE TITLE
Air Purifier: "Fan Level - Level1" trigger doesn't go OFF in Auto Mode

### ISSUE THREAD

**Issue by dmndrz** [merdok/homebridge-miot#58]
Hi!

There is a little annoying thing despite the perfect plugin you've created!
When the air purifier is switched in Auto Mode, the Level1 fan speed trigger stays ON instead of going OFF, so it's impossible to switch to Level1 from Auto Mode.

<img width="659" alt="Capture d’écran 2021-07-07 à 19 25 40" src="https://user-images.githubusercontent.com/18632343/124803216-1efe5580-df59-11eb-9d15-693517d12e4d.png">

And it's the same with Night Mode / Level1.

I don't know if my explanation is clear 😅.

**Comment by merdok** [comment]
Hi,

I understand what you mean. But in fact the air purifier still  reports level1 as the current fan level so this is simply displayed in the ui.  But maybe i can adjust this. So only when switching the air purifier to auto mode the fan levels should be inactive? At which modes you can use the fan levels?

**Comment by dmndrz** [comment]
> So only when switching the air purifier to auto mode the fan levels should be inactive?

Yes, I think so. And with the Sleep mode too. Then it would be possible to trigger the Level1 when it's on Auto mode or Sleep mode.

> At which modes you can use the fan levels?

I believe it has to be paired with Manual mode (the one you named "None"), because when you trigger this, the last level you chose (1, 2 or 3) is activated.

**Comment by merdok** [comment]
Ok, i understand the issue now. Unfortunately i cannot do a quick fix for that since currently the fan level is bound to the power state of the device, i would need to come up with a new concept of also including the mode into that for some devices...
I will try to think of something and fix that, but not sure if i can do that already for the next update...

**Comment by merdok** [comment]
Should be fixed in version 1.0.0
