### ISSUE TITLE
Air Quality sensor problem

### ISSUE THREAD

**Issue by ktahatastan** [merdok/homebridge-miot#583]
Air Quality sensor not visible on air purifier devices, when I enable "Show main accessory only" the sensor disappears from the home app. This setting must be made in the general settings of the device, just like the temperature and humidity sensor settings. I can't see anything about air quality right now. I would be very happy if it is developed.

**Comment by merdok** [comment]
The main accessory on a fan device is obviously the fan, that means when you use "Show main accessory only" it will only show the fan. If you want to keep it that way then you can use `propertyControl` to expose the air quality manually.

**Comment by merdok** [comment]
Just have a look at the README, you have the property documented and examples there.

**Comment by ktahatastan** [comment]
> Sadece README'ye bir göz atın, orada belgelenmiş özelliğiniz ve örnekleriniz var.

I think I discovered how to do it with a few tries. It would be great if a select box was developed where we can choose the sensor type instead of a fixed light sensor. thank you for your help.

**Comment by merdok** [comment]
There is some auto logic to determine the type of the accessory but that is not always perfect.
