### ISSUE TITLE
yeelink.light.lamp22 (Xiaomi Mi Computer Monitor Light Bar 1S) does not work

### ISSUE THREAD

**Issue by JJ-HYK** [merdok/homebridge-miot#585]
The device can be connected to the home kit, but it does not respond when operated by the home kit.

**Comment by merdok** [comment]
Do you use a local connection or over the cloud? It might be that the device is not a miot device hence in that case it would be required that you connect over the cloud.

**Comment by JJ-HYK** [comment]
The light bar is connected to the Mi Home, so I think it is a miot device.
I can normally control the light bar with the Mi Home app.

The device appears in the Apple Home, but it doesn't show the current state of the device (It is always shown OFF), and also I can't control it.

I have other devices (eg. Xiaomi Smart Standing Fan) connected to this plugin, and they normally works in the Apple Home.
What should be the problem here?

**Comment by merdok** [comment]
My recommendation is that you try to use the MiCloud for the device by specificinf your micloud credentials in the config and setting the flag `forceMiCloud` to true, and check if that helps.

**Comment by JJ-HYK** [comment]
Wow.. It DOES works with the micloud. Thank you for the help!!!
