### ISSUE TITLE
Temporary disable added device

### ISSUE THREAD

**Issue by mishablokhin** [merdok/homebridge-miot#586]
Hello!
It would be great to have option to temporary disable added device. For example, i have Xiaomi MiHumidifier which is being used during winter period. For now it's offline for a long time and HomeBridge trying to get it state every few seconds. Only one option to fix that - remove device.

**Comment by merdok** [comment]
How would you expect to be able to disable the device? Through a config entry or using a switch?

**Comment by merdok** [comment]
Yeah, i would need to think about it. I will see what i can do.

**Comment by mishablokhin** [comment]
> Yeah, i would need to think about it. I will see what i can do.

Thanks a lot! This would be great! Because this messages are really annoying :) 
<img width="672" alt="image" src="https://github.com/merdok/homebridge-miot/assets/25735019/da701a8e-dbc3-4fe2-8604-0ac77de1244b">

**Comment by merdok** [comment]
Added a new `deviceEnabled` property in version 1.7.1 which allows you to disable a device using the config. Hope that satisifes you :)
