### ISSUE TITLE
support for xiaomi water dispenser

### ISSUE THREAD

**Issue by hnitch** [merdok/homebridge-miot#588]
**Device model**
Xiaomi Mijia Smart Hot & Cold Water Dispenser 3L C1 2023
**Device name**
Xiaomi Mijia Smart Hot & Cold Water Dispenser 3L C1 2023

**Does the device require a MiCloud connection?**
No/not sure works on wifi

https://aihome.com.my/product/mijia-intelligent-hot-and-cold-water-dispenser/

**Comment by merdok** [comment]
Did you already try to add the device? What is not working currently?
