### ISSUE TITLE
Request of new device support of Xiaomi Smart Lightstrip Pro

### ISSUE THREAD

**Issue by yikchunnnn** [merdok/homebridge-miot#589]
**Device model**
_philips-strip3:3_
_(https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:light:0000A001:philips-strip3:3)_

**Device name**
_Xiaomi Smart Lightstrip Pro 米家追光氛围灯带_

**Does the device require a MiCloud connection?**
_Do not know_

**Anything special about the device?**
Not tried yet, but I guess no, cause no similar device (philips-strip) is found on the supported device list

**Comment by merdok** [comment]
You should try to add the device and see if it is working or not, or what features does not work. The supported device list is just for devices which were tested and have dedicated device modules, you should consider it as a reference but many other devices will also work out of the box.
