### ISSUE TITLE
支持洗衣机识别洗衣完成状态

### ISSUE THREAD

**Issue by zwb124** [merdok/homebridge-miot#591]
我有小米的洗衣机和aqara的不支持米家的晾衣杆，我想实现洗完衣服晾衣杆自动下降，但是在家庭里无法得到洗衣完成状态，哪位大神有解决办法吗？

**Comment by merdok** [comment]
Sorry, i do not speak Chinese. You would need to write your question in English...

**Comment by zwb124** [comment]
I have a Xiaomi washing machine and a non Xiaomi clothes drying pole. I want to achieve automatic descent of the clothes drying pole after washing, but in Apple's home, I cannot obtain the complete washing status. Does anyone have a solution?

**Comment by merdok** [comment]
Not quite sure what you mean, but it would be good if you provide the model names of the devices so at least i can have a look at the miot spec.
