### ISSUE TITLE
zhimi.airp.meb1 - Xiaomi Smart Air Purifier Elite: Not working

### ISSUE THREAD

**Issue by rgreco87** [merdok/homebridge-miot#593]
**Device model**
zhimi.airp.meb1

**Device name**
Xiaomi Smart Air Purifier Elite

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
Device appears into Apple Home app but it doesn't work: it can't be turned on/off, it can't monitor Quality/Temperature/Humidity.

>{
    "platform": "miot",
    "devices": [
        {
            "name": "Purificatore Salotto",
            "ip": "192.168.0.20",
            "token": "----------",
            "deviceId": "----------",
            "model": "zhimi.airp.meb1",
            "pollingInterval": 10,
            "micloud": {
                "username": "-----------",
                "password": "-----------",
                "country": "de",
                "timeout": 5000
            },
            "filterChangeThreshold": 5,
            "fanLevelControl": false,
            "pm25Breakpoints": [
                5,
                12,
                35,
                55
            ],
            "propertyControl": [
                {
                    "property": "air-purifier:plasma",
                    "name": "Tecnologia al Plasma"
                },
                {
                    "property": "air-purifier:uv",
                    "name": "Tecnologia UV"
                }
            ],
            "screenControl": false,
            "buzzerControl": false
        }
    ]
}

**Comment by merdok** [comment]
What does the debug log say? Are there any errors? Maybe the token is wrong, also if you want to use micloud you have to set the forceMiCloud property also to true.

**Comment by rgreco87** [comment]
@merdok never mind, I didn’t change the IP address 😅 sorry
