### ISSUE TITLE
New device Xiaomi X20+

### ISSUE THREAD

**Issue by satrik** [merdok/homebridge-miot#594]
**Device model**
xiaomi.vacuum.c102gl

**Device name**
Xiaomi X20+

**Does the device require a MiCloud connection?**
Don't know

**Comment by merdok** [comment]
Hi, what is the issue with the device? Did you already try to add it to the plugin? What does the debug log say?

**Comment by satrik** [comment]
Hey, I've added it today and still need to test it. 
But I mostly use the cli and there I need to figure out again how the room cleaning works. It is not the same like for my old X10+ -.- The room settings seem to be the same, but the actual start cleaning ignores the selected rooms. Need to setup an Android emulator again to get the logs and I will write my findings here

**Comment by merdok** [comment]
yeah you would need to catch the actual command sent to the device to find out how it should look like

**Comment by t0mmey** [comment]
@merdok I also tried to add it and its getting added though in Homebridge if I simply turn it on it doesn’t react at all. This is what my Homebridge Log says:
![IMG_0048](https://github.com/user-attachments/assets/7d44f5df-d2bb-4600-b4f3-2289d0631fe3)

Do I may need to change something in the config of the device in Homebridge?

Thanks
Thomas

**Comment by merdok** [comment]
@t0mmey the model which you specified is incorrect hence the plugin cannot fetched the correct spec. The model is xiaomi.vacuum.c102gl and not X20+

**Comment by t0mmey** [comment]
Thanks a Lot @merdok ! Fixes. Thanks for all your efforts!

**Comment by jvacek** [comment]
@satrik Heya, did you by any chance ever figure out how to map the rooms? Any suggestions on how to intercept the requests sent from the apps? I found the spec metadata here, but wouldn't know how to format the params to conform to it.

I do indeed get something `X10+`-like from `miot send <IP> -t <TOKEN> get_properties '[{"siid":8,"piid":2}]'` like the docs say, but the 6.2 nor 4.1 seem to want to work with me.

**Comment by satrik** [comment]
hey @jvacek, no I did not invest more time in this because I switched to HomeAssistant and there it just works.
I wrote the mentioned docs for the X10+. [here](https://github.com/merdok/homebridge-miot/issues/364) you can find the things I tried back then to get all the needed data. with the modified mi home app you can easily get all sent requests to reverse debug the correct commands.
