### ISSUE TITLE
Problem with chuangmi.plug.212a01 (Mi Smart Power Plug 2)

### ISSUE THREAD

**Issue by santiagolorenzo-uy** [merdok/homebridge-miot#595]
**Describe the bug**
Homebridge detect the plug and install it but puts two devices  in the accesory list(xiaomi smart plug 2 and a "LED"). 
It doesn't work at all when I try to turn on the device.

**Expected behavior**
when I make click on the device in home bridge (or even in the HomeKit app) the plug  doesn't turn on or off.

**Your config.json**
this?

 {
            "name": "Xiaomi Smart Plug 2 (Wi-Fi)",
            "ip": "XXX.XXX.XXX.XXX",
            "token": "this is private?",
            "deviceId": "this is private?",
            "model": "cuco.plug.v2eur",
            "pollingInterval": 10,
            "deepDebugLog": false,
            "silentLog": false,
            "deviceEnabled": true,
            "buzzerControl": true,
            "ledControl": true,
            "childLockControl": true,
            "modeControl": true
        }

**Debug log**
NOTHING HAPPENED, NO ERRORS OCCURED, but this is what I got:

[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Using module class for device type Outlet, indentified by miot spec! Not all features might work!
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Initializing device services
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Device services: [
  "switch",
  "physical-controls-locked",
  "power-consumption",
  "indicator-light",
  "delay",
  "charging-protection",
  "cycle",
  "max-power-limit"
]
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Initializing device properties
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Device properties: [
  "switch:on",
  "switch:default-power-on-state",
  "switch:fault",
  "physical-controls-locked:physical-controls-locked",
  "power-consumption:power-consumption",
  "power-consumption:electric-power",
  "indicator-light:on",
  "delay:delay",
  "delay:delay-time",
  "delay:delay-remain-time",
  "charging-protection:on",
  "charging-protection:power",
  "charging-protection:protect-time",
  "cycle:status",
  "cycle:data-value",
  "max-power-limit:on",
  "max-power-limit:power"
]
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Initializing device actions
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Device actions: [
  "switch:toggle"
]
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Successfully created a Outlet device! It is a Unknown outlet device.
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Initializing accessory!
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Accessory successfully initialized!
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Registering 1 accessories!
[5/27/2024, 9:09:14 PM] [miot] [Xiaomi Smart Plug 2 (Wi-Fi)] Everything looks good! Initiating property polling!
**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
<img width="425" alt="Captura de pantalla 2024-05-28 a la(s) 10 02 55 p  m" src="https://github.com/merdok/homebridge-miot/assets/64233421/00fe0922-7220-4b4e-bd9b-8f16158a32d7">

_Add any other context about the problem here._

**Comment by merdok** [comment]
Might be that this is a micloud only device. Did you try to specify your micloud credentials in the config and set the forceMiCloud property to true?

**Comment by santiagolorenzo-uy** [comment]
> Might be that this is a micloud only device. Did you try to specify your micloud credentials in the config and set the forceMiCloud property to true?

Hello, thanks to take the time to respond.
Yes I put mycloud account, this is mandatory as I know.
And yes I turn on "force mycloud", it start to gave me errors everywhere in the log

**Comment by santiagolorenzo-uy** [comment]
This is the error that gave me when I put de MiCloud info, is strange because it takes all the info automatically from the account.

<img width="833" alt="Captura de pantalla 2024-06-23 a la(s) 12 01 14 a  m" src="https://github.com/merdok/homebridge-miot/assets/64233421/418457ca-0151-4de5-bcae-cf595888255f">

**Comment by merdok** [comment]
If your device is on the Singapure server then you need to specify that in your MiCloud connection settings. The error simply states that the specified device cannot be found on the china server.

**Comment by santiagolorenzo-uy** [comment]
But I did that and doesn’t work.
But I solved, I start try another countries till one work (tw) thanks for everyone time. 
I am a little stupid at this things

**Comment by merdok** [comment]
glad that it works now! thanks for the info
