### ISSUE TITLE
Support for newly released 米家直流变频落地扇 Pro

### ISSUE THREAD

**Issue by steven414** [merdok/homebridge-miot#596]
**Device model**

**米家直流变频落地扇 Pro**

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
https://www.mi.com/shop/buy/detail?product_id=1230802062&cfrom=search

**Comment by merdok** [comment]
Did you already add the device to the plugin? What was the result?

**Comment by steven414** [comment]
> Did you already add the device to the plugin? What was the result?

Jus want to check whether it is supported, since I didn't see the name is listed in the supported device.

**Comment by merdok** [comment]
The list is only for devices which have a dedicated module and were tested, in most cases other devices will also work, hence you should simply try to add it to the plugin and see if it works.
