### ISSUE TITLE
Yeelight Wireless S1 BLE button 

### ISSUE THREAD

**Issue by DemoreN** [merdok/homebridge-miot#597]
**Device model**
yeelink.remote.remote  (YLAI003)

**Device name**
Yeelight Mesh Remote Control / Wireless Switch S1

**Does the device require a MiCloud connection?**
Do not know_

**Anything special about the device?**
HomeKit doesn't recognize as a button

**Comment by merdok** [comment]
Hi, unfortunately that device will currently not be able to work due to the fact that it operates with events which are currently not working... 
https://www.merdok.org/miotspec/?model=yeelink.remote.remote
