### ISSUE TITLE
Rodimi Eva support

### ISSUE THREAD

**Issue by Lis198407** [merdok/homebridge-miot#598]
Hello! is it possible to add Roidmi EVA support, or maybe it need some changes. 
it's in a support list, and it's adding as a device. but it's always off-line

device: roidmi.vacuum.v66
Device name: [ROIDMI EVA](https://home.mi.com/views/deviceReset.html?locale=en&model=roidmi.vacuum.v66)
Does the device require a MiCloud connection? - Do not know
[link to specification](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:roidmi-v66:1)

**Comment by merdok** [comment]
If it is in the supported device list and it does not work for you, then you need to verify that your token an ip address are correct.

**Comment by Lis198407** [comment]
Can you help to understand how to convert this https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:roidmi-v66:4

to action buttons, for example? it's looks like different JSON params. for example actions - it's something like buttons, but with different params

**Comment by merdok** [comment]
The action params piid correspond to properties which are on the same service with the specified id. So you have to check on the properties to see what kind of params an action supports.

**Comment by Lis198407** [comment]
Can you help on this example? I've made 1 action button for test.

in action name i've put an description of value
into the params i should use 0,1,2?

-- all json params for device--
"actionButtons": [
                {
                    "action": "Sweep Type",
                    "name": "Sweep",
                    "params": [
                        0
                    ],
                    "action": "Sweep Type",
                    "name": "Mop",
                    "params": [
                        1
                    ],
                    "action": "Sweep Type",
                    "name": "Mop And Sweep",
                    "params": [
                        2
                    ],
                }

example of JSON from homebridge-miot:

        {
            "name": "ROIDMI EVA",
            "ip": "IP",
            "token": "token",
            "deviceId": "deviceId",
            "model": "roidmi.vacuum.v66",
            "pollingInterval": 10,
            "deepDebugLog": false,
            "silentLog": false,
            "deviceEnabled": true,
            "micloud": {
                "username": "username",
                "password": "password",
                "country": "de",
                "forceMiCloud": true
            },
            "onlyMainService": false,
            "buzzerControl": false,
            "ledControl": false,
            "childLockControl": false,
            "modeControl": true,
            "actionButtons": [
                {
                    "action": "action1",
                    "name": "actionname1",
                    "params": [
                        "actionparam1"
                    ]
                }
            ]
        },

information from miot-spec:
        {
          "iid": 8,
          "type": "urn:miot-spec-v2:property:sweep-type:000000D3:roidmi-v66:1",
          "description": "Sweep Type",
          "format": "uint8",
          "access": [
            "read",
            "write",
            "notify"
          ],
          "value-list": [
            {
              "value": 0,
              "description": "Sweep"
            },
            {
              "value": 1,
              "description": "Mop"
            },
            {
              "value": 2,
              "description": "Mop And Sweep"
            }
          ],
          "gatt-access": []
        },

**Comment by merdok** [comment]
Your json is incorrect, the action property is wrong, please have a look at the example configuration here [icue link vrm](https://github.com/merdok/homebridge-miot?tab=readme-ov-file#configuration)
