### ISSUE TITLE
Support for Linptech Human Presence sensor

### ISSUE THREAD

**Issue by chrhee21** [merdok/homebridge-miot#599]
**Device model**
linp.sensor_occupy.hb01

**Device name**
Linptech human presence sensor 

**Does the device require a MiCloud connection?**
It seems that. Without Mi cloud, device was not recognized by Homebridge. 

**Anything special about the device?**
By using MiCloud connection, sensor was added. 
But, presence property was not shown properly.

**Comment by merdok** [comment]
Thanks, for the request! Will check it out!

**Comment by chrhee21** [comment]
I configured property monitor like below.
By doing this, occupancy-sensor:occupancy-status can be seen as presence in Homekit.
But, state is not correct. All the time absence.
<img width="690" alt="Presence sensor" src="https://github.com/merdok/homebridge-miot/assets/85432771/5eb8fb80-b19e-4573-9592-ccedd4265ddb">

**Comment by merdok** [comment]
This is the same issue as in your other device. Need to modify config.json manually.

**Comment by chrhee21** [comment]
Thanks a lot.  It works perfectly.

**Comment by fbi007130** [comment]
"propertyMonitor": [
                {
                    "property": "occupancy-sensor:occupancy-status",
                    "value": "1",
                    "valueOperator": "equal"
                }
            ]

**Comment by merdok** [comment]
@fbi007130 `value` should be 1 as number, so it would look like this:
`"value": 1,`
unfortunately you have to be careful about the values types...
using the ui, it will always put it is a a string, so you have to do that entries manually in the config.json
