### ISSUE TITLE
Linptech Pressure sensor

### ISSUE THREAD

**Issue by chrhee21** [merdok/homebridge-miot#600]
**Device model**
linp.senpres.ps1bb

**Device name**
Linptech pressure sensor

**Does the device require a MiCloud connection?**
It seems that. 
After using Mi Cloud connection, device could be seen in Home Kit. 

**Anything special about the device?**
Device can be seen in Home Kit. But its property is not shown in HomeKit properly.

**Comment by merdok** [comment]
Thanks, for the request! Will check it out!

**Comment by chrhee21** [comment]
I configured property monitor like below.
By doing this, pressure-presence-state can be seen as presence in Homekit. 
But, state is not correct. All the time absence. 
<img width="692" alt="Pressure sensor" src="https://github.com/merdok/homebridge-miot/assets/85432771/4be20e34-a80b-4c23-b4ae-9aee74eb55e0">

**Comment by merdok** [comment]
You need to modify the config.json manually. The value type is boolean but when you use the ui it will always use a string. You need to remove quotas around "true" in the config.json manually then it should work.

**Comment by chrhee21** [comment]
Thanks a lot.  It works perfectly.
