### ISSUE TITLE
Add support for Lomediqi Fresh air system

### ISSUE THREAD

**Issue by DaddyTommy69** [merdok/homebridge-miot#601]
**Device model**
bjdm.airfresh.test01 

**Device name**
Lomediqi Intelligent Fresh air purifier

**Does the device require a MiCloud connection?**
Do not know (released in 2019 I think according to this page https://home.miot-spec.com/s/bjdm.airfresh.test01)

**Anything special about the device?**
- Please support adjusting fresh air level (ranges from 0-20%-40%-60%-80%-100%) and C02 sensor in addition to the standard air purifier controls
- There are 2 versions of the device (one with ioniser and one without). I believe both goes by the model of bjdm.airfresh.test01

**Comment by merdok** [comment]
Hi, what is not working with the device currently? Did you already try to add it to the plugin?

**Comment by DaddyTommy69** [comment]
My apologies I recently press discover devices in the plugin and it's been found and working in homekit. However I do wish for a fresh air level option alongside the fan speed option, as the device has 2 fans that operate independently (the top one is for room air intake and bottom one for fresh air intake). I will post the pic of the Xiaomi Home controls below

**Comment by DaddyTommy69** [comment]
![Screenshot_20240610_140706_Mi Home](https://github.com/merdok/homebridge-miot/assets/165805615/67b4e3c7-0375-4d77-9b65-222da0994c35)
![Screenshot_20240610_140700_Mi Home](https://github.com/merdok/homebridge-miot/assets/165805615/7bbb8022-d1d5-44a4-9ad8-fe9e3fae89e1)

**Comment by merdok** [comment]
Hi, you would need to use propertyControl to expose the missing functionality.

**Comment by DaddyTommy69** [comment]
I managed to find what I want to control but not sure how to input them. Please point me in the right direction
![Untitled](https://github.com/merdok/homebridge-miot/assets/165805615/6cc032f9-94be-4605-a2a3-c06a552f3f4d)

**Comment by DaddyTommy69** [comment]
It is showing up as individual switches for 0-1-2-3-4-5 level. Is it possible to turn it into the blue slider for fans

![20240610_154448](https://github.com/merdok/homebridge-miot/assets/165805615/71983856-119d-4d8f-a6ac-ee491a2097fb)

**Comment by merdok** [comment]
Not in a generic way because the property is marked as a value list with a couple possible values, currently you can only show things like this with multiple switches.

**Comment by DaddyTommy69** [comment]
It would be greatly appreciated if you could find the time to implement such function. It is one of the main selling point of the unit as opposed to much pricier alternatives. Thank you

**Comment by merdok** [comment]
It requires a special property handling currently for this particular device which would require some work. Maybe it could be emulated using a fan or lightbulb but that would still require some code adjustments. The main problem here is that HomeKit does not support such ui control which allows to select between multiply options hence we need to do some tricks in order to make it work...

**Comment by merdok** [comment]
You can also limit the values only to those switches which you use the most, so if you just use two values then you can create two propertyControl for the same property and you can specify the value it should set, that way only two switches will appear.
