### ISSUE TITLE
Add support for New Widetech Dehumidifier 60L

### ISSUE THREAD

**Issue by DaddyTommy69** [merdok/homebridge-miot#602]
**Device model**
nwt.derh.60l

**Device name**
NWT Internet Dehumidifier 60L

**Does the device require a MiCloud connection?**
Probably ? (released in 2023 according to this page https://home.miot-spec.com/s/nwt.derh.60l)

**Anything special about the device?**
- Has clothes drying function (max speed and fan when chosen)
- Has water full features (notify when the drain bucket is full and stop the device)
- Has defrosting feature (stop operation when the coil is frozen)

**Comment by merdok** [comment]
Hi, what is not working with the device currently? Did you already try to add it to the plugin?

**Comment by DaddyTommy69** [comment]
My apologies I recently press discover devices in the plugin and it's been found and working in homekit. However I do wish for a targetted humidity level option and clothes drying function. I will post the pic of the Xiaomi Home controls below

**Comment by DaddyTommy69** [comment]
![Screenshot_20240610_140732_Mi Home](https://github.com/merdok/homebridge-miot/assets/165805615/7fecf109-8ba5-4f6d-9717-3eb464f71487)

**Comment by DaddyTommy69** [comment]
Nevermind. Found what I needed in the plugin config for the device. Thank you for your work, I'm closing the issue now. Please help me with issue #601
