### ISSUE TITLE
Local connection to lights not working

### ISSUE THREAD

**Issue by mishablokhin** [merdok/homebridge-miot#605]
Hello!
I have some problems with miot configured to use local connection with light devices. 
Some devices, such as Yeelight Light Strip, Yeelight Light Strip Pro and Yeelight Bedside Lamp D2 works only with MiCloud Connection setting is on. Other devices using local connection without any issues. 
For now i'm using this lamps with MiCloud connection as workaround.
Could you help me with fixing this issue? 
Here is log file with deep logging. Maybe it would be helpful to investigate problem.
Thank you!
[sanitized_homebridge_miot_logs.log](https://github.com/user-attachments/files/15889243/sanitized_homebridge_miot_logs.log)

**Comment by merdok** [comment]
I do not quite understand what is your issue, could you explain more? Some lamps require a MiCloud connection and there is nothing that can be changed about that. You can specify the global MiCloud account settings and then you can use the `forceMiCloud` on the devices which should use the cloud.

**Comment by mishablokhin** [comment]
Sure, I would like to provide more details about my problem. Some of my lights won’t work with a local connection. I have noticed this issue with the following models: yeelink.light.strip8, yeelink.light.bslamp3, and yeelink.light.strip2.

I have disabled the global option “Force MiCloud Connection”. However, some devices, if they require MiCloud to function, use a cloud connection instead of a local one (for example, the zhimi.airpurifier.v7 exhibits this behavior).

These three lights simply don’t work at all if I don't set true in "Force MiCloud Connection" globally or as option for specific device. Is there something wrong with my miot configuration, or do these lights only support MiCloud connection?

**Comment by mishablokhin** [comment]
Maybe i should try enable "LAN Control" for these lights in Yeelight App. Would see if this changes something.

**Comment by mishablokhin** [comment]
So, i have done my investigation :)
If "LAN Control" enabled in Yeelight App HomeAssistant could detect lightstrip locally, connect and control device. If "LAN Control" disabled device could be managed only using MiCloud, HomeAssistant won't discover any lights. 
All tests were made with yeelink.light.strip2. 
I think something wrong with miot, because while "LAN Control" is on, miot can't control lightstrip. Getting same connection and property fetch errors.

**Comment by merdok** [comment]
The Yeelight which you specified does not support a local miot connection. "LAN Control" is something different and it does not use the miot protocol.
