### ISSUE TITLE
support for mi robot cleaner/vaccum G1

### ISSUE THREAD

**Issue by henkyfoo** [merdok/homebridge-miot#61]
i know this is off topic
but i have 2 type of robot in home, one is 1C and another one is G1

i have successfully config both of them and be displayed in homekit tile
but only 1C is function, as for the G1 is not responding

and another one is, can we have the option to show the devices as switch rather than fan?

**Comment by merdok** [comment]
I can add support for the G1 but you would need to give me the exact model of that device so that i know with what i am dealing.

Right now the vacuums are displayed as fans since i want to take use of the additional functionality which that enables. If i change it to a switch then some functionality will get lost...

**Comment by henkyfoo** [comment]
Okay, what kind of information may be needed?

i am sorry but i’m kinda new to this
I’ll try to help as much as i could

**Comment by merdok** [comment]
I need the exact model of the device. When you check the supported devices list then you will see that each device can be identified with a model and i need to know that exact model of the G1 vacuum.

**Comment by henkyfoo** [comment]
Okay but where to find that?

**Comment by merdok** [comment]
If you already added the device to my plugin then just start homebridge in debug mode and it should print you somewhere in the console the device model, besides that you have to maybe check the mi home app if you can find it there.

**Comment by henkyfoo** [comment]
I think is this mijia.vacuum.v2

![58E64143-3B5C-48EC-B438-D86E62578F58](https://user-images.githubusercontent.com/87588344/126060875-39a3d928-1c40-4404-a0ee-da289e212691.jpeg)

**Comment by merdok** [comment]
Does it say device unsupported in the log also after that?

**Comment by henkyfoo** [comment]
Yes the log show device not supported

here is the full log when i restart the bridge

![6F2CDF13-763F-4390-9CB7-182252077ADF](https://user-images.githubusercontent.com/87588344/126063566-d487fb64-d6c7-4cc3-be87-e88f40524709.png)
![343A6A0C-C969-4BA9-AC31-AE4E4CC6544E](https://user-images.githubusercontent.com/87588344/126063569-dd04938d-5232-4257-a192-b17d3a1df6d4.png)

**Comment by merdok** [comment]
Ok, thanks for the info. Will try to add support for that device in the update!

**Comment by henkyfoo** [comment]
Thanks a lot

**Comment by henkyfoo** [comment]
Hey buddy, may i know when is the next update will be available??

**Comment by merdok** [comment]
That i cannot tell, hopefully soon...

**Comment by merdok** [comment]
Version 0.9.8 should now support your device!

**Comment by henkyfoo** [comment]
I am still getting not supported log
Am i doing it wrong?
![image](https://user-images.githubusercontent.com/87588344/126915898-ac6ddfa1-d194-4076-9279-6b6fa871bf83.png)

**Comment by henkyfoo** [comment]
I updated to 0.98, now it recognize but the device doesnt response in the home app

I'll try again tonight and update u

**Comment by henkyfoo** [comment]
Hi, the device was added fine and the log show no error
But everytime i try to turn on the vaccum, it will turning off itself

Idk where is the problem because the setting is the same with the 1C
And the 1C is working fine 

![image](https://user-images.githubusercontent.com/87588344/126934740-e6dc6e70-9b36-455f-91c2-0dac9f96f569.png)

![image](https://user-images.githubusercontent.com/87588344/126934750-c83f426f-9f92-48ef-9fa2-e9fc2eba24e4.png)

**Comment by henkyfoo** [comment]
Hey it worked now. Thanks a lot buddy
