### ISSUE TITLE
Xiaomi Smart IH Rice Cooker 3L ?

### ISSUE THREAD

**Issue by thanhbigface** [merdok/homebridge-miot#612]
**Device model**
chunmi.cooker.cmwy3

**Device name**
Xiaomi Smart IH Rice Cooker 3L 

**Does the device require a MiCloud connection?**
I don't know

**Anything special about the device?**
I found it doesn't work even though there is a button in homekit

**Comment by merdok** [comment]
Could it be that the Devise requires a micloud connection? Did you try to specify your micloud credentials and set the device to forceMiCloud?
