### ISSUE TITLE
Fan control not appear for Smart Air Purifier 4 Compact

### ISSUE THREAD

**Issue by lirik44** [merdok/homebridge-miot#615]
Tile work's only like a switch for Smart Air Purifier 4 Compact (xiaomi.airp.cpa4)
![IMG_7022](https://github.com/user-attachments/assets/663c1f32-b968-4805-be10-aa5e2e72fd54)

All settings correct, my config for this device:
 
```
{
            "name": "Air Purifier Mini",
            "ip": "192.168.1.132",
            "token": "XXXXXXXXXXXXXX", 
            "deviceId": "xiaomi.airp.cpa4",
            "pollingInterval": 10,
            "deepDebugLog": false,
            "silentLog": false,
            "deviceEnabled": true,
            "buzzerControl": false,
            "childLockControl": false,
            "modeControl": true,
            "fanLevelControl": true,
            "screenControl": false
        }
```
 Trying to force micloud connection, and there is no result.

Want this look like my another Smart Air Purifier 4 Pro (zhimi.airp.vb4)
![IMG_7024](https://github.com/user-attachments/assets/32740c26-e7dd-4c69-b272-066b21113434)

**Comment by merdok** [comment]
The provided device model is incorrect. The correct one is zhimi.airp.cpa4

**Comment by lirik44** [comment]
> The provided device model is incorrect. The correct one is zhimi.airp.cpa4

Already try this, same result, only switcher, no fan control

**Comment by merdok** [comment]
You put the model info in the deviceid field! If you are unsure where to put the values then just leave them away and plugin will retrieve those automatically!
