### ISSUE TITLE
2FA Required, Click Here, Wait a Few Seconds And Try Again

### ISSUE THREAD

**Issue by Jonan1252** [merdok/homebridge-miot#618]
Unable to login to MiCloud to discover new devices, existing BLE devices that require forced micloud connection has also broken. 
After clicking and logging in to micloud account authentication, the webpage just displays ok in text. nothing else happens

**Comment by merdok** [comment]
I think you have to disable 2FA for your account.

**Comment by Jonan1252** [comment]
> I think you have to disable 2FA for your account.

Theres no option to disable of mi account.

**Comment by merdok** [comment]
You could also try to authenticate in a different browser window

**Comment by Danivilanova** [comment]
I'm having the same problem, have you found out how to solve it?

**Comment by merdok** [comment]
I would need to try create an account with 2FA enabled as my primary account does not have it. Could tell where did you create the account and how you enabled 2FA?

**Comment by Jonan1252** [comment]
2FA was enabled by default. My workaround was to log into my mi account via https://account.xiaomi.com/fe/service/login/phone?_locale=en on another tab while homebridge tries to authenticate at the same time on another browser tab.

On 14 Aug 2024, at 1:59 PM, Marcin ***@***.***> wrote:

﻿

I would need to try create an account with 2FA enabled as my primary account does not have it. Could tell where did you create the account and how you enabled 2FA?

**Comment by Zedasix** [comment]
Same problem
