### ISSUE TITLE
Unable to control Mi Air Purifier Pro V7

### ISSUE THREAD

**Issue by Orcky723** [merdok/homebridge-miot#619]
**Describe the bug**
I am unable to control any settings for zhimi.airpurifier.v7. The plugin works as expected for my other purifier: zhimi.airpurifier.mb3. 

I added both devices using "Discover all devices via MiClud". Both devices can be controlled using the MiCloud app.

I attached a screenshot of Homebridge with the two devices. Both are currently on, but the v7 is appearing off. 

Deep debug attached, and JSON below.

**Your config.json**
{
            "devices": [
                {
                    "name": "Air purifier (large)",
                    "ip": "",
                    "token": "",
                    "deviceId": "133486901",
                    "model": "zhimi.airpurifier.v7",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "silentLog": false,
                    "deviceEnabled": true,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "fanLevelControl": false,
                    "ioniserControl": false,
                    "screenControl": false
                },
                {
                    "name": "Air purifier (small)",
                    "ip": "",
                    "token": "",
                    "deviceId": "282500494",
                    "model": "zhimi.airpurifier.mb3",
                    "pollingInterval": 10,
                    "deepDebugLog": true,
                    "silentLog": false,
                    "deviceEnabled": true,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "fanLevelControl": false,
                    "ioniserControl": false,
                    "screenControl": false
                }
            ],
            "platform": "miot"
        }
    ]
}

![Screenshot 2024-08-04 at 4 36 54 PM](https://github.com/user-attachments/assets/85037c98-6160-402f-9639-0a35172e8f9f)

[debug log.txt](https://github.com/user-attachments/files/16486540/debug.log.txt)

**Comment by merdok** [comment]
The zhimi.airpurifier.v7 is a micloud only device, meaning you have to specify your micloud credentials in the config so that the plugin can connect to the cloud and control your device.

**Comment by Orcky723** [comment]
Legend, that worked, thanks mate. This is a great little plugin, and thanks for the quick reply.
