### ISSUE TITLE
Xiaomi doorbell 3 Camera

### ISSUE THREAD

**Issue by maverickrezo** [merdok/homebridge-miot#620]
**Describe the idea or improvement**
I have added xiaomi doorbell 3 camera but it only shows motion sensor and also i couldn't find any documentation for this device

**Describe the solution you'd like**
i want to have camera notifications and possibility to use homepod as chime

**Comment by merdok** [comment]
Sorry, the camera feed currently does not work as it requires some extensive work. Maybe in the future thou...

**Comment by Semir333** [comment]
@merdok 
Maybe this could be help. (I could help beta test with 3 type of cams) In HA all of the Xiaomi cameras work with this plugin with auto config, also login and tokens. I think if fully works on HA, it's need to be work same as HB.
Google stream codes is also avalivable from Xiaomi's datasheet site.

https://github.com/al-one/hass-xiaomi-miot

**Comment by merdok** [comment]
The difference is python vs JavaScript, so it would need to be checked if there are the same or at least similar libraries which can be re-used...
