### ISSUE TITLE
Homekit to turn on and off Mi TV

### ISSUE THREAD

**Issue by tath105** [merdok/homebridge-miot#623]
**Device model**
xiaomi.tv.mitv5h1

**Device name**
xiaomiTV 55inch

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
I can already see the device in HomeKit as "not supported"; but i noticed that I can control my sony TV in Homekit.
I'm grateful if I can turn this on / off already. Of course, full control will be great...

**Comment by merdok** [comment]
You could enter the device model here https://www.merdok.org/miotspec/
Check the supported properties and create properyControl for everything that you need.
