### ISSUE TITLE
Roidmi eve cc 

### ISSUE THREAD

**Issue by Michkal1991** [merdok/homebridge-miot#629]
**Device model**
_The unique model of your device, e.g zhimi.fan.za5._
Roidmi eve cc

**Device name**
_The friendly name of the device used by the manufacturer, e.g. Smartmi Standing Fan 3._
Roidmi eve cc

**Does the device require a MiCloud connection?**
_Yes/No/Do not know_
Do not know 
_Most devices which were introduced to the market in 2020 and later does not require MiCloud._

**Anything special about the device?**
_Does it already work with the plugin with a limited scope (can be controlled using the auto created switch)?_
Nothing exposed

**Comment by merdok** [comment]
What is the issue with the device? Did you already try to add it to the plugin?
BTW, `Roidmi eve cc` is not the device model.

**Comment by Michkal1991** [comment]
I tried to add it (I also tried it with mi account), however no success.
What do you mean this is not the device model?
How can I identify the correct model?

**Comment by Michkal1991** [comment]
I changed the name. I found it through mihome devices token app. Please find below my config.

name": "roidmi.vacuum.v62",
                    "ip": "10.238.1.169",
                    "token": "---",
                    "deviceId": "roidmi.vacuum.v62",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "silentLog": false,
                    "deviceEnabled": true,
                    "micloud": {
                        "username": "-----@gmail.com",
                        "password": "M------8!",
                        "forceMiCloud": false
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                }

**Comment by merdok** [comment]
The deviceid is incorrect in your config! If you are not sure what to enter then you should leave the not required properties empty and the plugin will automatically retrieve those values.

**Comment by Michkal1991** [comment]
My mistake. Finally I was able to add it by connecting to mihome and getting the device id.

**Comment by merdok** [comment]
Fantastic! Glad that it works now🙂
