### ISSUE TITLE
 Device not supported!

### ISSUE THREAD

**Issue by League2EB** [merdok/homebridge-miot#63]
can you add this model to support list ? @merdok 

thx all ! 

 **Model: yeelink.light.color3**

## Error Messenger
![image.png](https://i.loli.net/2021/07/25/3ixgTon8LlzRVEI.png)

## config
![Untitled_Clipping_072521_020905_AM.jpg](https://i.loli.net/2021/07/25/rBNZGVQhtX9oavm.jpg)

**Comment by merdok** [comment]
Sure, i will add support for that device in the next update

**Comment by League2EB** [comment]
> Sure, i will add support for that device in the next update

thx all !

**Comment by merdok** [comment]
Version 0.9.8 should now support your device!

**Comment by League2EB** [comment]
@merdok can you support model of **isa.camera.hlc7** ?
i can donate you !

**Comment by merdok** [comment]
I can try to implement that camera, basic controls of the camera should definitely be possible. But i am not sure about the video feed in homekit since i never had any experience with that and also without having the actual device it can be tricky... Would you also expect to have the video feed or is it only control for the camera`?

**Comment by League2EB** [comment]
I tried using HA to concatenate the camera
And the use of
[hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot)

But the author told me there was no support
I can use HA to control the camera switch but I can't see anything
I just need to see the camera in Homekit and turn the camera off and on

**Comment by merdok** [comment]
On/Off should be already possible now. Did you try it?

**Comment by League2EB** [comment]
> On/Off should be already possible now. Did you try it?

not yet with your plugin  

i am try it now !

**Comment by merdok** [comment]
Please try it and let me know, that would give me clarity if at least the base works.

**Comment by League2EB** [comment]
@merdok 

it's work for on/off

https://imgur.com/Evcn1ww

**Comment by merdok** [comment]
Yes, that is already good info :) That confirm that it is indeed a miot device. I cannot promise anything at this point but i will try to implement support for that camera, although it might be not easy without actually having that camera... Could you please open a new issue where you request support for that camera?

**Comment by League2EB** [comment]
> Yes, that is already good info :) That confirm that it is indeed a miot device. I cannot promise anything at this point but i will try to implement support for that camera, although it might be not easy without actually having that camera... Could you please open a new issue where you request support for that camera?

need support Camera Info 

Name：XIAOMI MI Smart CCTV Camera 2K Standard Edition - MJSXJ03HL
Model Numbe: MJSXJ03HL
Model Name: isa.camera.hlc7

**Comment by merdok** [comment]
Please open a new issue requesting support for that camera and add that info there!
