### ISSUE TITLE
Support for Smart Air Purifier 4 no longer works

### ISSUE THREAD

**Issue by sasojadrovski** [merdok/homebridge-miot#630]
**Describe the bug**
Since a few days ago, Homebridge continuously reports issues with the Smart Air Purifier 4. It looks like Homebridge cannot connect to the device. I did try with forcing Mi Cloud, but the issue persists.

**Expected behavior**
Smart Air Purifier 4 should work as expected.

**Your config.json**
```json
{
    "name": "Air Purifier",
    "ip": "192.168.2.44",
    "token": "XXX", // redacted for security reasons
    "deviceId": "YYY", // redacted for security reasons
    "model": "zhimi.airp.mb5a",
    "pollingInterval": 10,
    "deepDebugLog": false,
    "silentLog": false,
    "deviceEnabled": true,
    "micloud": {
        "country": "de",
        "forceMiCloud": false
    },
    "onlyMainService": false,
    "buzzerControl": false,
    "ledControl": false,
    "childLockControl": false,
    "modeControl": false,
    "suppressAutoServiceCreation": [
        "illumination"
    ],
    "fanLevelControl": false,
    "screenControl": false
}
```

**Debug log**
```
[9/13/2024, 3:46:00 PM] [homebridge-miot] [Air Purifier] Device found! Setting up miot device from local connection!
[9/13/2024, 3:46:00 PM] [homebridge-miot] [Air Purifier] Connected to device: zhimi.airp.mb5a
[9/13/2024, 3:46:00 PM] [homebridge-miot] [Air Purifier] Doing initial property fetch.
[9/13/2024, 3:46:12 PM] [homebridge-miot] [Air Purifier] Starting property polling.
[9/13/2024, 3:46:54 PM] [homebridge-miot] [Air Purifier] Poll failed 4 times in a row! Stopping polling and trying to reconnect! Reason: Error: Call to device timed out
```

Will enable deep debug logs if needed. Above is an output without.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by merdok** [comment]
That might be a strong indicator that the token changed. You would need to re-fetch the token.
Also if you specify `forceMiCloud` then you also have to specify the account credentials for login.

**Comment by sasojadrovski** [comment]
Thanks @merdok,

How do I re-fetch the token?

I know I have to add my credentials if I force using Mi Cloud.

**Comment by merdok** [comment]
Please check the README for the credentials!

The token you can retrieve as usual

**Comment by gnz-ori** [comment]
Been having issues with the Xiaomi Air Purifier 4 Pro. Deleted and re-added and saw these lines.

![Screenshot 2024-10-09 at 11 47 00](https://github.com/user-attachments/assets/45e25327-ed86-47ab-aefc-238c6b8e7f6a)

**Comment by gnz-ori** [comment]
So after a few tries I got it back. But there seems to be a bug with the "general device settings" where even when the controls are not selected, they still appear as part of the created device.

Please refer to the screenshots:

![Screenshot 2024-10-09 at 11 58 56](https://github.com/user-attachments/assets/f6e0ee96-a29e-4151-9304-8c7a8b8503e4)
![Screenshot 2024-10-09 at 11 58 06](https://github.com/user-attachments/assets/5a114a60-f8cd-4365-ab3b-2f7b3e849b93)

**Comment by merdok** [comment]
What would you expect to disappear? From your screenshot it looks as it supposed to...

**Comment by merdok** [comment]
Screen is a device specific setting so you will not find it under the generic section, but I guess under the air purifier section.

**Comment by arktiknova** [comment]
Oh yeah you are right. Just checked btw after you pointed it out but I don't have them ticked too. Basically everything automatically appeared even when they are not ticked (selected). Are those supports to appear despite not being selected?

![Screenshot 2024-10-09 at 21 47 34](https://github.com/user-attachments/assets/766e863c-706e-4550-965c-d558e9dc3adc)

**Comment by merdok** [comment]
You should try to tick it and save, and afterwards untick it, save again and re-try.

**Comment by arktiknova** [comment]
Finally got the time to give it a try. I did as suggested and it finally worked after two reboots. Thank you!

**Comment by merdok** [comment]
Good to hear. About your other device you have to check what the log says, possibility it cannot connect to the device.
