### ISSUE TITLE
isa.camera.hlc7

### ISSUE THREAD

**Issue by Pejpr** [merdok/homebridge-miot#631]
Hi,
I have isa.camera.hlc7 Camera and in HomeKit I can see just ON/OFF button and no live stream video - it is OK or I am missing something else?
Thx for lead the right direction.

Here is my config:
{
    "devices": [
        {
            "name": "Mímo",
            "ip": "10.0.0.2",
            "token": "<geted token>",
            "deviceId": "1104686365",
            "model": "isa.camera.hlc7",
            "pollingInterval": 10,
            "propertyChunkSize": 5,
            "deepDebugLog": false,
            "silentLog": false,
            "deviceEnabled": true,
            "micloud": {
                "username": "<e-mail account>",
                "password": "<my password>",
                "country": "de",
                "forceMiCloud": true,
                "timeout": 100
            },
            "buzzerControl": true,
            "ledControl": true,
            "childLockControl": true,
            "modeControl": true
        }
    ],
    "platform": "miot"
}

**Comment by merdok** [comment]
There is currently no live stream support for cameras... That would need to be first implemented by someone who has knowledge of that.
