### ISSUE TITLE
Pet Feeder

### ISSUE THREAD

**Issue by violason** [merdok/homebridge-miot#632]
Hello There is Pet Feeder among the supported device types. but it is not in the list of Supported devices. When I add the plugin to my home, it finds the pet feeder, but the buttons are non-functional (not activated or deactivated) is there something about it that I missed and can't do? I use one of xiaomi's pet feeder devices.

**Comment by merdok** [comment]
That all depends on what pet feeder you have. Some will require that you use a micloud connection. For that you need to set the `forceMiCloud` property to true and enter your credentials.
