### ISSUE TITLE
Please add support for `philips.light.strip3`

### ISSUE THREAD

**Issue by realJustinLee** [merdok/homebridge-miot#633]
**Device model**
philips.light.strip3

**Device name**
Xiaomi Smart Light Strip  Pro

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
Nope

**Comment by merdok** [comment]
Hi, what is the issue with the device? Did you already try to add it to the plugin?

**Comment by realJustinLee** [comment]
Hi, @merdok , I’ve tried to add it to HomeKit, and the controls seem to be a little laggy and is quite difficult to turn the light strip off after turning it on.

**Comment by merdok** [comment]
This is not a problem with the plugin but the connection. I assume that you are using the micloud which more or less behaves like that in certain regions.

**Comment by realJustinLee** [comment]
Hmmm, maybe, but I haven’t turned on mi cloud for this gadget.

**Comment by merdok** [comment]
Then the slow response is due to your network. You can also try to reset the device, sometimes that helps.
