### ISSUE TITLE
I can not get the Room ID's for a Roborock Vacuum

### ISSUE THREAD

**Issue by keduco** [merdok/homebridge-miot#634]
**Describe the bug**
_A clear and concise description of what the bug is._

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Your config.json**
_Provide the config.json entry for your device._

**Debug log**
_Provide a snippet of a debug log when the issue occurs. Ideally with the `deepDebugLog` property enabled._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Comment by keduco** [comment]
Model is an S7 Ultra
I run the get_room_mapping and this is what is returned....
[[16,"",1],[17,"",13],[18,"",6],[21,"",3],[22,"",15],[23,"",9],[24,"",14]]
Looks like it is not pulling the room ID's from the app.  I tried all the other commands that had to deal with the map and none of them were valid.  Any ideas?  I tried using the smaller numbers 16,1,17, etc. in the action button but all it does is run a complete clean.

**Comment by keduco** [comment]
<img width="993" alt="image" src="https://github.com/user-attachments/assets/85a6d759-6cbe-4211-92a2-2b2372ef01dc">

**Comment by merdok** [comment]
If the room ids are missing then maybe they are not configured properly?

**Comment by markusv** [comment]
what wa the solution to this? I have the same problem.
