### ISSUE TITLE
Add function to set "Warm" and "Heat" mode

### ISSUE THREAD

**Issue by stocksnjerry** [merdok/homebridge-miot#637]
**Describe the idea or improvement**
I have the Xiaomi Smart Heater Fan and it has two main speeds or heating modes, warm and heat. Warm uses around 1200 watt and heat uses the full capacity of 2000 watt. In the Mi Home app you can adjust this but not in Apple Home. Would be great.

**Describe the solution you'd like**
Set warm and heat mode

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by merdok** [comment]
Hello, you should be able to use propertyControl to expose the needed properties in HomeKit. Did you try that out? You can find more about that with examples in the README.

**Comment by stocksnjerry** [comment]
No, sorry. I have no idea what that is

Norbert Heim

**Comment by merdok** [comment]
Then please try it out, all the info on the usage should be available in the README
