### ISSUE TITLE
Device Support Request: Xiaomi Smart Air Fryer 4.5L (xiaomi.fryer.maf14)

### ISSUE THREAD

**Issue by websess** [merdok/homebridge-miot#643]
Device model
xiaomi.fryer.maf14

Device name
Xiaomi Smart Air Fryer 4.5L

Does the device require a MiCloud connection?
No (to the best of my knowledge). It seems to function locally without requiring MiCloud.

Anything special about the device?
	•	The plugin currently recognizes the device as an Unknown air fryer device.
	•	The device was successfully created, but no specific functionalities (e.g., start, stop, set temperature) are available yet.
	•	The temperature is displayed but is off and not correctly shown.

I would greatly appreciate it if support for this model could be added. Please let me know if I can provide additional details, logs, or other device-specific data to assist with development.

**Comment by websess** [comment]
Thank you for your swift response and for the suggestion to manually set the model to `careli.fryer.maf02`.

After several attempts, the temperature display now seems to be working correctly. Interestingly, it doesn’t seem to matter whether I set the model to `xiaomi.fryer.maf14` or `careli.fryer.maf02` – both seem to behave identically in this regard.

However, I am currently unable to set the cooking time. Would it be possible to add this functionality for this model?

At the moment, the plugin displays the following features:
- **On/Off Switch**: functional
- **Temperature**: Now works correctly
- **Light Switch**: Visible, but non-functional
- **Modes**: Available for selection, though I’m not using them

Here is my current configuration:

```json
{
    "name": "Fritteuse",
    "ip": "192.168.178.xxx",
    "token": "xxx",
    "deviceId": "xxx",
    "model": "xiaomi.fryer.maf14",
    "pollingInterval": 10,
    "deepDebugLog": false,
    "silentLog": false,
    "deviceEnabled": true,
    "buzzerControl": false,
    "ledControl": false,
    "childLockControl": false,
    "modeControl": false
}

**Comment by merdok** [comment]
The target temperature should be also visible as alight bulb.

**Comment by websess** [comment]
Thank you for clarification!
Now I understand that the light switch is used to control the time. Under these conditions, everything seems to be working as expected. I really appreciate your detailed response and all the effort you put into maintaining this plugin.

Thanks again for your great work!

**Comment by merdok** [comment]
Good to hear that it works now! And thanks for the suggestion and text, i have added that to the README.
