### ISSUE TITLE
Error in Air Humidifier - zhimi.humidifier.ca4

### ISSUE THREAD

**Issue by vijayramadass** [merdok/homebridge-miot#65]
27/07/2021, 20:07:00HOOBSERROR[HOOBS 1297@Air Humidifier@Air Humidifier@Rotation Speed] characteristic was supplied illegal value: number 670 exceeded maximum of 100
![Screenshot 2021-07-27 at 20 10 18](https://user-images.githubusercontent.com/83660778/127205943-732bb0c2-d03e-4b0e-bb8c-5e0aea77b15e.png)

**Comment by merdok** [comment]
Thanks for the info. I will have a look at it. 

BTW, i have removed your config.json image since i was not sure if the micloud login data provided there was real or not

**Comment by merdok** [comment]
Should be fixed in version 0.9.9
