### ISSUE TITLE
Favourite speed dmaker.airfresh.a1

### ISSUE THREAD

**Issue by blastoma** [merdok/homebridge-miot#67]
Hello!
Can you add Speed regulator for dmaker.airfresh.a1 like here https://github.com/syssi/xiaomi_airpurifier/blob/develop/docs/dmaker.airfresh.a1.yaml https://github.com/NikolayBorisov/xiaomi_airfresh?

**Comment by merdok** [comment]
The dmaker.airfresh.a1 does not support favorite speed with the miot protocol. At least i do not see it in the spec: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-fresh:0000A012:dmaker-a1:1

**Comment by blastoma** [comment]
It works for me with miio protocol
<img width="566" alt="image" src="https://user-images.githubusercontent.com/11328303/128250819-c657d465-739a-4aac-a8e1-44a3a458a65f.png">

I saw this service https://python-miio.readthedocs.io/en/latest/_modules/miio/airfresh_t2017.html?highlight=dmaker.airfresh.a1#

**Comment by blastoma** [comment]
Commands:
  get_ptc_timer       Returns a list of PTC timers.
  get_timer           Response unknown.
  info                Get miIO protocol information from the device.
  off                 Power off.
  on                  Power on.
  raw_command         Send a raw command to the device.
  reset_dust_filter   Resets filter lifetime of the dust filter.
  set_buzzer          Set sound on/off.
  set_child_lock      Set child lock on/off.
  set_display         Turn led on/off.
  set_favorite_speed  Sets the fan speed in favorite mode.
  set_mode            Set mode.
  set_ptc             Turn ptc on/off.
  set_ptc_timer       value = time.index + '-' + time.hexSum + '-' +...
  status              Retrieve properties.
  test_properties     Helper to test device properties.

**Comment by merdok** [comment]
The old miio protocol is unfortunately not supported by this plugin. 
Some devices like this one you have are mapped over micloud to the miot protocol, but unfortunately only with limited property support and that is the case here. As long as a property is exposed under the miot protocol then i can implement it, if not then unfortunately not...
