### ISSUE TITLE
Add support for zhimi.airpurifier.xa1

### ISSUE THREAD

**Issue by krmkrx** [merdok/homebridge-miot#68]
Please add support for the Xiaomi Mijia Air Purifier X (zhimi.airpurifier.xa1). Currently this is exposed as an ON/OFF switch only.

**Comment by merdok** [comment]
Will add support for that device in the next update. Can you tell me the exact name of the device?

**Comment by krmkrx** [comment]
Thank you. 

It is this device: 
[https://de.aliexpress.com/i/1005001710827302.html](https://de.aliexpress.com/i/1005001710827302.html)

![image](https://user-images.githubusercontent.com/37005480/128257753-55cb1f14-5e86-4756-b797-f9be2e769e09.jpeg)

![image](https://user-images.githubusercontent.com/37005480/128257777-2fdd8bc1-86b3-48a4-86fc-b8d56737af67.png)

This device is currently exposed by the plugin as a simple but working ON/OFF switch. In the HomeKit device details I can see that the Plugin recognises the Air Purifier as "zhimi.airpurifier.xa1"

![image](https://user-images.githubusercontent.com/37005480/128257677-51a5facb-f95f-4730-9309-6b2830b6ef50.png)

Please note two special functions of this Air Purifier which differentiates it from the other Xiaomi Air Purifiers:

1) Shutter switch angle / Vane angle setting

![image](https://user-images.githubusercontent.com/37005480/128258008-7f70b5d6-bb6b-4439-aa29-4744fb320953.jpeg)

2) VOC Sensor

![image](https://user-images.githubusercontent.com/37005480/128258047-33257017-51c5-4412-ba6c-7b755763113d.jpeg)

**Comment by merdok** [comment]
Version 0.9.9 now has support for the device! Please try it out and let me know!

**Comment by merdok** [comment]
Try to set a higher polling interval value to reduce the load on the device.
