### ISSUE TITLE
Add support for TROUVER Finder

### ISSUE THREAD

**Issue by HomebridgeX** [merdok/homebridge-miot#69]
Please add support for the Trouver Robot LDS Vacuum-Mop Finder (MODEL: dreame vacuum p2036). Thank you.

**Comment by merdok** [comment]
Thanks for the request. Will add support for that vacuum in the next update.

**Comment by HomebridgeX** [comment]
Thank you for the quick answer and for the effort.

**Comment by merdok** [comment]
Version 0.9.9 now has support for the device! Please try it out and let me know!

**Comment by HomebridgeX** [comment]
It works great, thank you very much
