### ISSUE TITLE
Add new device (hanyi.airpurifier.kj550)

### ISSUE THREAD

**Issue by shin2012** [merdok/homebridge-miot#72]
Could you consider add this device?

Exact model name is "MiWhole Air Purifier Mix".
currently the on/off switch is working, but can't connect with humidity and temperature.
(fan level is not working also).

**Comment by merdok** [comment]
Yes, it should be possible! Will check it out!

**Comment by merdok** [comment]
Support is now added as of version 0.9.10!

**Comment by shin2012** [comment]
> Support is now added as of version 0.9.10!

It does works well! Thank you 👍 
Have a nice day!
