### ISSUE TITLE
Add support for device: dreame.vacuum.p2029

### ISSUE THREAD

**Issue by djsmix** [merdok/homebridge-miot#73]
its just like Z10 but without the bin for dust. :)

**Comment by djsmix** [comment]
its just like Z10 but without the bin for dust. :)

**Comment by merdok** [comment]
Should be straight forward! Will add support for it in the next update!

**Comment by djsmix** [comment]
> Should be straight forward! Will add support for it in the next update!

How often do you do updates?

**Comment by merdok** [comment]
There is no schedule, usually when i think that there are enough changes then i update :) But the next update will be definitely next week, but not sure what day.

BTW, what is the exact name of your device?

**Comment by djsmix** [comment]
Dreame Bot L10 Pro

**Comment by merdok** [comment]
BTW, i see that as you say the device is pretty much identical to the dreame.vacuum.p2028 (Z10 ), so if you cannot wait till next week you can force to use the Z10 spec by specifying the `model` manually in the config.json as `dreame.vacuum.p2028 `. That should make your device already work now, but just remember when the update comes out that you have to remove the model line so that the correct spec is used!

**Comment by djsmix** [comment]
> BTW, i see that as you say the device is pretty much identical to the dreame.vacuum.p2028 (Z10 ), so if you cannot wait till next week you can force to use the Z10 spec by specifying the `model` manually in the config.json as `dreame.vacuum.p2028 `. That should make your device already work now, but just remember when the update comes out that you have to remove the model line so that the correct spec is used!

I will give it a try tomorrow!

**Comment by merdok** [comment]
Support is now added as of version 0.9.10!

**Comment by djsmix** [comment]
Hi! thanks!

seems like the "Charging" status does not work. when its connected to the dock its shows "Charging: no" in apple homekit and in homebridge

**Comment by merdok** [comment]
When it is connected to the dock and the battery is 100% the device will not charge so it will not charging.
The active mode is basic so the tile will be on even when the vacuum is in the dock, that is wanted behavior since you are able to switch modes when the vacuum is currently not cleaning.

**Comment by djsmix** [comment]
Can i see the total cleaned area/brush life etc in apple homekit?

**Comment by merdok** [comment]
In HomeKit currently not, it is logged in the console. There is no accessory which can display such info. But I could actually use the lux sensor for that...
