### ISSUE TITLE
Xiaomi robot vaccum G1 problem

### ISSUE THREAD

**Issue by henkyfoo** [merdok/homebridge-miot#74]
hi,

the plugin suddenly didn't work with robot vaccum G1 anymore
the log doesn't show any error

my other vaccum 1C just working fine

G1 couldn't be turn on or off. (it doesn't show the battery level too)

here is the log
Robot Vaccum 2] Got device configuration, initializing device with name: Robot Vaccum 2
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Device model known: mijia.vacuum.v2! Creating device!
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Initializing device properties
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Initializing device actions
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Device actions: [
  "start_sweep",
  "stop_sweep",
  "start_charge",
  "reset_brush_life",
  "reset_side_brush_life",
  "reset_filter_life",
  "locate_robot",
  "go_charge",
  "stop_charge"
]
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Successfully created a RobotCleaner device! It is a Xiaomi Mi Robot Vacuum Mop G1.
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Initializing accessory!
8/13/2021, 8:10:32 PMMiot Bridgemiot[Robot Vaccum 2] Accessory successfully initialized!
8/13/2021, 8:10:32 PMMiot BridgeBridge is running on port 56826.

**Comment by merdok** [comment]
I guess your device token or ip address has changed. Make sure that they are correct. You can also post a homebridge debug log here then you will probably see the issue...
