### ISSUE TITLE
Mijia Robot Vacuum-Mop 2C

### ISSUE THREAD

**Issue by qrsy2k** [merdok/homebridge-miot#75]
Hi Merdok,

Any plan to include the Vacuum 2C to your list of supported devices? Thanks

Name: Mijia Robot Vacuum-Mop 2C
Model: dreame.vacuum.p2140

**Comment by merdok** [comment]
Hi,

i can do that! But it might take some time since I am on vacation right now...

**Comment by merdok** [comment]
In the meantime you can actually put the dreame.vacuum.p2029 as the model in the config since this vaccum is basically identical to yours so it should also work till i add proper support.

**Comment by qrsy2k** [comment]
Nice thanks!

**Comment by merdok** [comment]
Support is now included in version 0.9.11
