### ISSUE TITLE
Add support for Mi Smart Bathroom Heater Pro\Mi Body Composition Scale2 能否增加米家智能浴霸pro、小米体脂秤2 的支持

### ISSUE THREAD

**Issue by i7s7x** [merdok/homebridge-miot#78]
Link:https://www.mi.com/buy/detail?product_id=12791
Name：Mi Smart Bathroom Heater Pro
Model Name: yeelink.bhf_light.v5
model number：YB01

Link:https://www.mi.com/scale2
Name：Mi Body Composition Scale2
Model Name:
model number：XMTZC05HM

**Comment by merdok** [comment]
Hello,

the bath heater should be no problem, although it will take some time since i need to create a new accessory type.
About the scale i am not sure if it will be possible since there is no scale accessory in homekit. Also what is the model name of the scale?

**Comment by i7s7x** [comment]
thank you for your reply.&nbsp;
I can't get the model name of the scale temporarily because I don't know how to get it. I tried to contact Xiaomi's customer service, but I didn't get the desired result. The model name that can get the bath heater is the mijia APP modified by the Russians, but this does not apply to the scale.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "merdok/homebridge-miot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [merdok/homebridge-miot] Add support for Mi Smart Bathroom Heater Pro\Mi Body Composition Scale2 能否增加米家智能浴霸pro、小米体脂秤2 的支持 (#78)





 
Hello,
 
the bath heater should be no problem, although it will take some time since i need to create a new accessory type.
 About the scale i am not sure if it will be possible since there is no scale accessory in homekit. Also what is the model name of the scale?
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by merdok** [comment]
Are you sure that the scale has WiFi? I think the scale have only a Bluetooth connection which will not work here...

**Comment by i7s7x** [comment]
Sorry, it is indeed the scale have only a Bluetooth connection

**Comment by merdok** [comment]
Support for the bath heater is now included in version 0.9.11
