### ISSUE TITLE
Can you join support for XiaoMi Philips light?

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#81]
The homebridge-mi-philips-light plug-in has not been updated for a long time, and there are often warnings like this: This plugin generated a warning from the characteristic'Color Temperature': characteristic was supplied illegal value: number 25550 exceeded maximum of 400. See https:/ /git.io/JtMGR for more info.
Plug-in address: https://github.com/YinHangCode/homebridge-mi-philips-light
I have contacted the developer of this plugin, and he has no intention of fixing it.
So are you interested in adding support for XiaoMi Philips light, especially MiPhilipsSmartBulb

**Comment by merdok** [comment]
Hi, 
those are old devices which use the old miio protocol so local control will not be possible with this plugin. Nevertheless it could be possible to add support for them using the MiCloud. If you give me the **model** name of the device or devices then i can check it out!

**Comment by louliangsheng** [comment]
the model name of the device ：philips.light.bulb

**Comment by merdok** [comment]
Yes, that should be possible but like i said only using the MiCloud, so you will have to specify your MiCloud credentials in the json.

**Comment by merdok** [comment]
@louliangsheng you had luck since i am flying for a longer holiday in a couple of hours, but i still quickly added the light. Check out the just released version 0.9.12, it should work now!

**Comment by louliangsheng** [comment]
wow ！！thank you very much, the update speed is too fast

**Comment by louliangsheng** [comment]
Thank you very much!! XiaoMi Philips light is working perfectly.

**Comment by merdok** [comment]
Good to hear! 👍
