### ISSUE TITLE
Please add the support of Viomi Kettle 🙏🙏

### ISSUE THREAD

**Issue by Pacoakm** [merdok/homebridge-miot#82]
Hello, would you please add the support of the Viomi Kettle? You can create a lightbulb to control the temperature of water. And also display the TDS value and water remain time. Here are the details:

model: yunmi.kettle.r3 [https://ws.izenecdn.com/pms/2020/08/1a184e34a1a763f033892513f726dd41.jpeg](url)
Here is the github link of home assistant: [https://github.com/lukezzz/homeassistant-yunmi-kettle](url)

**Comment by merdok** [comment]
Hi,

does the kettle have wifi or is it Bluetooth?

**Comment by Pacoakm** [comment]
Oh, the kettle can use wifi, you can find the token directly

**Comment by merdok** [comment]
Then I guess it should be no problem! But since I am right now on holiday it will take some time till I can check it out, so please be patient...

**Comment by Pacoakm** [comment]
Ok, thank you very much😀. Hope that you can success!

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.13
