### ISSUE TITLE
Please add support for Aqara Curtain Controller A1 (ZNCLDJ21LM)

### ISSUE THREAD

**Issue by drhamazani** [merdok/homebridge-miot#85]
This is the WiFi version of the Aqara curtain motor.
Unlike other Aqara devices, this model doesn't support Zigbee protocol and doesn't connect to the Aqara hub.
I have logged into my MiCloud and the miot recognized the model as **lumi.curtain.hagl08** as shown below.
A switch appeared in the Home App but it doesn't do any action.

> [miot] Initializing miot platform...
> [miot] Initializing devices
> [miot] [Curtain 1] Got device configuration, initializing device with name: Curtain 1
> [miot] [Curtain 1] Device model known: lumi.curtain.hagl08! Creating device!
> [miot] [Curtain 1] Initializing device properties
> [miot] [Curtain 1] Initializing device actions
> [miot] [Curtain 1] Device not supported! Using a generic device with limited properties! Consider requesting device support!
> [miot] [Curtain 1] Initializing accessory!
> [miot] [Curtain 1] Accessory successfully initialized!
> [miot] [Curtain 1] Connected to device: lumi.curtain.hagl08
> [miot] [Curtain 1] Setting up device!
> [miot] [Curtain 1] Doing device specific setup
> [miot] [Curtain 1] Doing initial property fetch
> [miot] [Curtain 1] Device setup finished! Device ready, you can now control your device!

Could you please support this device?
Thanks

**Comment by merdok** [comment]
That should not be a problem! Support will be added in the next update :)

**Comment by merdok** [comment]
The device should now be supported as of version 0.9.13

**Comment by kevinjohncutler** [comment]
@drhamazani How did you add the A1? I can't figure out how to get its device token, given that it is set up with Aqara and not Mi Home.

**Comment by merdok** [comment]
The token should be in your mi cloud account. Just use the homebridge ui preferences of this plugin to get a list of device from your micloud account including the tokens.

**Comment by kevinjohncutler** [comment]
@merdok that's for your response. What's confusing me is that I cannot add this device in mi home. Are Aqara devices usually compatible with the Mi Home app?

**Comment by merdok** [comment]
That i cannot answer you since i do not have any.
