### ISSUE TITLE
Version 0.9.13 Unable to Load Settings

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#88]
Hi,

Seems like the new version 0.9.13 caused the Settings page of the plugin failed to load. Here’s what I’m seeing:

![184D8F1D-EEBD-43B7-8734-8AD8BA09D8B0](https://user-images.githubusercontent.com/66505845/134334227-a5d6b7dc-b8be-4153-bac8-a1e40379e629.jpeg)

Luckily I could go back to previous version.

**Comment by merdok** [comment]
Thanks for the info! Fixed in version 0.9.14!
