### ISSUE TITLE
Please add support for the Smartmi Ventilation System (XFXT01ZM)

### ISSUE THREAD

**Issue by oleg77s** [merdok/homebridge-miot#90]
Please add support for the Smartmi Ventilation System:
Model: zhimi.airfresh.va2
Region: cn

**Comment by merdok** [comment]
Should be straight forward. Will add it in the next update!

**Comment by merdok** [comment]
Also please note that this is an older miio device which will require MiCloud

**Comment by oleg77s** [comment]
ok

**Comment by merdok** [comment]
The device is now added in version 0.9.16

**Comment by oleg77s** [comment]
yes. it appear, but how to disable it?

**Comment by merdok** [comment]
You cannot disable it since it is not an extra switch but part of the accessory.

**Comment by oleg77s** [comment]
ok
