### ISSUE TITLE
Please add support for the Xiaomi Chuangmi Plug V3 (chuangmi.plug.v3) ZNCZ03CM

### ISSUE THREAD

**Issue by oleg77s** [merdok/homebridge-miot#92]
Please add support for the Xiaomi Chuangmi Plug V3 (with 2 USB):
Model: chuangmi.plug.v3
Region: cn

**Comment by merdok** [comment]
Support for this device will be added in the next update. Please note that this is an older miio device which will require MiCloud

**Comment by merdok** [comment]
The device is now added in version 0.9.16

**Comment by merdok** [comment]
Oh, you are right! The usb is currently linked to the main power, which causes your behavior! I will fix that in the next update!

**Comment by oleg77s** [comment]
ok

**Comment by oleg77s** [comment]
It's ok now 👍
