### ISSUE TITLE
Please add the support of Xiaomi Gateway 3

### ISSUE THREAD

**Issue by Pacoakm** [merdok/homebridge-miot#95]
Hello! Would you please add the support of Xiaomi Gateway 3. There is a 'Mi Aqara' plugin on homebridge but it can just support the gateway 2. Hope you can write a plugin for gateway 3.
model: lumi.gateway.mgl03
the photo: https://sc04.alicdn.com/kf/H4a6227477676432ab8d3ed5c378a62b4R.jpg
the homeassistant plugin: https://github.com/AlexxIT/XiaomiGateway3

**Comment by merdok** [comment]
Hi,
I was wondering why would you like to have the gateway in homekit? What would you like to control on it?

**Comment by Pacoakm** [comment]
Oh, there are many sub devices under the gateway, like motion sensor and outlet. I want this plugin to support the sub devices mainly, not just the gateway : )

**Comment by merdok** [comment]
This as far as i saw is not possible. You can only control the gateway like enable/disable some settings (led, alarm) but there is no access to the bridge sub devices.

**Comment by merdok** [comment]
You can now add the gateway to this plugin and use the `propertyControl` to expose any functionally which you want as of version 1.0.0.
