### ISSUE TITLE
Air Humidifier 2 (zhimi.humidifier.ca4) always shows extra switches for screen control, ignoring corresponding flags.

### ISSUE THREAD

**Issue by kikiwora** [merdok/homebridge-miot#97]
Air Humidifier 2 (zhimi.humidifier.ca4) always shows extra switches for screen control, ignoring corresponding flags.
The Screen control service (Humidifier-specific) and LED control service (generic) are both set to false, yet, the switches for screen brightness control are always added despite this fact 

Also, the fan speed control is way out of allowed range, this literally forces the device to make a horrible noise.
And there is no way to set its mode to "automatic" using the fan speed slider, as far as I can see. 

[This plugin](https://github.com/russtone/homebridge-mi-humidifier#readme) works better.

**Comment by merdok** [comment]
You would need to post your config so i can have a look if there everything is set correctly.
