### ISSUE TITLE
Desktop Lamp (yeelink.light.lamp1) does not work. The device is added, but only as a non-working switch

### ISSUE THREAD

**Issue by kikiwora** [merdok/homebridge-miot#99]
Lamp is added as switch that does nothing.

The [Yeelighter](https://www.npmjs.com/package/homebridge-yeelighter) plugin works almost fine.

**Comment by merdok** [comment]
The `yeelink.light.lamp1` is not supported yet as you can see here: https://github.com/merdok/homebridge-miot/blob/main/supported_devices.md, you can make a support request for that device!
